import type { PoolConnection, RowDataPacket } from 'mysql2/promise';
import { getPool, withTransaction } from '../database/pool';
import { recalculateCharacterStats } from './character.service';

type WeaponRow = RowDataPacket & { id: number; name: string; quality: number; rarity: string; required_level: number; fusion_count: number };
type MaterialRow = RowDataPacket & { id: number; name: string; item_category: string; quantity: number; min_gain?: number; max_gain?: number; effect_json?: unknown; description?: string };
const rarityBonus: Record<string, number> = { '普通': 0, '优秀': 1, '精良': 2, '稀有': 3, '传说': 4, '史诗': 5, '神器': 6 };
const jsonRecord = (value: unknown): Record<string, unknown> => { if (!value) return {}; if (typeof value !== 'string') return value as Record<string, unknown>; try { return JSON.parse(value) as Record<string, unknown>; } catch { return {}; } };
const fusionLimit = (weapon: Pick<WeaponRow, 'rarity' | 'required_level'>) => Math.floor(Math.max(0, Number(weapon.required_level)) / 10) + (rarityBonus[weapon.rarity] ?? 0);
const characterIdFor = async (connection: PoolConnection | Awaited<ReturnType<typeof getPool>>, qqUserId: string, lock = false) => {
  const [rows] = await connection.execute<(RowDataPacket & { id: number })[]>(`SELECT c.id FROM characters c JOIN players p ON p.id=c.player_id WHERE p.qq_user_id=? LIMIT 1${lock ? ' FOR UPDATE' : ''}`, [qqUserId]);
  if (!rows[0]) throw new Error('请先注册角色。');
  return Number(rows[0].id);
};
const weaponsFor = async (connection: PoolConnection | Awaited<ReturnType<typeof getPool>>, characterId: number) => {
  const [rows] = await connection.execute<WeaponRow[]>(`SELECT ii.id,i.name,ii.quality,i.rarity,i.required_level,COUNT(ef.id) AS fusion_count FROM player_item_instances ii JOIN item_definitions i ON i.id=ii.item_id LEFT JOIN equipment_fusions ef ON ef.instance_id=ii.id WHERE ii.character_id=? AND i.item_type='equipment' AND i.item_category='武器' GROUP BY ii.id,i.name,ii.quality,i.rarity,i.required_level ORDER BY ii.acquired_at DESC,ii.id DESC`, [characterId]);
  return rows.map(row => ({ id: Number(row.id), name: row.name, quality: Number(row.quality), rarity: row.rarity, requiredLevel: Number(row.required_level), fusionCount: Number(row.fusion_count), fusionLimit: fusionLimit(row) }));
};
export const blacksmithWeapons = async (qqUserId: string) => weaponsFor(await getPool(), await characterIdFor(await getPool(), qqUserId));
export const refinementMaterials = async (qqUserId: string) => {
  const pool = await getPool(); const characterId = await characterIdFor(pool, qqUserId);
  const [rows] = await pool.execute<MaterialRow[]>(`SELECT i.id,i.name,i.item_category,pi.quantity,rm.min_gain,rm.max_gain FROM player_inventory pi JOIN item_definitions i ON i.id=pi.item_id JOIN blacksmith_refinement_materials rm ON rm.item_id=i.id WHERE pi.character_id=? AND pi.quantity>0 ORDER BY i.id`, [characterId]);
  return rows.map(row => ({ id: Number(row.id), name: row.name, category: row.item_category, quantity: Number(row.quantity), minGain: Number(row.min_gain), maxGain: Number(row.max_gain) }));
};
export const fusionMaterials = async (qqUserId: string) => {
  const pool = await getPool(); const characterId = await characterIdFor(pool, qqUserId);
  const [rows] = await pool.execute<MaterialRow[]>(`SELECT i.id,i.name,i.item_category,pi.quantity,fe.effect_json,fe.description FROM player_inventory pi JOIN item_definitions i ON i.id=pi.item_id LEFT JOIN blacksmith_fusion_material_effects fe ON fe.item_id=i.id WHERE pi.character_id=? AND pi.quantity>0 AND i.item_type='material' AND i.item_category<>'货币' ORDER BY i.item_category,i.name`, [characterId]);
  return rows.map(row => ({ id: Number(row.id), name: row.name, category: row.item_category, quantity: Number(row.quantity), effect: jsonRecord(row.effect_json), description: row.description ?? '可熔入装备，形成随机的基础强化。' }));
};
const refinementGain = (minimum: number, maximum: number, quality: number) => {
  const min = Math.max(1, Math.ceil(minimum)); const max = Math.max(min, Math.floor(maximum));
  const candidates = Array.from({ length: max - min + 1 }, (_, index) => min + index);
  const weights = candidates.map(value => Math.pow(max - value + 1, 1 + quality / 45));
  if (quality >= 80) weights[weights.length - 1] *= 0.03;
  let roll = Math.random() * weights.reduce((sum, weight) => sum + weight, 0);
  return candidates[weights.findIndex(weight => (roll -= weight) <= 0)] ?? min;
};
export const refineWeapon = async (qqUserId: string, instanceId: number, materialId: number) => withTransaction(async connection => {
  const characterId = await characterIdFor(connection, qqUserId, true);
  const [weapons] = await connection.execute<(WeaponRow & { item_id: number })[]>(`SELECT ii.id,ii.item_id,i.name,ii.quality,i.rarity,i.required_level,0 AS fusion_count FROM player_item_instances ii JOIN item_definitions i ON i.id=ii.item_id WHERE ii.id=? AND ii.character_id=? AND i.item_type='equipment' AND i.item_category='武器' FOR UPDATE`, [instanceId, characterId]);
  const weapon = weapons[0]; if (!weapon) throw new Error('请选择自己背包中的武器。');
  if (Number(weapon.quality) >= 100) throw new Error('该武器品质已达到 100%。');
  const [materials] = await connection.execute<MaterialRow[]>(`SELECT i.id,i.name,i.item_category,pi.quantity,rm.min_gain,rm.max_gain FROM player_inventory pi JOIN item_definitions i ON i.id=pi.item_id JOIN blacksmith_refinement_materials rm ON rm.item_id=i.id WHERE pi.character_id=? AND i.id=? FOR UPDATE`, [characterId, materialId]);
  const material = materials[0]; if (!material || Number(material.quantity) < 1) throw new Error('没有可用的精炼材料。');
  await connection.execute('UPDATE player_inventory SET quantity=quantity-1 WHERE character_id=? AND item_id=?', [characterId, materialId]);
  await connection.execute('DELETE FROM player_inventory WHERE character_id=? AND item_id=? AND quantity<=0', [characterId, materialId]);
  const quality = Number(weapon.quality); const failed = quality >= 90 && Math.random() >= Math.max(.35, .8 - (quality - 90) * .045);
  if (failed) return { name: weapon.name, material: material.name, oldQuality: quality, newQuality: quality, gain: 0, failed: true, great: false };
  const great = Math.random() < .03; const gain = Math.min(100 - quality, refinementGain(Number(material.min_gain), Number(material.max_gain), quality) * (great ? 2 : 1)); const newQuality = Math.round((quality + gain) * 100) / 100;
  await connection.execute('UPDATE player_item_instances SET quality=? WHERE id=?', [newQuality, instanceId]);
  await recalculateCharacterStats(connection, characterId);
  return { name: weapon.name, material: material.name, oldQuality: quality, newQuality, gain, failed: false, great };
});
const fallbackFusion = (category: string) => category === '草药' ? { hpPct: 1 } : category === '兽材' ? { physicalAttackPct: 1 } : category === '锻材' ? { physicalDefensePct: 1 } : { magicAttackPct: 1 };
export const fuseWeapon = async (qqUserId: string, instanceId: number, materialId: number) => withTransaction(async connection => {
  const characterId = await characterIdFor(connection, qqUserId, true);
  const [weapons] = await connection.execute<(WeaponRow & { effect_json: unknown; item_id: number })[]>(`SELECT ii.id,ii.item_id,i.name,ii.quality,i.rarity,i.required_level,COALESCE(ii.effect_json,i.effect_json) AS effect_json,(SELECT COUNT(*) FROM equipment_fusions ef WHERE ef.instance_id=ii.id) AS fusion_count FROM player_item_instances ii JOIN item_definitions i ON i.id=ii.item_id WHERE ii.id=? AND ii.character_id=? AND i.item_type='equipment' AND i.item_category='武器' FOR UPDATE`, [instanceId, characterId]);
  const weapon = weapons[0]; if (!weapon) throw new Error('请选择自己背包中的武器。');
  const limit = fusionLimit(weapon); if (Number(weapon.fusion_count) >= limit) throw new Error(`该武器的熔铸次数已用尽（${weapon.fusion_count}/${limit}）。`);
  const [materials] = await connection.execute<MaterialRow[]>(`SELECT i.id,i.name,i.item_category,pi.quantity,fe.effect_json,fe.description FROM player_inventory pi JOIN item_definitions i ON i.id=pi.item_id LEFT JOIN blacksmith_fusion_material_effects fe ON fe.item_id=i.id WHERE pi.character_id=? AND i.id=? AND i.item_type='material' AND i.item_category<>'货币' FOR UPDATE`, [characterId, materialId]);
  const material = materials[0]; if (!material || Number(material.quantity) < 1) throw new Error('请选择背包中的熔铸材料。');
  const added = Object.keys(jsonRecord(material.effect_json)).length ? jsonRecord(material.effect_json) : fallbackFusion(material.item_category);
  const current = jsonRecord(weapon.effect_json); const merged = { ...current };
  for (const [key, value] of Object.entries(added)) merged[key] = Math.round((Number(merged[key] ?? 0) + Number(value)) * 100) / 100;
  await connection.execute('UPDATE player_inventory SET quantity=quantity-1 WHERE character_id=? AND item_id=?', [characterId, materialId]);
  await connection.execute('DELETE FROM player_inventory WHERE character_id=? AND item_id=? AND quantity<=0', [characterId, materialId]);
  await connection.execute('UPDATE player_item_instances SET effect_json=? WHERE id=?', [JSON.stringify(merged), instanceId]);
  await connection.execute('INSERT INTO equipment_fusions (instance_id,material_item_id,effect_json) VALUES (?,?,?)', [instanceId, materialId, JSON.stringify(added)]);
  await recalculateCharacterStats(connection, characterId);
  return { name: weapon.name, material: material.name, effect: added, count: Number(weapon.fusion_count) + 1, limit };
});

const forgeContribution = (code: string) => ({ living_wood: 15, refined_iron: 25, star_copper: 35, moon_silver: 45, sun_gold: 60, beast_meat: 3, beast_bone: 7, beast_hide: 7, beast_tendon: 8, beast_core: 12, magic_wool: 15, magic_tusk: 18, magic_scale: 18, magic_claw: 18, magic_heartcore: 20, riot_aura: 30 }[code] ?? 5);
const random = (min: number, max: number) => Math.floor(Math.random() * (max - min + 1)) + min;
const forgeCategories = new Set(['武器', '头肩', '上装', '腰部', '下装', '脚部']);
const weaponTypes = new Set(['长剑', '法杖', '匕首', '拳刃']); const armorTypes = new Set(['布甲', '皮甲', '轻甲', '重甲', '板甲']);
const forgeName = (category: string, subtype: string, level: number, rarity: string) => `${({ '普通': '粗制', '优秀': '精工', '精良': '锐利', '稀有': '星辉', '传说': '辉煌', '史诗': '圣铸', '神器': '神铸' }[rarity] ?? '锻造')}·${subtype}${category === '武器' ? '' : category}·Lv.${level}`;
const forgeRarity = (score: number) => score >= 220 ? '史诗' : score >= 170 ? '传说' : score >= 125 ? '稀有' : score >= 80 ? '精良' : score >= 45 ? '优秀' : '普通';
const baseForgeEffect = (category: string, subtype: string, level: number): Record<string, number> => {
  const value = Math.max(1, level);
  if (category === '武器') {
    if (subtype === '法杖') return { magicAttack: random(value * 3, value * 5), mpMax: random(value * 5, value * 8) };
    if (subtype === '匕首') return { physicalAttack: random(value * 2, value * 4), accuracy: random(value * 2, value * 4), evasion: random(value, value * 2) };
    if (subtype === '拳刃') return { physicalAttack: random(value * 2, value * 4), magicAttack: random(value, value * 2), critRateBp: random(value * 2, value * 4) };
    return { physicalAttack: random(value * 3, value * 5), physicalDefense: random(value, value * 2) };
  }
  const armor = subtype === '布甲' ? { magicDefense: 4, mpMax: 6 } : subtype === '皮甲' ? { physicalDefense: 3, evasion: 3 } : subtype === '轻甲' ? { physicalDefense: 4, magicDefense: 3, speed: 1 } : subtype === '重甲' ? { physicalDefense: 6, magicDefense: 3, hpMax: 5 } : { physicalDefense: 8, magicDefense: 4, hpMax: 7 };
  return Object.fromEntries(Object.entries(armor).map(([key, amount]) => [key, random(value * amount, value * amount + value * 2)]));
};
const forgeMaterialEffect = (code: string): Record<string, number> => ({ beast_bone: { physicalAttack: random(1, 3) }, beast_hide: { physicalDefense: random(1, 3) }, beast_tendon: { speed: random(1, 2) }, beast_core: { magicAttack: random(1, 3) }, magic_wool: { evasionPct: random(1, 3) }, magic_tusk: { physicalAttackPct: random(1, 3) }, magic_scale: { magicDefensePct: random(1, 3) }, magic_claw: { critRatePct: random(1, 3) }, magic_heartcore: { accuracyPct: random(1, 3) }, living_wood: { hpMax: random(2, 5) }, refined_iron: { physicalDefense: random(3, 6) }, star_copper: { accuracy: random(3, 6) }, moon_silver: { mpPct: random(1, 3) }, sun_gold: { physicalAttackPct: random(1, 2), magicAttackPct: random(1, 2) }, riot_aura: { magicDamagePct: random(1, 3) } }[code] ?? { hpMax: 1 }) as Record<string, number>;
const mergeEffect = (base: Record<string, number>, incoming: Record<string, number>) => { for (const [key, value] of Object.entries(incoming)) base[key] = Math.round((Number(base[key] ?? 0) + Number(value)) * 100) / 100; return base; };
export const forgeState = async (qqUserId: string) => {
  const pool = await getPool(); const characterId = await characterIdFor(pool, qqUserId);
  const [sessions] = await pool.execute<(RowDataPacket & { equipment_category: string | null; subtype: string | null; target_level: number | null })[]>('SELECT equipment_category,subtype,target_level FROM player_forge_sessions WHERE character_id=?', [characterId]);
  const [materials] = await pool.execute<(MaterialRow & { code: string })[]>(`SELECT i.id,i.code,i.name,i.item_category,pi.quantity,COALESCE(fm.quantity,0) AS selected_quantity FROM player_inventory pi JOIN item_definitions i ON i.id=pi.item_id LEFT JOIN player_forge_materials fm ON fm.character_id=pi.character_id AND fm.item_id=pi.item_id WHERE pi.character_id=? AND pi.quantity>0 AND i.item_type='material' AND i.item_category<>'货币' ORDER BY i.item_category,i.name`, [characterId]);
  const selected = materials.filter(item => Number((item as any).selected_quantity) > 0).map(item => ({ id: Number(item.id), name: item.name, quantity: Number((item as any).selected_quantity), contribution: forgeContribution(item.code) }));
  return { category: sessions[0]?.equipment_category ?? null, subtype: sessions[0]?.subtype ?? null, level: sessions[0]?.target_level === null || !sessions[0] ? null : Number(sessions[0].target_level), materials: materials.map(item => ({ id: Number(item.id), name: item.name, code: item.code, category: item.item_category, quantity: Number(item.quantity), selected: Number((item as any).selected_quantity ?? 0), contribution: forgeContribution(item.code) })), selected, success: Math.min(100, selected.reduce((sum, item) => sum + item.quantity * item.contribution, 0)) };
};
export const selectForgeCategory = async (qqUserId: string, category: string) => withTransaction(async connection => { if (!forgeCategories.has(category)) throw new Error('该装备部位暂不支持打造。'); const characterId = await characterIdFor(connection, qqUserId, true); await connection.execute('INSERT INTO player_forge_sessions (character_id,equipment_category,subtype,target_level) VALUES (?,?,NULL,NULL) ON DUPLICATE KEY UPDATE equipment_category=VALUES(equipment_category),subtype=NULL,target_level=NULL', [characterId, category]); await connection.execute('DELETE FROM player_forge_materials WHERE character_id=?', [characterId]); return category; });
export const selectForgeSubtype = async (qqUserId: string, subtype: string) => withTransaction(async connection => { const characterId = await characterIdFor(connection, qqUserId, true); const [rows] = await connection.execute<(RowDataPacket & { equipment_category: string | null })[]>('SELECT equipment_category FROM player_forge_sessions WHERE character_id=? FOR UPDATE', [characterId]); const category = rows[0]?.equipment_category; if (!category) throw new Error('请先选择打造部位。'); if (category === '武器' ? !weaponTypes.has(subtype) : !armorTypes.has(subtype)) throw new Error('该装备类型不可用。'); await connection.execute('UPDATE player_forge_sessions SET subtype=?,target_level=NULL WHERE character_id=?', [subtype, characterId]); return subtype; });
export const selectForgeLevel = async (qqUserId: string, level: number) => withTransaction(async connection => { if (level < 5 || level > 50 || level % 5) throw new Error('装备等级只能选择 5～50 级之间的 5 的倍数。'); const characterId = await characterIdFor(connection, qqUserId, true); const [rows] = await connection.execute<(RowDataPacket & { subtype: string | null })[]>('SELECT subtype FROM player_forge_sessions WHERE character_id=? FOR UPDATE', [characterId]); if (!rows[0]?.subtype) throw new Error('请先选择装备类型。'); await connection.execute('UPDATE player_forge_sessions SET target_level=? WHERE character_id=?', [level, characterId]); return level; });
export const addForgeMaterial = async (qqUserId: string, itemId: number) => withTransaction(async connection => { const characterId = await characterIdFor(connection, qqUserId, true); const [items] = await connection.execute<(MaterialRow & { code: string })[]>(`SELECT i.id,i.code,i.name,i.item_category,pi.quantity FROM player_inventory pi JOIN item_definitions i ON i.id=pi.item_id WHERE pi.character_id=? AND i.id=? AND pi.quantity>0 AND i.item_type='material' AND i.item_category<>'货币' FOR UPDATE`, [characterId, itemId]); const item = items[0]; if (!item) throw new Error('请选择背包中的材料。'); const [selected] = await connection.execute<(RowDataPacket & { quantity: number })[]>('SELECT quantity FROM player_forge_materials WHERE character_id=? AND item_id=? FOR UPDATE', [characterId, itemId]); if (Number(selected[0]?.quantity ?? 0) >= Number(item.quantity)) throw new Error('该材料没有更多可放入的数量。'); await connection.execute('INSERT INTO player_forge_materials (character_id,item_id,quantity) VALUES (?,?,1) ON DUPLICATE KEY UPDATE quantity=quantity+1', [characterId, itemId]); return { name: item.name }; });
export const removeForgeMaterial = async (qqUserId: string, itemId: number) => withTransaction(async connection => { const characterId = await characterIdFor(connection, qqUserId, true); const [rows] = await connection.execute<(RowDataPacket & { quantity: number })[]>('SELECT quantity FROM player_forge_materials WHERE character_id=? AND item_id=? FOR UPDATE', [characterId, itemId]); if (!rows[0] || Number(rows[0].quantity) < 1) throw new Error('该材料尚未放入。'); await connection.execute('UPDATE player_forge_materials SET quantity=quantity-1 WHERE character_id=? AND item_id=?', [characterId, itemId]); await connection.execute('DELETE FROM player_forge_materials WHERE character_id=? AND item_id=? AND quantity<=0', [characterId, itemId]); });
export const craftForgeEquipment = async (qqUserId: string, confirmed = false) => withTransaction(async connection => {
  const characterId = await characterIdFor(connection, qqUserId, true); const [sessions] = await connection.execute<(RowDataPacket & { equipment_category: string; subtype: string; target_level: number })[]>('SELECT equipment_category,subtype,target_level FROM player_forge_sessions WHERE character_id=? FOR UPDATE', [characterId]); const session = sessions[0]; if (!session?.equipment_category || !session.subtype || !session.target_level) throw new Error('请完成打造目标选择。');
  const [materials] = await connection.execute<(MaterialRow & { code: string; selected_quantity: number })[]>(`SELECT i.id,i.code,i.name,i.item_category,pi.quantity,fm.quantity AS selected_quantity FROM player_forge_materials fm JOIN player_inventory pi ON pi.character_id=fm.character_id AND pi.item_id=fm.item_id JOIN item_definitions i ON i.id=fm.item_id WHERE fm.character_id=? FOR UPDATE`, [characterId]); if (!materials.length) throw new Error('请先放入打造材料。'); const shortage = materials.find(item => Number(item.quantity) < Number(item.selected_quantity)); if (shortage) throw new Error(`材料不足：${shortage.name}。`);
  const score = materials.reduce((sum, item) => sum + forgeContribution(item.code) * Number(item.selected_quantity), 0); const success = Math.min(100, score); if (success < 100 && !confirmed) return { needsConfirm: true as const, success, score };
  const [coins] = await connection.execute<(RowDataPacket & { copper_coins: number })[]>('SELECT copper_coins FROM characters WHERE id=? FOR UPDATE', [characterId]); if (Number(coins[0]?.copper_coins ?? 0) < 60) throw new Error('铜币不足，打造手续费需要 60 铜币。');
  for (const material of materials) await connection.execute('UPDATE player_inventory SET quantity=quantity-? WHERE character_id=? AND item_id=?', [material.selected_quantity, characterId, material.id]); await connection.execute('DELETE FROM player_inventory WHERE character_id=? AND quantity<=0', [characterId]); await connection.execute('UPDATE characters SET copper_coins=copper_coins-60 WHERE id=?', [characterId]); await connection.execute('DELETE FROM player_forge_materials WHERE character_id=?', [characterId]);
  if (Math.random() * 100 >= success) return { needsConfirm: false as const, success, failed: true as const };
  const rarity = forgeRarity(score); const effect = baseForgeEffect(session.equipment_category, session.subtype, Number(session.target_level)); for (const material of materials) for (let i = 0; i < Number(material.selected_quantity); i++) mergeEffect(effect, forgeMaterialEffect(material.code)); const name = forgeName(session.equipment_category, session.subtype, Number(session.target_level), rarity); const code = `crafted_${characterId}_${Date.now()}_${Math.floor(Math.random() * 100000)}`; const quality = Math.min(100, Math.max(0, Math.round((15 + score * .35 + random(-8, 8)) * 100) / 100));
  const [definition] = await connection.execute<any>('INSERT INTO item_definitions (code,name,description,obtain_source,item_type,item_category,weapon_type,rarity,required_level,weight,stackable,effect_json) VALUES (?,?,?,?,?,?,?,?,?,?,0,?)', [code, name, `由铁匠铺打造的 Lv.${session.target_level}${session.subtype}。`, '百纳镇铁匠铺打造', 'equipment', session.equipment_category, session.equipment_category === '武器' ? session.subtype : null, rarity, session.target_level, 2, JSON.stringify(effect)]); const [instance] = await connection.execute<any>('INSERT INTO player_item_instances (character_id,item_id,quality,durability,durability_max,effect_json) VALUES (?,?,?,100,100,?)', [characterId, definition.insertId, quality, JSON.stringify(effect)]); await connection.execute('DELETE FROM player_forge_sessions WHERE character_id=?', [characterId]);
  return { needsConfirm: false as const, failed: false as const, name, rarity, quality, effect, instanceId: Number(instance.insertId), success };
});
export const blacksmithQuest = async (qqUserId: string) => { const pool = await getPool(); const characterId = await characterIdFor(pool, qqUserId); const [rows] = await pool.execute<(RowDataPacket & { status: string; secondary_profession_code: string | null })[]>('SELECT q.status,c.secondary_profession_code FROM characters c LEFT JOIN player_side_quests q ON q.character_id=c.id AND q.quest_code=\'blacksmith_apprentice\' WHERE c.id=?', [characterId]); const row = rows[0]; const [items] = await pool.execute<(RowDataPacket & { code: string; quantity: number })[]>('SELECT i.code,pi.quantity FROM player_inventory pi JOIN item_definitions i ON i.id=pi.item_id WHERE pi.character_id=? AND i.code IN (\'living_wood\',\'beast_core\')', [characterId]); const owned = new Map(items.map(item => [item.code, Number(item.quantity)])); const completed = row?.status === 'accepted' && (owned.get('living_wood') ?? 0) >= 1 && (owned.get('beast_core') ?? 0) >= 1; if (completed) await pool.execute('UPDATE player_side_quests SET status=\'completed\',completed_at=NOW() WHERE character_id=? AND quest_code=\'blacksmith_apprentice\'', [characterId]); return { status: completed ? 'completed' : row?.secondary_profession_code === 'blacksmith' ? 'claimed' : row?.status ?? 'none', wood: owned.get('living_wood') ?? 0, core: owned.get('beast_core') ?? 0 }; };
export const acceptBlacksmithQuest = async (qqUserId: string) => withTransaction(async connection => { const characterId = await characterIdFor(connection, qqUserId, true); const [professionRows] = await connection.execute<(RowDataPacket & { secondary_profession_code: string | null })[]>('SELECT secondary_profession_code FROM characters WHERE id=? FOR UPDATE', [characterId]); if (professionRows[0]?.secondary_profession_code && professionRows[0].secondary_profession_code !== 'blacksmith') throw new Error('你已经拥有其他副职业，无法再选择锻造师。'); await connection.execute('INSERT INTO player_side_quests (character_id,quest_code) VALUES (?,\'blacksmith_apprentice\') ON DUPLICATE KEY UPDATE status=IF(status=\'claimed\',status,\'accepted\')', [characterId]); return true; });
export const claimBlacksmithQuest = async (qqUserId: string) => withTransaction(async connection => { const characterId = await characterIdFor(connection, qqUserId, true); const status = await blacksmithQuest(qqUserId); if (status.status !== 'completed') throw new Error('任务尚未完成。'); const [wood] = await connection.execute<(RowDataPacket & { item_id: number })[]>('SELECT pi.item_id FROM player_inventory pi JOIN item_definitions i ON i.id=pi.item_id WHERE pi.character_id=? AND i.code=\'living_wood\' FOR UPDATE', [characterId]); const [core] = await connection.execute<(RowDataPacket & { item_id: number })[]>('SELECT pi.item_id FROM player_inventory pi JOIN item_definitions i ON i.id=pi.item_id WHERE pi.character_id=? AND i.code=\'beast_core\' FOR UPDATE', [characterId]); if (!wood[0] || !core[0]) throw new Error('任务材料已不在背包中。'); await connection.execute('UPDATE player_inventory SET quantity=quantity-1 WHERE character_id=? AND item_id IN (?,?)', [characterId, wood[0].item_id, core[0].item_id]); await connection.execute('DELETE FROM player_inventory WHERE character_id=? AND quantity<=0', [characterId]); await connection.execute('UPDATE player_side_quests SET status=\'claimed\',claimed_at=NOW() WHERE character_id=? AND quest_code=\'blacksmith_apprentice\'', [characterId]); await connection.execute('UPDATE characters SET secondary_profession_code=\'blacksmith\' WHERE id=?', [characterId]); return { name: '锻造师' }; });
