import {readFileSync,writeFileSync} from 'node:fs';
const base=JSON.parse(readFileSync('.data/achievement-design-20260909/final-audit-status.json','utf8')).rows;
type Review={status:string;reason:string;tests:string};
const reviews:Record<string,Review>={};
const put=(ids:string,status:string,reason:string,tests='')=>{for(const id of ids.split(/\s+/).filter(Boolean))reviews['ACH_'+id]={status,reason,tests};};
const business='通过：实际业务与落库',settlement='通过：判定与账本',gap='未通过：覆盖或验收缺口',missing='未通过：缺少事件或溯源',unavailable='无法按原条件验收';
put('H15 H19 H20',business,'真实个人炼金入口完成预览、付料、失败与重炼成功，成就完成记录实际写入隔离MySQL；取消、错人、旧按钮、并发确认、异常回滚均回归。H20另验相同配方、不同配方和失败事务回滚。','alchemy-v2.integration.test.ts；achievement.integration.test.ts');
put('J04 J15',business,'实际装配生成唯一机巧实例并产生长期记忆；真实MySQL中明确断言对应成就已达成，材料支付、重复请求、业务异常回滚和实例交易回归通过。','automaton.integration.test.ts');
put(Array.from({length:25},(_,i)=>'P'+String(i+1).padStart(2,'0')).join(' '),settlement,'正式PVP结算观察器逐项校验，含有效对手、等级、胜负、回合、残血、地域与零贡献等边界；真实账本另验同对手同日去重、回滚、奖励、名次与重修。未在正式QQ客户端逐项复现。','achievement-pvp-audit.test.ts；achievement.integration.test.ts；achievement-catalogue-audit.integration.test.ts');
put('EGG01 EGG02',settlement,'真实MySQL调用正式战败/胜利观察器，验证同一生涯、同一敌人生命实例、连续次数、换敌/逃离中断、归零与受伤、回滚和重试。完整战斗过程以结算快照驱动。','achievement.integration.test.ts');
put('EGG03 EGG04 EGG05 EGG06',settlement,'正式PVE胜利结算校验1HP、六种非无元素、全员有效贡献且残血、30次敌方命中等边界；共同首发成员、奖励与公告落库通过。输入为真实结算结构的测试快照。','achievement.integration.test.ts');
put('A12 A13 A14 A18 A19 A20',settlement,'等级判定在门槛前与门槛时逐档通过；本轮补接进化升级及炼金、锻造、解构、博识、机巧、天赋副职业熟练升级入口。账本验证本世隔离和重修保留；未逐副职业从零练到11级。','achievement-observers.test.ts；achievement.integration.test.ts；achievement-catalogue-audit.integration.test.ts');
put('A17',settlement,'执行正式二转试炼完成函数：阶段未满足不发奖，合法阶段完成后记录；普通二转与四店正式就职均已接入。业务函数测试的SQL依赖使用桩，账本另用真实MySQL验收。','achievement-business-paths.test.ts；achievement-catalogue-audit.integration.test.ts');
put('A23 B24',settlement,'正式战败历史观察器在真实MySQL中记录后续合格胜利，明确断言战败再胜与同一生命实例重挑战成就；重试、逃离与换敌边界一并检查。','achievement.integration.test.ts');
put('B25',settlement,'新生涯建立fromBirth凭据，首次首领胜利且无PVE战败才达成；重修后初始化凭据不会被旧生涯回执吞掉。旧角色没有完整历史时不推定其从未战败，也不自动补发。','achievement.integration.test.ts');
put('B03 B04 B05 B07 B09 B10 B11',settlement,'正式PVE胜利结算按80%等级线、有效贡献、敌人模板/生命实例产生计数；账本逐项验证10/100/1000场及去重门槛、回滚和重试。高计数以测试事件推进，没有在客户端连续打满对应场数。','achievement.integration.test.ts；achievement-catalogue-audit.integration.test.ts');
put('G08 G09 G10 G11',settlement,'正式胜利函数实测全员存活、其他玩家有效治疗/护盾3次、敌方独立行动3次、带低至少3级队友；反例包含队友死亡、仅2次、同次多段命中和高等级导师被80%门槛误挡。真实账本另外验证共同首发。','achievement.integration.test.ts；achievement-existing-mechanics.test.ts');
put('G15 G19 J07 J08 J11 J18 I15',settlement,'真实MySQL测试跨事件状态、同对象隔离、门槛前、回滚与重试；实际次数以maximum写入，修复“达到内部门槛却只上报1次”的问题。J18须读书后实际学成；I15第100场走正式战斗函数并查询本人武器实例。J11完整机巧战斗过程仍由结算快照驱动。','achievement.integration.test.ts；alchemy-v2.integration.test.ts；automaton.integration.test.ts');
put('F20 F21 F22',settlement,'执行正式巡查结算函数，核对目的地、实例、prepare/handoff/deliver流程；中止、未到终点、旧实例、仅准备均不触发。SQL依赖使用桩；名次奖励等账本另由隔离MySQL覆盖。','achievement-business-paths.test.ts；achievement-catalogue-audit.integration.test.ts');
put('E22 K19',settlement,'正式餐厅函数验证铜币、原料及效果入库后记录；背包食物在真实MySQL验证消耗和实际效果，已有效果不再消耗。不同料理数量门槛、去重和回滚由账本测试覆盖。','achievement-business-paths.test.ts；alchemy-v2.integration.test.ts；achievement-catalogue-audit.integration.test.ts');
put('L18 L19',settlement,'正式NPC切磋函数只在胜利分支记录，并按NPC代码去重；战败、逃离、超时不发奖。SQL依赖使用桩，三对手门槛和重复事件由真实账本覆盖。','achievement-business-paths.test.ts；achievement-catalogue-audit.integration.test.ts');
put('A09',missing,'专精加点与配置存在，但尚未把“实际成功使用过的专精方向”写入本世成就状态。只检查当前配置或消费SP会误算，不能代替实际使用。');
put('B22 B23',missing,'现有首领有部位机制，但成就入口接收的目标已排除部位，未保存本人命中过哪些有效部位、指定部位破坏与本体死亡先后顺序。不能用队伍击败首领代替本人部位贡献。');
put('C09 C20',missing,'已有首领预告各自使用独立状态字段，未统一标注哪些属于高威力预告、何种结果算成功应对。直接统计普通吟唱或日志文字会改变原条件，需要先完成机制到成就的明确映射。');
put('C11',missing,'规则DOT、旧状态DOT和天赋持续伤害的来源记录不统一；缺少统一的“最后实际HP损失由本人DOT造成”结算证据。不能把最后一击或普通击杀直接算作DOT收尾。');
put('C17',missing,'当前证据累计部分敌方直击，但未覆盖所有HP损失来源以及敌方至少成功行动一次的完整记录；仅以开战/结算HP相等会把受伤后治疗误算为无伤。');
put('C19',missing,'战斗存在攻击、防御、支援，但三类实际成功动作尚未统一记录；当前技能类别、治疗量和点击按钮都不能完整证明三种有效动作。');
put('C23',missing,'职业资源生成和支付存在，尚未把两次成功技能执行及相同资源类型串成可核对的有序记录，不能以最终资源余额推定。');
put('C25',missing,'已记录部分对其他玩家的治疗/护盾次数，但本人有效防御、自用治疗/护盾与旧技能路径尚未统一计数；直接复用G09会遗漏原定义允许的贡献。');
put('E14',unavailable,'当前物品目录未提供可统一查询的植物材料标签，无法证明确有5种满足原标签条件的物品；不能擅自把名称带草/木的材料都算植物。');
put('E18',unavailable,'九系粉尘分类判定已测，但wind_element_dust的现有获取来源标为待开放，无法用正常玩家路径集齐九种。不会用管理员发放冒充自然可达。','achievement-observers.test.ts');
put('H04',unavailable,'当前普通采集分类只有living_wood映射为植被，没有5种植物采集来源，原“五种不同植物材料”不可达。');
put('E25',missing,'装备、战斗使用和维修均存在，但没有串联同一实例在本人本次持有期间完成三阶段的记录；跨交易持有期间不能简单混算。');
put('F25',unavailable,'当前怪物交涉赠礼不能等同于NPC赠礼；未找到对5名NPC分别校验其礼物喜好并接受的正式入口。NPC好感增加不能替代送对礼物。');
put('G23',missing,'只有预留的同实例计数工具类型，尚无同伴战斗结算调用；需把同伴实例与本人有效胜利关联，不能用模板或普通队友次数替代。');
put('H24 H25 I23 J23',missing,'加工、制作、解构和药品使用各自存在，但普通材料/药剂以同定义数量堆叠，尚无可核对的来源批次消耗链。仅凭曾制作或曾拆解过同类物品会把买来物品误算为自产。');
put('I21 I24 I25',missing,'需串联本人制造的装备实例、制作投入、装备/实际命中或交易接收身份。当前这些成就没有对应完整事件链；本次不以物品名称或持有者推定制作者。');
put('J13',unavailable,'当前automaton-combat.ts明确停用旧策略、手动指令与挡刀开关，机巧不再按玩家旧策略决策。原“修改策略后执行”不适配现玩法，需用户确认改写条件。');
put('J17 J24',missing,'本轮已记录技能书来源与实际学习，但尚未记录所学技能的有效使用；J24还缺少“三种场景”的正式分类，不能把重复施放或三场战斗当作三种场景。');
put('J25',unavailable,'未找到普通玩家制作可供另一身份学习的技能载体及其制作者来源链；当前商店技能书学习不能满足“本人制作”。');
put('K16',unavailable,'家园现有入口为自己的家园，未找到其他玩家授权拜访与有效访问结算；不能用移动到别人家附近替代。');
put('K24',missing,'任务、服务和返家分开结算，未记录同一外出行程ID及其完成顺序；把账号历史三类记录拼在一起不满足原条件。');
put('K25',missing,'正式任务、制作/采集有结算入口，但有效休息的开始、实际恢复与结束未形成统一活动凭据，尚不能可靠判定同一自然日三类活动。');
put('L05 L06 L07 L08 L09 L10 L11 L12',unavailable,'目录所指旧版命名地点/正式主线交接节点与当前灯火/开局内容不一一对应，未找到原要求的正式终结节点。不能擅自改挂到相似地点或另一段剧情。');
put('H11','暂缓：用户指定','种植成就按用户要求暂缓，不新增种植配方。当前只有一种收获观察，原三种种植配方门槛不可达。');
put('L21 L22 L23 L24 L25','未开放','仙路五艺支线未开放，服务层明确拦截；本轮不实装？？？路线，也不借普通副职业代替仙路入门。');
// 有正式入口但未达到完整验收条件：明确写出缺哪一层，不能把没有测试写成不存在玩法。
put('A15',gap,'已补正式晋境写库后的事件，但尚未从该路线完整任务链复现资格、支付、晋境提交与失败重试；当前只通过该编号账本。');
put('A24 A25',gap,'自然日去重已由账本验证，战斗/采集/炼金/部分任务已有调用；所有正式任务和制作入口的活动覆盖尚未完整核验，可能漏计仅做某一类活动的日期。');
put('C05 C07 C08 C10 C15',gap,'现规则引擎的低血治疗、净化、打断、破盾/友伤排除已有测试，其中净化、打断和破盾新增真实规则动作测试通过；旧技能/天赋直接修改状态或HP的路径尚未全部统一到观察器，不能宣称所有合法技能都覆盖。','achievement-existing-mechanics.test.ts；achievement.integration.test.ts');
put('C14',gap,'胜利结算有等级差判定，账本通过；教学、城市追击、管理测试、特殊试炼等全部路由的排除尚未逐入口做业务实测。');
put('D20',gap,'现移动入口只对白名单区域记到访；地图切换、任务迁移及所有正式区域是否均覆盖尚未验证，不能把十个白名单名字当作全世界到访。');
put('D23 D24 D25 G12 G25',gap,'动态场景发现、协助和共同见证已补结算事件及合作标记；仍需真实场景验证中止/过期、三角色关系、供料支付、多人并发与结算回滚，尚未以完整场景路径通过。');
put('E03 E04 E07 E08 E11 E12 E13 E15 E16 E17 E19 E21 E23',gap,'物品分类观察器已测，史诗装备新增实际实例校验；战利品、采集、炼金、锻造、解构及部分商店/市场已接入。但正式剧情奖励、所有商店、神器获取和书籍来源尚未全部统一到观察器，仍可能漏计合法取得。','achievement-observers.test.ts');
put('E20 I08',gap,'装备定义与五件同甲类套装判定已测，重复槽不能凑件；还未以真实数据库从换装入口完整复现、验证战斗锁与旧按钮，并核对成就属性在PVP进入/退出后的面板还原。','achievement-observers.test.ts');
put('E24',gap,'成功炼金与普通/史诗锻造已统一配方签名；机巧、加工及其他算作“亲手制作”的入口未全部接入，不能把两类制作当作所有配方。','achievement-existing-mechanics.test.ts');
put('F03 F04 F06 EGG10',gap,'交涉成功出口已接；F06新增同生命实例拒礼记录，库存未损失后成功才触发。尚未以真实交涉事务跑完拒礼、库存返还、复谈成功及并发结算；不能仅凭出口引用标为全链通过。');
put('F07 F08 F09',gap,'已核对正式第二级为200，199/200与有效互动开关测试通过；已补多处实际好感更新，但委托、动态域民等全部好感/互动来源未逐入口业务验收。','achievement-observers.test.ts');
put('F24',gap,'天赋材料委托交付入口按job.id去重；站点委托等其他正式NPC委托尚未统一纳入，20次门槛不能代表所有合法委托覆盖。');
put('G03 G04 G05 G07',gap,'组队贡献、首领合作结算及同身份伙伴计数已接入，G07共同首发已有真实MySQL证据；纯护盾贡献者、全部组队战斗入口及同伴混编的贡献口径仍须补齐验证。','achievement.integration.test.ts');
put('G17',gap,'双方誓约确认已有事件；尚未完整实测双边确认、关系变更并发、回滚及支付失败后的无奖励，账本已通过。');
put('G20 G22',gap,'接受合法邀请已有招募事件和模板去重；尚未实测完整邀请条件、拒绝、过期、对象校验与3种模板来源，账本已通过。');
put('H02 H03 H05 H06 EGG12',gap,'实际采集完成且取得产物才记录，资源实例去重；H05本轮收紧为矿石/锻材。账本门槛和重复资源去重通过，但完整采集计时、争抢、取消与落库的业务路径未逐项实测。');
put('H07 H08',gap,'险采成功与封存最终兑现已有事件；仍需对应天赋真实入口验证风险开启、支付、取消、过期、重复兑现及库存原子性，不能用普通采集替代。');
put('H13 H14 H18 H22 EGG07 EGG08 EGG09',gap,'真实炼金业务已回归；H18分类规则已测，相关计数与去重账本通过。尚未逐项以业务入口跑到20/100成功批、10炸炉、50大成功及10/30不同配方，并证明代工/批次/炸炉排除，保留未完整验收。','alchemy-v2.integration.test.ts；achievement-existing-mechanics.test.ts');
put('I02 I03 I16 I17 I18 I19 I20',gap,'普通/史诗锻造、实际精炼成功和熔铸已补入口；锻材正数量、两种不同锻材、陨铁及区域材料判定测试通过。尚未完成真实锻造数据库中失败扣料、代工排除、精炼/熔铸并发和成就原子落库验收。','achievement-existing-mechanics.test.ts');
put('J21 J22 EGG11',gap,'解构实际有产物才计；J22新增材料类型限制，J21按元素粒子定义去重，并排除构造物回拆/代工。尚未以真实解构入口跑完不同输入、零产物、支付与失败回滚。');
put('K05 K08 K09',gap,'撮合/实例市场现按实际成交金额及卖家净收入记录，三店卖货、公会买卖、书店与悬赏已补部分入口；尚需全部商店/任务来源、退款撤销及并发成交完整覆盖验证，不能把订金或赠送算收入。','achievement.integration.test.ts；alchemy-v2.integration.test.ts；secondary-shop.integration.test.ts');
put('K10 K14',gap,'购房及不同家具计数已有事件；仍缺真实家园购买/摆放入口的资金不足、重复提交、绑定家具与回滚验收，不能用账本人工事件替代。');
put('L01 L02 L03 L04',gap,'灯火阶段切换在节点成功写入后记录；仍需分别从四段最终节点验证只有合法终结切换触发、回看/旧按键不重发及事务回滚。历史剧情测试不能自动等于本轮新增成就集成通过。');
put('L13 L14',gap,'已补下层关卡及整座迷宫完成事件，完整通关传入真实参与者；仍需验证层主排除、最后一层完成、重复关卡结算、队伍贡献与迷宫状态原子落库。');
put('L15 L16',gap,'正式PVE悬赏交付按委托ID记录；真实任务接取到交付的业务路径、20次不同委托、过期/重复领取与追杀排除尚未逐项实测。');
put('L17',gap,'四店隐藏二转正式就职完成后已补事件；仍需完整任务资格、试炼及最终就职一起验证，而不是只调用最后记账函数。');
put('L20',gap,'I10实际降服结算已有事件；尚未实测生命比例、单人限制、首领/特殊敌人排除、旧战斗按钮和降服后奖励落库。');
put('E05 E06',gap,'图鉴发现已有怪物模板去重入口；仍未完整核对探查、战斗首次见敌与剧情敌人等所有发现来源，以及测试/教学模板排除，账本门槛不能替代发现流程。');
const rows=base.map((d:any)=>{const r=reviews[d.id];if(!r)throw Error('缺少逐项结论 '+d.id);return {...d,...r};});
const counts=Object.fromEntries([...new Set(rows.map((r:any)=>r.status))].map(s=>[s,rows.filter((r:any)=>r.status===s).length]));
let md='# 成就最终信息与逐项验收记录 V2\n\n核查日期：2026-09-10。本文件替代V1的验收状态，保留当前202个有效静态编号，逐项写明最终条件、奖励、证据与未通过原因；不修改玩家端隐藏条件规则。\n\n## 结论与验收口径\n\n**没有把202条全部标成已完成。** “实际业务与落库通过”表示已经由正式玩法函数运行到隔离数据库完成记录；“判定与账本通过”表示正式判定函数和持久化已测，但部分业务SQL依赖为测试桩、长计数使用测试事件，没有冒充生产玩家完整游玩。其余条目明确区分实现/覆盖缺口、原内容不可达、用户暂缓和未开放。\n\n| 状态 | 项数 |\n| --- | ---: |\n';
for(const [s,n]of Object.entries(counts))md+=`| ${s} | ${n} |\n`;
md+='\n当前不能给出“全部玩法端到端已通过”的结论。缺少触发/溯源属于尚未补完的实现，不等于玩法不存在；缺少完整业务实测属于尚未验收，不等于永远无法验收。需要改变原条件的项目维持原定义，未擅自简化。\n\n## 本轮实际修复\n\n- 补副职业各成长出口、进化升级、普通/隐藏二转、NPC切磋和迷宫完成观察。\n- 补精炼、熔铸、普通/史诗锻造材料条件、炼金失败后同配方重炼、解构粒子/材料、餐厅和背包食物。\n- 补成交实付/净收入、NPC有效互动、拒礼后复谈、同身份伙伴、好友跨日、誓约回忆与同机巧育成记录。\n- 补读书来源与真正学会、同一武器/机巧实例胜利计数，修复跨对象拼次数、内部达到门槛却只上报1次、重修初始化被旧回执吞掉等问题。\n- 补DOT净化、打断、破盾和独立敌方行动证据，修正导师因自身等级被普通战斗收益门槛误挡。\n- 补护送/救援正式终点交接，修正“暂不参与”仍计巡查互动；史诗装备要求实际实例，且战利品先完成发放再观察，零数量/零实际铜币不计取得；采矿成就收紧材料分类。\n\n## 测试证据\n\n- 成就专项：305项通过，零失败、零跳过。包含202条目录独立账本测试，其中197条验证门槛/去重/回滚/重试/首位与第二位/奖励/注销重修保留，5条验证未开放拦截。人工构造成就事件只证明账本。\n- 炼金真实隔离MySQL：22项通过；机巧真实隔离MySQL：21项通过；副职业商店真实隔离MySQL：2项通过。\n- 战斗规则、面板公式与商店相关回归：105项通过。`npx tsc --noEmit`通过。\n- 全部写库测试采用新建隔离数据库并清理；未给真人补发、未改正式名次、未主动发送公告、未重启机器人。\n- 六维奖励读取与重修保留已测；本轮没有完成正式PVP进入/退出后成就六维面板的端到端还原验证，不能将一般面板公式测试等同于此项。\n\n测试文件位于`test/`；详细输出保存在`.data/achievement-design-20260909/`，状态机器记录为`acceptance-v2.json`。\n\n## 玩家最终展示与共用规则\n\n仅显示已解锁成就和已解锁分类，未解锁时只有[全部]；每页最多10条。详情显示名称、凝练简介、永久属性、分类、稀有度、全服名次、完成率与达成时间，不公开下文维护用具体要求。所有完成记录及奖励注销重修后保留。\n\n稀有度从低到高为普通、优秀、精良、稀有、传说、史诗。全服首发有奇珍道具匣×1；支持共同结算的合作成就按同一合作事件共同首发。每项成就单独公告，各群排队投递，不保证同时抵达。道具匣可随机单开或批量开；其中三种奖励道具的战斗使用未在本轮完成，不将可开匣等同于可使用。\n';
for(const category of [...new Set(rows.map((r:any)=>r.category))]){md+=`\n## ${category}\n`;for(const d of rows.filter((r:any)=>r.category===category))md+=`\n### ${d.id} ${d.name}\n\n${d.description}\n\n- 最终要求：${d.condition}\n- 最终奖励：${d.rarity}；永久${d.attribute}。\n- 未完成进度：${d.scope==='世'?'限本世':d.scope==='场'?'按对应单场/事件判定':'账号累计'}；已完成记录与奖励永久保留。\n- 验收结论：**${d.status}**。\n- 证据或原因：${d.reason}\n- 测试：${d.tests||'该编号通用真实MySQL账本已测；不能替代缺失的业务证据。'}\n- 源码定位：${d.evidence.length?d.evidence.slice(0,4).map((e:any)=>`[${e.p}:${e.line}](../${e.p})`).join('；'):'尚无正式成就触发调用'}。\n`;}
md+='\n## Boss首杀\n\n统一Boss结算、不同难度奖励、国王团队归一与合作首发账本已回归。V1所列两项正式完成记录是2026-09-09只读快照，本轮未重新查询，不把该快照当作当前全服总数。204项预备文案仍不代表204个可进入难度；每个实际Boss/难度的完整战斗验收未全部执行。大学者·噶与不存在的迷宫镇守者不计独立Boss，国王与同队护卫只算一组。\n\n[Boss首杀名称与简介V3](Boss首杀成就名称与简介V3.md)。？？？十条隐藏路线和仙路五艺维持未开放；种植维持暂缓。\n';
writeFileSync('docs/成就最终信息与逐项验收记录V2.md',md);writeFileSync('.data/achievement-design-20260909/acceptance-v2.json',JSON.stringify({date:'2026-09-10',counts,rows},null,2));console.log(counts);
