import {readFileSync,writeFileSync} from 'node:fs';
import {transformSync} from 'esbuild';
import {calculateDerivedStats,virtualEquipmentStats} from '../../src/game/constants';
const snapshot=JSON.parse(readFileSync('.data/balance-review-20260908/snapshot.json','utf8'));
const source=readFileSync('src/game/adventure.service.ts','utf8');
const start=source.indexOf('const monsterCombatStats = '),end=source.indexOf('\n};',start)+3;
const fn=source.slice(start,end);
const traitStart=source.indexOf('const wolfKingTraits:'),traitEnd=source.indexOf('\n];',traitStart)+3;
const js=transformSync(source.slice(traitStart,traitEnd)+'\n'+fn+'\nexports.run=monsterCombatStats;exports.traits=wolfKingTraits;',{loader:'ts',format:'cjs'}).code;
const attrs=['constitution','spirit','strength','intelligence','agility','perception'];
const json=(v:any)=>typeof v==='string'?JSON.parse(v):v??{};
const list=(v:any)=>Array.isArray(json(v))?json(v):[];
let definitions:any[]=[];
const helpers:any={calculateDerivedStats,virtualEquipmentStats,traitList:list,jsonObject:json,bossComponentTrait:(m:any)=>list(m.traits_json).find((t:any)=>t.code==='boss_component'),advancedMentorBuildFor:(m:any)=>list(m.traits_json).find((t:any)=>t.code==='advanced_mentor_build')?.build??null,monsterAttributes:(m:any)=>{const mul=list(m.traits_json).reduce((a:number,t:any)=>a*Number(t.attributeMultiplier??1),1);return Object.fromEntries(attrs.map(k=>[k,Math.floor((Number(m[k])+Math.max(0,m.level-1)*Number(m[k+'_growth']))*mul)]));},bossTraitDefinitionFor:(code:string)=>definitions.find(d=>d.code===code),isKingbeastCore:(m:any)=>list(m.traits_json).some((t:any)=>t.code==='kingbeast_encounter'),percentBonus:(traits:any[],k:string)=>traits.reduce((a,t)=>a+Number(t[k]??0),0)};
const instantiate=(h:any)=>{const exports:any={};new Function(...Object.keys(h),'exports',js)(...Object.values(h),exports);definitions=exports.traits;return exports.run;};
const old=instantiate(helpers);
const growth=(l:number)=>Math.min(9,Math.max(0,l-1))+2*Math.min(10,Math.max(0,l-10))+3*Math.min(10,Math.max(0,l-20));
const newVirtual=(l:number,tier:any,pa:number,ma:number)=>{const v=virtualEquipmentStats(l,tier,pa,ma);if(l>30)return v;const b=8+4.3*(100+10*growth(l))/6;const mult=({normal:.6,large:1,elite:1.15,boss:1.3} as any)[tier]??.6;v[pa>=ma?'physicalAttack':'magicAttack']=Math.floor(b*.5*mult);v.physicalDefense=Math.floor(b*.5*mult);v.magicDefense=Math.floor(b*.5*mult);return v;};
const after=instantiate({...helpers,virtualEquipmentStats:newVirtual});
const spawns=snapshot.spawns.map((r:any)=>({id:r.id,code:r.code,name:r.name,level:r.level,tier:r.monster_class,traits:list(r.traits_json).map((t:any)=>t.code),old:old(r),newMainOnly:after(r)}));
const templates=snapshot.monsters.map((r:any)=>({code:r.code,level:r.level,rawTemplateStats:old({...r,traits_json:[]})}));
writeFileSync('.data/balance-review-20260908/monster-calculations.json',JSON.stringify({method:'current monsterCombatStats function extracted from source, same pure dependencies; template rows are unrandomized theoretical values; newMainOnly changes virtual primary budgets, no body growth change',templates,spawns},null,2));
console.log(JSON.stringify({templateCount:templates.length,spawnCount:spawns.length,bosses:spawns.filter((r:any)=>r.tier==='boss').map((r:any)=>({id:r.id,name:r.name,lv:r.level,traits:r.traits,hp:r.old.hpMax,pa:r.old.physicalAttack,pd:r.old.physicalDefense,newPa:r.newMainOnly.physicalAttack,newPd:r.newMainOnly.physicalDefense}))},null,2));
