qq-bot:
  app_id: '102057736'
  secret: 'qWCtaI0jSCwhSE0naOC1qgXOG81uoidY'
  sandbox: false
  markdownToText: true
  hideUnsupported: 1
mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  password: root
  database: fantasy
redis:
  host: 127.0.0.1
  port: 16379
  user: root
  db: 6

login: 'qq-bot'
