qq-bot:
  app_id: "102057736"
  secret: "qWCtaI0jSCwhSE0naOC1qgXOG81uoidY"
  hideUnsupported: 1
  markdownToText: false
  sandbox: false
mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  password: root
  database: fantasy_final
redis:
  host: 127.0.0.1
  port: 16379
  user: root
  db: 6

login: "qq-bot"
port: 17117
