import { calculateDerivedStats, forgedEquipmentBase, forgedAffixCap, forgeRarityMultiplier, equipmentQualityMultiplier } from './src/game/constants';
import { calculatePanelStats } from './src/game/panel-stat-formula';
import { armorPanelPercent, armorSlots } from './src/game/armor-class';
import { armorSetFromRows } from './src/game/armor-set';
import { playerGrowthShares } from './src/game/growth-rules';

const trained = { constitution: 85.1, spirit: 51.5, strength: 124.7, intelligence: 43.6, agility: 59.4, perception: 77.2 };
const base = calculateDerivedStats(trained);
const primaryMultiplier = (rarity: string) => (forgeRarityMultiplier[rarity] ?? 1) * equipmentQualityMultiplier(100);
const weapon = forgedEquipmentBase(30, '武器') * primaryMultiplier('传说');
const armor = armorSlots.reduce((sum, slot) => sum + forgedEquipmentBase(30, '防具', slot), 0) * primaryMultiplier('传说');
const result = { ...Object.fromEntries(Object.keys(base).map(key => [key, 0])) };
result.physicalAttack += Math.floor(weapon * 2);
result.physicalDefense += Math.floor(armor);
result.magicDefense += Math.floor(armor);
const cap = (cat: '武器' | '防具', key: string) => forgedAffixCap(cat, key, 30, '传说') * equipmentQualityMultiplier(100) * .6;
result.accuracy += Math.floor(cap('武器', 'accuracy'));
result.critRateBp += Math.floor(cap('武器', 'critRateBp'));
result.critDamageBp += Math.floor(cap('武器', 'critDamageBp'));
result.hpMax += Math.floor(cap('防具', 'hpMax') * 2);
result.evasion += Math.floor(cap('防具', 'evasion'));
result.critResistBp += Math.floor(cap('防具', 'critResistBp'));
result.tenacity += Math.floor(cap('防具', 'tenacity'));
result.speed += Math.floor(cap('防具', 'speed'));
const masteryPercent = { hpPct: 0, mpPct: 0, physicalAttackPct: 0, magicAttackPct: 0, physicalDefensePct: 0, magicDefensePct: 0, accuracyPct: 0, evasionPct: 0, critRatePct: 80, critDamagePct: 0, critResistPct: 0, critDamageReductionPct: 0, tenacityPct: 0, tenacityPiercePct: 0, speedPct: 0 };
const rows = armorSlots.map(slot => ({ slot, weapon_type: '重甲', quality: 100 }));
const evolution = { hpPct: 3, physicalAttackPct: 5, accuracyPct: 4, speedPct: 3 };
const passive = { physicalAttackPct: 12, accuracyPct: 10, speedPct: 8 };
const stats = calculatePanelStats(base, result, evolution, [masteryPercent, armorPanelPercent(rows), armorSetFromRows(rows)?.panelPercent ?? {}]);
const final = calculatePanelStats(stats, {}, passive);
console.log('legendary war_lord', final);

const weaponE = forgedEquipmentBase(30, '武器') * primaryMultiplier('史诗');
const armorE = armorSlots.reduce((sum, slot) => sum + forgedEquipmentBase(30, '防具', slot), 0) * primaryMultiplier('史诗');
const resultE = { ...Object.fromEntries(Object.keys(base).map(key => [key, 0])) };
resultE.physicalAttack += Math.floor(weaponE * 2);
resultE.physicalDefense += Math.floor(armorE);
resultE.magicDefense += Math.floor(armorE);
const capE = (cat: '武器' | '防具', key: string) => forgedAffixCap(cat, key, 30, '史诗') * equipmentQualityMultiplier(100) * .6;
resultE.accuracy += Math.floor(capE('武器', 'accuracy'));
resultE.critRateBp += Math.floor(capE('武器', 'critRateBp'));
resultE.critDamageBp += Math.floor(capE('武器', 'critDamageBp'));
resultE.hpMax += Math.floor(capE('防具', 'hpMax') * 2);
resultE.evasion += Math.floor(capE('防具', 'evasion'));
resultE.critResistBp += Math.floor(capE('防具', 'critResistBp'));
resultE.tenacity += Math.floor(capE('防具', 'tenacity'));
resultE.speed += Math.floor(capE('防具', 'speed'));
const statsE = calculatePanelStats(base, resultE, evolution, [masteryPercent, armorPanelPercent(rows), armorSetFromRows(rows)?.panelPercent ?? {}]);
const finalE = calculatePanelStats(statsE, {}, passive);
console.log('epic war_lord', finalE);
