import {readFileSync,writeFileSync} from 'node:fs';
import {monsterCombatStats,monsterAttributes} from '../../src/game/adventure.service';
import {recalculateNpcSparProfileStats,buildNpcSparProfile} from '../../src/game/npc-sparring.config';
import {monsterGrowthCoefficient,isResidentMonsterCode} from '../../src/game/monster-growth';
import {monsterGrowthAnchors} from '../../src/config/monster-growth-anchors';
import {withVirtualNpcEquipment} from '../../src/game/character.service';
import {calculateDerivedStats,virtualEquipmentStats} from '../../src/game/constants';
import {attributes} from '../../src/game/types';
import {playerGrowthShares} from '../../src/game/growth-rules';
import {monsterCombatStats as oldStats,monsterAttributes as oldSix} from './legacy-adventure';
const s=JSON.parse(readFileSync('.data/enemy-balance-20260908/before.json','utf8'));
const templateById=new Map(s.templates.map((t:any)=>[Number(t.id),t]));
for(const r of s.spawns){const t:any=templateById.get(Number(r.template_id));for(const k of attributes)r[k]=r[k]??t[k];r.calculated=oldStats(r);r.finalSix=oldSix(r);}
writeFileSync('.data/enemy-balance-20260908/verified-before.json',JSON.stringify(s));
const parse=(v:any)=>typeof v==='string'?JSON.parse(v):v;
const compare=(r:any)=>({id:r.id,code:r.code,name:r.name,level:r.level,anchor:monsterGrowthAnchors[r.code]??10,coefficient:monsterGrowthCoefficient(r.code,r.level),before:r.calculated,after:monsterCombatStats(r),sixBefore:r.finalSix,sixAfter:monsterAttributes(r)});
const templates=s.templates.map(compare),alive=s.spawns.filter((r:any)=>!r.defeated_at).map(compare);
const profiles=s.profiles.map((r:any)=>{const old=parse(r.profile_json);return {code:r.npc_code,before:old,after:{...old,...recalculateNpcSparProfileStats(old)}}});
const scenarios=s.npcAudit.map((r:any)=>({...r,after:buildNpcSparProfile(r.input,r.playerLevel,r.worldStage)}));
const companions=s.npcCharacters.map((r:any)=>{const six=Object.fromEntries(attributes.map(k=>[k,Number(r[k])+Number(r[k+'_growth'])*playerGrowthShares(r.level)]));return {id:r.id,code:r.npc_code,name:r.name,level:r.level,before:r,after:withVirtualNpcEquipment(calculateDerivedStats(six as any),r.level,r.npc_code)}});
const ratios=(rows:any[])=>Object.fromEntries(['hpMax','physicalAttack','magicAttack','physicalDefense','magicDefense','accuracy','evasion','speed'].map(k=>{const a=rows.map(r=>r.after[k]/Math.max(1,r.before[k]));return [k,{min:Math.min(...a),max:Math.max(...a),mean:a.reduce((a,b)=>a+b,0)/a.length}]}));
const summary={templates:templates.length,alive:alive.length,profiles:profiles.length,scenarios:scenarios.length,companions:companions.length,nullBirth:s.spawns.filter((r:any)=>attributes.some(k=>r[k]===null)).length,ordinaryRatios:ratios(alive.filter((r:any)=>!isResidentMonsterCode(r.code)&&!['evolution_trial_beast'].includes(r.code))),largestHpIncreases:alive.filter((r:any)=>r.after.hpMax>r.before.hpMax).sort((a:any,b:any)=>b.after.hpMax/b.before.hpMax-a.after.hpMax/a.before.hpMax).slice(0,8),samples:templates.filter((r:any)=>['forest_slime','slime_water','goblin','necromancer','goblin_king','city_patrol','scholar_ga'].includes(r.code)),npcSamples:profiles.filter((r:any)=>['alchemy_sweetshop','guild_counter','bookshop'].includes(r.code)).map((r:any)=>({code:r.code,level:r.before.level,before:r.before.stats,after:r.after.stats})),companions:companions.map((r:any)=>({code:r.code,level:r.level,hp:[r.before.hp_max,r.after.hpMax],def:[r.before.physical_defense,r.after.physicalDefense]}))};
writeFileSync('.data/enemy-balance-20260908/comparison.json',JSON.stringify({summary,templates,alive,profiles,scenarios,companions},null,2));console.log(JSON.stringify(summary));process.exit(0);
