export declare const monsterCardData: readonly [{
    readonly cardCode: "monster_card_ball_rabbit";
    readonly monsterCode: "ball_rabbit";
    readonly monsterName: "球兔";
    readonly name: "球兔·卡片";
    readonly level: 1;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["shoulder", "waist", "feet"];
    readonly effectText: "闪避 +28.10";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_spike_boar";
    readonly monsterCode: "spike_boar";
    readonly monsterName: "刺猪";
    readonly name: "刺猪·卡片";
    readonly level: 1;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["shoulder", "waist", "feet"];
    readonly effectText: "破韧 +9.56";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_vine_snake";
    readonly monsterCode: "vine_snake";
    readonly monsterName: "藤蛇";
    readonly name: "藤蛇·卡片";
    readonly level: 1;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["shoulder", "waist", "feet"];
    readonly effectText: "命中 +28.10";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_black_bear";
    readonly monsterCode: "black_bear";
    readonly monsterName: "乌熊";
    readonly name: "乌熊·卡片";
    readonly level: 2;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["upper", "lower"];
    readonly effectText: "生命上限 +68.62";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_mist_wolf";
    readonly monsterCode: "mist_wolf";
    readonly monsterName: "幽狼";
    readonly name: "幽狼·卡片";
    readonly level: 2;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["shoulder", "waist", "feet"];
    readonly effectText: "暴击 +29.82";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_roll_rabbit";
    readonly monsterCode: "roll_rabbit";
    readonly monsterName: "滚兔";
    readonly name: "滚兔·卡片";
    readonly level: 3;
    readonly tier: "large";
    readonly allowedSlots: readonly ["shoulder", "waist", "feet"];
    readonly effectText: "闪避 +44.16";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_tusk_boar";
    readonly monsterCode: "tusk_boar";
    readonly monsterName: "獠猪";
    readonly name: "獠猪·卡片";
    readonly level: 4;
    readonly tier: "large";
    readonly allowedSlots: readonly ["weapon", "offhand"];
    readonly effectText: "物理攻击 +8.58";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_vine_python";
    readonly monsterCode: "vine_python";
    readonly monsterName: "藤蚺";
    readonly name: "藤蚺·卡片";
    readonly level: 4;
    readonly tier: "large";
    readonly allowedSlots: readonly ["shoulder", "waist", "feet"];
    readonly effectText: "破韧 +17.07";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_pitch_bear";
    readonly monsterCode: "pitch_bear";
    readonly monsterName: "漆熊";
    readonly name: "漆熊·卡片";
    readonly level: 5;
    readonly tier: "large";
    readonly allowedSlots: readonly ["upper"];
    readonly effectText: "生命上限 +153.84";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_shadow_wolf";
    readonly monsterCode: "shadow_wolf";
    readonly monsterName: "影狼";
    readonly name: "影狼·卡片";
    readonly level: 5;
    readonly tier: "large";
    readonly allowedSlots: readonly ["shoulder", "waist", "feet"];
    readonly effectText: "暴击 +53.25";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_goblin";
    readonly monsterCode: "goblin";
    readonly monsterName: "哥布林";
    readonly name: "哥布林·卡片";
    readonly level: 4;
    readonly tier: "elite";
    readonly allowedSlots: readonly ["shoulder"];
    readonly effectText: "命中修正 +2%";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_tree_ent";
    readonly monsterCode: "tree_ent";
    readonly monsterName: "树精";
    readonly name: "树精·卡片";
    readonly level: 7;
    readonly tier: "elite";
    readonly allowedSlots: readonly ["lower"];
    readonly effectText: "承受伤害降低 2%";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_forest_slime";
    readonly monsterCode: "forest_slime";
    readonly monsterName: "森林史莱姆";
    readonly name: "森林史莱姆·卡片";
    readonly level: 8;
    readonly tier: "boss";
    readonly allowedSlots: readonly ["necklace"];
    readonly effectText: "主动治疗量 +12%；水元素抗性 +12";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_shadow_wolf_king";
    readonly monsterCode: "shadow_wolf_king";
    readonly monsterName: "幽影狼王";
    readonly name: "幽影狼王·卡片";
    readonly level: 12;
    readonly tier: "boss";
    readonly allowedSlots: readonly ["shoulder"];
    readonly effectText: "实际暴击 +6 个百分点；暴伤 +180";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_dungeon_raider";
    readonly monsterCode: "dungeon_raider";
    readonly monsterName: "地宫劫掠者";
    readonly name: "地宫劫掠者·卡片";
    readonly level: 11;
    readonly tier: "elite";
    readonly allowedSlots: readonly ["shoulder"];
    readonly effectText: "命中修正 +3%";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_dungeon_wisp";
    readonly monsterCode: "dungeon_wisp";
    readonly monsterName: "幽邃法灵";
    readonly name: "幽邃法灵·卡片";
    readonly level: 15;
    readonly tier: "elite";
    readonly allowedSlots: readonly ["upper"];
    readonly effectText: "承受魔法伤害降低 3%";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_dungeon_stalker";
    readonly monsterCode: "dungeon_stalker";
    readonly monsterName: "暗影猎手";
    readonly name: "暗影猎手·卡片";
    readonly level: 20;
    readonly tier: "elite";
    readonly allowedSlots: readonly ["feet"];
    readonly effectText: "闪避修正 +3%";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_dungeon_guardian";
    readonly monsterCode: "dungeon_guardian";
    readonly monsterName: "迷宫守卫";
    readonly name: "迷宫守卫·卡片";
    readonly level: 25;
    readonly tier: "elite";
    readonly allowedSlots: readonly ["lower"];
    readonly effectText: "承受物理伤害降低 3%";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_dungeon_warden";
    readonly monsterCode: "dungeon_warden";
    readonly monsterName: "迷宫镇守者";
    readonly name: "迷宫镇守者·卡片";
    readonly level: 30;
    readonly tier: "boss";
    readonly allowedSlots: readonly ["bracelet"];
    readonly effectText: "暴免修正 +12%；暴抗修正 +10%";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_slime_red";
    readonly monsterCode: "slime_red";
    readonly monsterName: "红色史莱姆";
    readonly name: "红色史莱姆·卡片";
    readonly level: 1;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["weapon", "offhand"];
    readonly effectText: "物理攻击 +4.76";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_slime_orange";
    readonly monsterCode: "slime_orange";
    readonly monsterName: "橙色史莱姆";
    readonly name: "橙色史莱姆·卡片";
    readonly level: 2;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["upper", "lower"];
    readonly effectText: "物理防御 +14.83";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_slime_yellow";
    readonly monsterCode: "slime_yellow";
    readonly monsterName: "黄色史莱姆";
    readonly name: "黄色史莱姆·卡片";
    readonly level: 3;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["shoulder", "waist", "feet"];
    readonly effectText: "命中 +31.54";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_slime_green";
    readonly monsterCode: "slime_green";
    readonly monsterName: "绿色史莱姆";
    readonly name: "绿色史莱姆·卡片";
    readonly level: 4;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["upper", "lower"];
    readonly effectText: "生命上限 +77.80";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_slime_cyan";
    readonly monsterCode: "slime_cyan";
    readonly monsterName: "青色史莱姆";
    readonly name: "青色史莱姆·卡片";
    readonly level: 5;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["shoulder", "waist", "feet"];
    readonly effectText: "速度 +31.76";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_slime_blue";
    readonly monsterCode: "slime_blue";
    readonly monsterName: "蓝色史莱姆";
    readonly name: "蓝色史莱姆·卡片";
    readonly level: 6;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["weapon", "offhand"];
    readonly effectText: "魔力上限 +77.36";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_slime_purple";
    readonly monsterCode: "slime_purple";
    readonly monsterName: "紫色史莱姆";
    readonly name: "紫色史莱姆·卡片";
    readonly level: 8;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["weapon", "offhand"];
    readonly effectText: "魔法攻击 +6.48";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_black_slime";
    readonly monsterCode: "black_slime";
    readonly monsterName: "黑暗史莱姆";
    readonly name: "黑暗史莱姆·卡片";
    readonly level: 10;
    readonly tier: "boss";
    readonly allowedSlots: readonly ["weapon"];
    readonly effectText: "无元素普通攻击赋予暗属性；暗元素精通 +16；暗元素伤害提高 8%";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_skeleton";
    readonly monsterCode: "skeleton";
    readonly monsterName: "骷髅";
    readonly name: "骷髅·卡片";
    readonly level: 16;
    readonly tier: "large";
    readonly allowedSlots: readonly ["weapon", "offhand"];
    readonly effectText: "物理攻击 +23.23";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_undead";
    readonly monsterCode: "undead";
    readonly monsterName: "亡灵";
    readonly name: "亡灵·卡片";
    readonly level: 17;
    readonly tier: "large";
    readonly allowedSlots: readonly ["weapon", "offhand"];
    readonly effectText: "魔法攻击 +23.23";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_skeleton_warrior";
    readonly monsterCode: "skeleton_warrior";
    readonly monsterName: "骷髅战士";
    readonly name: "骷髅战士·卡片";
    readonly level: 19;
    readonly tier: "elite";
    readonly allowedSlots: readonly ["shoulder"];
    readonly effectText: "命中修正 +3%";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_death_wight";
    readonly monsterCode: "death_wight";
    readonly monsterName: "死灵";
    readonly name: "死灵·卡片";
    readonly level: 20;
    readonly tier: "elite";
    readonly allowedSlots: readonly ["upper"];
    readonly effectText: "暴免修正 +4%";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_skeleton_general";
    readonly monsterCode: "skeleton_general";
    readonly monsterName: "骷髅将军";
    readonly name: "骷髅将军·卡片";
    readonly level: 22;
    readonly tier: "boss";
    readonly allowedSlots: readonly ["shoulder"];
    readonly effectText: "实际命中 +6 个百分点；破韧 +80";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_death_knight";
    readonly monsterCode: "death_knight";
    readonly monsterName: "死灵骑士";
    readonly name: "死灵骑士·卡片";
    readonly level: 22;
    readonly tier: "boss";
    readonly allowedSlots: readonly ["lower"];
    readonly effectText: "承受伤害降低 8%；暴抗修正 +8%";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_goblin_vanguard";
    readonly monsterCode: "goblin_vanguard";
    readonly monsterName: "哥布林先锋";
    readonly name: "哥布林先锋·卡片";
    readonly level: 20;
    readonly tier: "large";
    readonly allowedSlots: readonly ["weapon", "offhand"];
    readonly effectText: "物理攻击 +30.95";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_goblin_warrior";
    readonly monsterCode: "goblin_warrior";
    readonly monsterName: "哥布林战士";
    readonly name: "哥布林战士·卡片";
    readonly level: 21;
    readonly tier: "large";
    readonly allowedSlots: readonly ["weapon"];
    readonly effectText: "物理攻击 +37.82";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_goblin_archer";
    readonly monsterCode: "goblin_archer";
    readonly monsterName: "哥布林弓箭手";
    readonly name: "哥布林弓箭手·卡片";
    readonly level: 21;
    readonly tier: "large";
    readonly allowedSlots: readonly ["shoulder", "waist", "feet"];
    readonly effectText: "命中 +136.44";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_goblin_bomber";
    readonly monsterCode: "goblin_bomber";
    readonly monsterName: "哥布林自爆兵";
    readonly name: "哥布林自爆兵·卡片";
    readonly level: 22;
    readonly tier: "large";
    readonly allowedSlots: readonly ["shoulder"];
    readonly effectText: "暴伤 +184.71";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_goblin_daredevil";
    readonly monsterCode: "goblin_daredevil";
    readonly monsterName: "哥布林敢死队";
    readonly name: "哥布林敢死队·卡片";
    readonly level: 23;
    readonly tier: "large";
    readonly allowedSlots: readonly ["shoulder", "waist", "feet"];
    readonly effectText: "破韧 +61.70";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_goblin_drummer";
    readonly monsterCode: "goblin_drummer";
    readonly monsterName: "哥布林战鼓手";
    readonly name: "哥布林战鼓手·卡片";
    readonly level: 22;
    readonly tier: "large";
    readonly allowedSlots: readonly ["shoulder", "waist", "feet"];
    readonly effectText: "速度 +104.74";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_goblin_shieldbearer";
    readonly monsterCode: "goblin_shieldbearer";
    readonly monsterName: "哥布林盾卫";
    readonly name: "哥布林盾卫·卡片";
    readonly level: 24;
    readonly tier: "large";
    readonly allowedSlots: readonly ["lower"];
    readonly effectText: "物理防御 +102.85";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_goblin_trapper";
    readonly monsterCode: "goblin_trapper";
    readonly monsterName: "哥布林网罗工兵";
    readonly name: "哥布林网罗工兵·卡片";
    readonly level: 23;
    readonly tier: "large";
    readonly allowedSlots: readonly ["shoulder", "waist", "feet"];
    readonly effectText: "破韧 +61.70";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_goblin_priest";
    readonly monsterCode: "goblin_priest";
    readonly monsterName: "哥布林祭司";
    readonly name: "哥布林祭司·卡片";
    readonly level: 24;
    readonly tier: "elite";
    readonly allowedSlots: readonly ["necklace"];
    readonly effectText: "主动治疗量 +4%";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_goblin_mage";
    readonly monsterCode: "goblin_mage";
    readonly monsterName: "哥布林法师";
    readonly name: "哥布林法师·卡片";
    readonly level: 25;
    readonly tier: "elite";
    readonly allowedSlots: readonly ["ring"];
    readonly effectText: "火元素精通 +16";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_goblin_assassin";
    readonly monsterCode: "goblin_assassin";
    readonly monsterName: "哥布林刺客";
    readonly name: "哥布林刺客·卡片";
    readonly level: 29;
    readonly tier: "elite";
    readonly allowedSlots: readonly ["feet"];
    readonly effectText: "闪避修正 +4%";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_goblin_earthshaper";
    readonly monsterCode: "goblin_earthshaper";
    readonly monsterName: "哥布林土行者";
    readonly name: "哥布林土行者·卡片";
    readonly level: 30;
    readonly tier: "elite";
    readonly allowedSlots: readonly ["lower"];
    readonly effectText: "承受伤害降低 3%";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_goblin_colonel";
    readonly monsterCode: "goblin_colonel";
    readonly monsterName: "精英·哥布林上校";
    readonly name: "精英·哥布林上校·卡片";
    readonly level: 30;
    readonly tier: "elite";
    readonly allowedSlots: readonly ["shoulder"];
    readonly effectText: "命中修正 +5%";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_uzz_skeleton_berserker";
    readonly monsterCode: "uzz_skeleton_berserker";
    readonly monsterName: "骷髅狂战士";
    readonly name: "骷髅狂战士·卡片";
    readonly level: 30;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["weapon", "offhand"];
    readonly effectText: "物理攻击 +30.05";
    readonly sourcePolicy: "source_boss";
}, {
    readonly cardCode: "monster_card_uzz_skeleton_archer";
    readonly monsterCode: "uzz_skeleton_archer";
    readonly monsterName: "骷髅神箭手";
    readonly name: "骷髅神箭手·卡片";
    readonly level: 30;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["shoulder", "waist", "feet"];
    readonly effectText: "命中 +157.55";
    readonly sourcePolicy: "source_boss";
}, {
    readonly cardCode: "monster_card_uzz_pain_wraith";
    readonly monsterCode: "uzz_pain_wraith";
    readonly monsterName: "痛苦幽魂";
    readonly name: "痛苦幽魂·卡片";
    readonly level: 30;
    readonly tier: "large";
    readonly allowedSlots: readonly ["ring"];
    readonly effectText: "暗元素精通 +18";
    readonly sourcePolicy: "source_boss";
}, {
    readonly cardCode: "monster_card_uzz_skeleton_mage";
    readonly monsterCode: "uzz_skeleton_mage";
    readonly monsterName: "骷髅法师";
    readonly name: "骷髅法师·卡片";
    readonly level: 30;
    readonly tier: "large";
    readonly allowedSlots: readonly ["weapon", "offhand"];
    readonly effectText: "魔法攻击 +54.09";
    readonly sourcePolicy: "source_boss";
}, {
    readonly cardCode: "monster_card_uzz_frost_bone_dragon";
    readonly monsterCode: "uzz_frost_bone_dragon";
    readonly monsterName: "冰霜骨龙";
    readonly name: "冰霜骨龙·卡片";
    readonly level: 30;
    readonly tier: "elite";
    readonly allowedSlots: readonly ["bracelet"];
    readonly effectText: "冰元素抗性 +14；暴抗修正 +3%";
    readonly sourcePolicy: "source_boss";
}, {
    readonly cardCode: "monster_card_necromancer_uz";
    readonly monsterCode: "necromancer_uz";
    readonly monsterName: "死灵法师·乌兹";
    readonly name: "死灵法师·乌兹·卡片";
    readonly level: 32;
    readonly tier: "boss";
    readonly allowedSlots: readonly ["ring"];
    readonly effectText: "暗元素精通 +30；实际暴击 +6 个百分点";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_goblin_king";
    readonly monsterCode: "goblin_king";
    readonly monsterName: "横冲直撞的哥布林国王";
    readonly name: "横冲直撞的哥布林国王·卡片";
    readonly level: 32;
    readonly tier: "boss";
    readonly allowedSlots: readonly ["shoulder"];
    readonly effectText: "实际暴击 +8 个百分点；暴伤 +200";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_habadragon";
    readonly monsterCode: "habadragon";
    readonly monsterName: "横冲直撞哈巴龙·载王中";
    readonly name: "横冲直撞哈巴龙·载王中·卡片";
    readonly level: 30;
    readonly tier: "boss";
    readonly allowedSlots: readonly ["waist"];
    readonly effectText: "实际命中 +6 个百分点；破韧 +160";
    readonly sourcePolicy: "source_boss";
}, {
    readonly cardCode: "monster_card_goblin_royal_guard";
    readonly monsterCode: "goblin_royal_guard";
    readonly monsterName: "王庭盾卫";
    readonly name: "王庭盾卫·卡片";
    readonly level: 28;
    readonly tier: "elite";
    readonly allowedSlots: readonly ["lower"];
    readonly effectText: "承受物理伤害降低 4%";
    readonly sourcePolicy: "source_boss";
}, {
    readonly cardCode: "monster_card_goblin_royal_spearman";
    readonly monsterCode: "goblin_royal_spearman";
    readonly monsterName: "雷矛侍卫";
    readonly name: "雷矛侍卫·卡片";
    readonly level: 28;
    readonly tier: "elite";
    readonly allowedSlots: readonly ["shoulder"];
    readonly effectText: "命中修正 +4%";
    readonly sourcePolicy: "source_boss";
}, {
    readonly cardCode: "monster_card_scholar_ga";
    readonly monsterCode: "scholar_ga";
    readonly monsterName: "大学者·噶";
    readonly name: "大学者·噶·卡片";
    readonly level: 22;
    readonly tier: "boss";
    readonly allowedSlots: readonly ["ring"];
    readonly effectText: "实际命中 +5 个百分点；魔法攻击 +42.98";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_dew_slime";
    readonly monsterCode: "dew_slime";
    readonly monsterName: "露珠史莱姆";
    readonly name: "露珠史莱姆·卡片";
    readonly level: 1;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["upper", "lower"];
    readonly effectText: "生命上限 +64.04";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_clover_rabbit";
    readonly monsterCode: "clover_rabbit";
    readonly monsterName: "苜蓿兔";
    readonly name: "苜蓿兔·卡片";
    readonly level: 1;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["shoulder", "waist", "feet"];
    readonly effectText: "闪避 +28.10";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_sprout_rat";
    readonly monsterCode: "sprout_rat";
    readonly monsterName: "根芽鼠";
    readonly name: "根芽鼠·卡片";
    readonly level: 2;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["weapon", "offhand"];
    readonly effectText: "物理攻击 +4.76";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_pollen_bee";
    readonly monsterCode: "pollen_bee";
    readonly monsterName: "花粉蜂";
    readonly name: "花粉蜂·卡片";
    readonly level: 2;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["shoulder", "waist", "feet"];
    readonly effectText: "命中 +29.82";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_grass_antler_deer";
    readonly monsterCode: "grass_antler_deer";
    readonly monsterName: "草角鹿";
    readonly name: "草角鹿·卡片";
    readonly level: 3;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["shoulder", "waist", "feet"];
    readonly effectText: "破韧 +11.36";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_mossback_turtle";
    readonly monsterCode: "mossback_turtle";
    readonly monsterName: "苔背龟";
    readonly name: "苔背龟·卡片";
    readonly level: 3;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["upper", "lower"];
    readonly effectText: "物理防御 +15.26";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_windchime_bird";
    readonly monsterCode: "windchime_bird";
    readonly monsterName: "风铃鸟";
    readonly name: "风铃鸟·卡片";
    readonly level: 4;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["shoulder", "waist", "feet"];
    readonly effectText: "速度 +28.57";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_vine_puppet";
    readonly monsterCode: "vine_puppet";
    readonly monsterName: "蔓藤傀儡";
    readonly name: "蔓藤傀儡·卡片";
    readonly level: 4;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["upper", "lower"];
    readonly effectText: "魔法防御 +15.46";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_dawn_fox";
    readonly monsterCode: "dawn_fox";
    readonly monsterName: "晨光狐";
    readonly name: "晨光狐·卡片";
    readonly level: 5;
    readonly tier: "large";
    readonly allowedSlots: readonly ["shoulder", "waist", "feet"];
    readonly effectText: "暴击 +53.25";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_grassroot_guard";
    readonly monsterCode: "grassroot_guard";
    readonly monsterName: "草原守根";
    readonly name: "草原守根·卡片";
    readonly level: 6;
    readonly tier: "elite";
    readonly allowedSlots: readonly ["lower"];
    readonly effectText: "承受伤害降低 2%";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_rootcrown_ram";
    readonly monsterCode: "rootcrown_ram";
    readonly monsterName: "根冠公羊";
    readonly name: "根冠公羊·卡片";
    readonly level: 6;
    readonly tier: "boss";
    readonly allowedSlots: readonly ["upper"];
    readonly effectText: "生命上限提高 20%；承受伤害降低 4%";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_bubble_slime";
    readonly monsterCode: "bubble_slime";
    readonly monsterName: "水泡史莱姆";
    readonly name: "水泡史莱姆·卡片";
    readonly level: 4;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["weapon", "offhand"];
    readonly effectText: "魔力上限 +67.19";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_mudfin_murloc";
    readonly monsterCode: "mudfin_murloc";
    readonly monsterName: "泥鳍鱼人";
    readonly name: "泥鳍鱼人·卡片";
    readonly level: 4;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["weapon", "offhand"];
    readonly effectText: "物理攻击 +4.76";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_river_shell_crab";
    readonly monsterCode: "river_shell_crab";
    readonly monsterName: "河壳蟹";
    readonly name: "河壳蟹·卡片";
    readonly level: 5;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["upper", "lower"];
    readonly effectText: "物理防御 +19.59";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_watergrass_snake";
    readonly monsterCode: "watergrass_snake";
    readonly monsterName: "水草蛇";
    readonly name: "水草蛇·卡片";
    readonly level: 5;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["shoulder", "waist", "feet"];
    readonly effectText: "破韧 +13.41";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_floatlight_jelly";
    readonly monsterCode: "floatlight_jelly";
    readonly monsterName: "浮灯水母";
    readonly name: "浮灯水母·卡片";
    readonly level: 6;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["weapon", "offhand"];
    readonly effectText: "魔法攻击 +6.48";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_reed_spirit";
    readonly monsterCode: "reed_spirit";
    readonly monsterName: "湿苇精";
    readonly name: "湿苇精·卡片";
    readonly level: 6;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["upper", "lower"];
    readonly effectText: "生命上限 +90.05";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_rapid_otter";
    readonly monsterCode: "rapid_otter";
    readonly monsterName: "急流獭";
    readonly name: "急流獭·卡片";
    readonly level: 7;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["shoulder", "waist", "feet"];
    readonly effectText: "暴击 +41.48";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_ironbeak_heron";
    readonly monsterCode: "ironbeak_heron";
    readonly monsterName: "铁嘴鹭";
    readonly name: "铁嘴鹭·卡片";
    readonly level: 7;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["shoulder", "waist", "feet"];
    readonly effectText: "命中 +41.48";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_mire_toad";
    readonly monsterCode: "mire_toad";
    readonly monsterName: "泥潭蟾王";
    readonly name: "泥潭蟾王·卡片";
    readonly level: 8;
    readonly tier: "large";
    readonly allowedSlots: readonly ["upper", "lower"];
    readonly effectText: "生命上限 +138.92";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_river_scavenger";
    readonly monsterCode: "river_scavenger";
    readonly monsterName: "河道拾荒者";
    readonly name: "河道拾荒者·卡片";
    readonly level: 8;
    readonly tier: "elite";
    readonly allowedSlots: readonly ["shoulder"];
    readonly effectText: "命中修正 +2%";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_dawntide_crocodile";
    readonly monsterCode: "dawntide_crocodile";
    readonly monsterName: "晨潮鳄王";
    readonly name: "晨潮鳄王·卡片";
    readonly level: 10;
    readonly tier: "boss";
    readonly allowedSlots: readonly ["shoulder"];
    readonly effectText: "实际命中 +5 个百分点；破韧 +45";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_shard_hermit";
    readonly monsterCode: "shard_hermit";
    readonly monsterName: "碎壳寄居蟹";
    readonly name: "碎壳寄居蟹·卡片";
    readonly level: 7;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["upper", "lower"];
    readonly effectText: "物理防御 +20.45";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_salt_urchin";
    readonly monsterCode: "salt_urchin";
    readonly monsterName: "盐刺海胆";
    readonly name: "盐刺海胆·卡片";
    readonly level: 7;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["upper", "lower"];
    readonly effectText: "暴免 +41.48";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_sandrunner_lizard";
    readonly monsterCode: "sandrunner_lizard";
    readonly monsterName: "沙行蜥";
    readonly name: "沙行蜥·卡片";
    readonly level: 8;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["shoulder", "waist", "feet"];
    readonly effectText: "速度 +35.20";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_tide_slime";
    readonly monsterCode: "tide_slime";
    readonly monsterName: "潮汐史莱姆";
    readonly name: "潮汐史莱姆·卡片";
    readonly level: 8;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["weapon", "offhand"];
    readonly effectText: "魔力上限 +86.53";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_shell_gull";
    readonly monsterCode: "shell_gull";
    readonly monsterName: "拾贝鸥盗";
    readonly name: "拾贝鸥盗·卡片";
    readonly level: 9;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["shoulder", "waist", "feet"];
    readonly effectText: "命中 +44.92";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_rockarm_crab";
    readonly monsterCode: "rockarm_crab";
    readonly monsterName: "岩甲蟹";
    readonly name: "岩甲蟹·卡片";
    readonly level: 9;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["upper", "lower"];
    readonly effectText: "生命上限 +103.81";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_headwind_sharkdog";
    readonly monsterCode: "headwind_sharkdog";
    readonly monsterName: "逆风鲨犬";
    readonly name: "逆风鲨犬·卡片";
    readonly level: 10;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["shoulder", "waist", "feet"];
    readonly effectText: "暴击 +47.78";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_tidewraith";
    readonly monsterCode: "tidewraith";
    readonly monsterName: "潮痕幽灵";
    readonly name: "潮痕幽灵·卡片";
    readonly level: 10;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["necklace", "bracelet", "ring"];
    readonly effectText: "暗元素精通 +5.00";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_shore_giant_lizard";
    readonly monsterCode: "shore_giant_lizard";
    readonly monsterName: "石滩巨蜥";
    readonly name: "石滩巨蜥·卡片";
    readonly level: 11;
    readonly tier: "large";
    readonly allowedSlots: readonly ["upper"];
    readonly effectText: "物理防御 +48.46";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_ebb_acolyte";
    readonly monsterCode: "ebb_acolyte";
    readonly monsterName: "退潮祭徒";
    readonly name: "退潮祭徒·卡片";
    readonly level: 12;
    readonly tier: "elite";
    readonly allowedSlots: readonly ["necklace"];
    readonly effectText: "主动治疗量 +3%";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_shattertide_crab";
    readonly monsterCode: "shattertide_crab";
    readonly monsterName: "碎潮巨蟹";
    readonly name: "碎潮巨蟹·卡片";
    readonly level: 14;
    readonly tier: "boss";
    readonly allowedSlots: readonly ["lower"];
    readonly effectText: "物理防御 +120；承受物理伤害降低 8%";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_rubble_beast";
    readonly monsterCode: "rubble_beast";
    readonly monsterName: "碎岩兽";
    readonly name: "碎岩兽·卡片";
    readonly level: 20;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["necklace", "bracelet", "ring"];
    readonly effectText: "土元素抗性 +7.00";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_canyon_jackal";
    readonly monsterCode: "canyon_jackal";
    readonly monsterName: "峡谷豺";
    readonly name: "峡谷豺·卡片";
    readonly level: 21;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["shoulder", "waist", "feet"];
    readonly effectText: "暴击 +97.46";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_ironfeather_vulture";
    readonly monsterCode: "ironfeather_vulture";
    readonly monsterName: "铁羽秃鹫";
    readonly name: "铁羽秃鹫·卡片";
    readonly level: 22;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["shoulder", "waist", "feet"];
    readonly effectText: "命中 +102.62";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_mountain_beetle";
    readonly monsterCode: "mountain_beetle";
    readonly monsterName: "山甲虫";
    readonly name: "山甲虫·卡片";
    readonly level: 23;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["upper", "lower"];
    readonly effectText: "物理防御 +55.85";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_cliff_ram";
    readonly monsterCode: "cliff_ram";
    readonly monsterName: "峭壁羊怪";
    readonly name: "峭壁羊怪·卡片";
    readonly level: 24;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["shoulder", "waist", "feet"];
    readonly effectText: "破韧 +46.59";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_stonevein_golem";
    readonly monsterCode: "stonevein_golem";
    readonly monsterName: "石脉傀儡";
    readonly name: "石脉傀儡·卡片";
    readonly level: 25;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["upper", "lower"];
    readonly effectText: "生命上限 +284.08";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_ember_bat";
    readonly monsterCode: "ember_bat";
    readonly monsterName: "火绒蝠";
    readonly name: "火绒蝠·卡片";
    readonly level: 24;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["necklace", "bracelet", "ring"];
    readonly effectText: "火元素精通 +7.00";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_mine_goblin";
    readonly monsterCode: "mine_goblin";
    readonly monsterName: "矿道哥布林";
    readonly name: "矿道哥布林·卡片";
    readonly level: 25;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["weapon", "offhand"];
    readonly effectText: "物理攻击 +23.62";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_fault_centipede";
    readonly monsterCode: "fault_centipede";
    readonly monsterName: "断层蜈蚣";
    readonly name: "断层蜈蚣·卡片";
    readonly level: 28;
    readonly tier: "large";
    readonly allowedSlots: readonly ["waist"];
    readonly effectText: "破韧 +103.27";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_canyon_overseer";
    readonly monsterCode: "canyon_overseer";
    readonly monsterName: "峡谷监工";
    readonly name: "峡谷监工·卡片";
    readonly level: 30;
    readonly tier: "elite";
    readonly allowedSlots: readonly ["waist"];
    readonly effectText: "暴抗修正 +4%";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_gruen_mountainheart";
    readonly monsterCode: "gruen_mountainheart";
    readonly monsterName: "山脉心核·格鲁恩";
    readonly name: "山脉心核·格鲁恩·卡片";
    readonly level: 32;
    readonly tier: "boss";
    readonly allowedSlots: readonly ["upper"];
    readonly effectText: "承受伤害降低 10%；土元素抗性 +30";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_rediron_wisp";
    readonly monsterCode: "rediron_wisp";
    readonly monsterName: "赤铁矿灵";
    readonly name: "赤铁矿灵·卡片";
    readonly level: 20;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["weapon", "offhand"];
    readonly effectText: "魔法攻击 +17.19";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_moltenscorpion";
    readonly monsterCode: "moltenscorpion";
    readonly monsterName: "熔洞蝎";
    readonly name: "熔洞蝎·卡片";
    readonly level: 21;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["shoulder", "waist", "feet"];
    readonly effectText: "暴伤 +97.46";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_ash_lizard";
    readonly monsterCode: "ash_lizard";
    readonly monsterName: "灰烬蜥";
    readonly name: "灰烬蜥·卡片";
    readonly level: 22;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["necklace", "bracelet", "ring"];
    readonly effectText: "火元素抗性 +7.00";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_magnet_golem";
    readonly monsterCode: "magnet_golem";
    readonly monsterName: "磁石傀儡";
    readonly name: "磁石傀儡·卡片";
    readonly level: 23;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["upper", "lower"];
    readonly effectText: "韧性 +99.80";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_cinder_boar";
    readonly monsterCode: "cinder_boar";
    readonly monsterName: "焦岩野猪";
    readonly name: "焦岩野猪·卡片";
    readonly level: 24;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["weapon", "offhand"];
    readonly effectText: "物理攻击 +17.19";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_mine_hexer";
    readonly monsterCode: "mine_hexer";
    readonly monsterName: "矿坑咒师";
    readonly name: "矿坑咒师·卡片";
    readonly level: 24;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["necklace", "bracelet", "ring"];
    readonly effectText: "暗元素精通 +7.00";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_furnace_beetle";
    readonly monsterCode: "furnace_beetle";
    readonly monsterName: "炉心甲虫";
    readonly name: "炉心甲虫·卡片";
    readonly level: 25;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["upper", "lower"];
    readonly effectText: "物理防御 +71.41";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_ore_raider";
    readonly monsterCode: "ore_raider";
    readonly monsterName: "盗矿团弩手";
    readonly name: "盗矿团弩手·卡片";
    readonly level: 25;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["shoulder", "waist", "feet"];
    readonly effectText: "命中 +121.89";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_lava_rockbeast";
    readonly monsterCode: "lava_rockbeast";
    readonly monsterName: "熔岩岩兽";
    readonly name: "熔岩岩兽·卡片";
    readonly level: 28;
    readonly tier: "large";
    readonly allowedSlots: readonly ["weapon"];
    readonly effectText: "魔法攻击 +51.97";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_rediron_torchbearer";
    readonly monsterCode: "rediron_torchbearer";
    readonly monsterName: "赤铁执炬官";
    readonly name: "赤铁执炬官·卡片";
    readonly level: 30;
    readonly tier: "elite";
    readonly allowedSlots: readonly ["bracelet"];
    readonly effectText: "火元素抗性 +12；承受火元素伤害降低 2%";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_valk_forge_overseer";
    readonly monsterCode: "valk_forge_overseer";
    readonly monsterName: "熔炉监工·瓦尔克";
    readonly name: "熔炉监工·瓦尔克·卡片";
    readonly level: 32;
    readonly tier: "boss";
    readonly allowedSlots: readonly ["weapon"];
    readonly effectText: "攻击赋予火属性；火元素精通 +30";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_mistalgae_mass";
    readonly monsterCode: "mistalgae_mass";
    readonly monsterName: "雾藻团";
    readonly name: "雾藻团·卡片";
    readonly level: 20;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["necklace", "bracelet", "ring"];
    readonly effectText: "木元素抗性 +7.00";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_marsh_crocodile";
    readonly monsterCode: "marsh_crocodile";
    readonly monsterName: "沼泽鳄";
    readonly name: "沼泽鳄·卡片";
    readonly level: 21;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["weapon", "offhand"];
    readonly effectText: "物理攻击 +17.19";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_bog_midge";
    readonly monsterCode: "bog_midge";
    readonly monsterName: "毒沼蜉蝣";
    readonly name: "毒沼蜉蝣·卡片";
    readonly level: 22;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["shoulder", "waist", "feet"];
    readonly effectText: "破韧 +41.43";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_reed_walker";
    readonly monsterCode: "reed_walker";
    readonly monsterName: "芦苇行尸";
    readonly name: "芦苇行尸·卡片";
    readonly level: 23;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["upper", "lower"];
    readonly effectText: "魔法防御 +54.99";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_watermirror_siren";
    readonly monsterCode: "watermirror_siren";
    readonly monsterName: "水镜妖";
    readonly name: "水镜妖·卡片";
    readonly level: 24;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["necklace", "bracelet", "ring"];
    readonly effectText: "水元素精通 +7.00";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_blackfeather_stork";
    readonly monsterCode: "blackfeather_stork";
    readonly monsterName: "黑羽鹳";
    readonly name: "黑羽鹳·卡片";
    readonly level: 24;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["shoulder", "waist", "feet"];
    readonly effectText: "命中 +112.94";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_bogfire_wisp";
    readonly monsterCode: "bogfire_wisp";
    readonly monsterName: "沼火鬼灯";
    readonly name: "沼火鬼灯·卡片";
    readonly level: 25;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["necklace", "bracelet", "ring"];
    readonly effectText: "火元素精通 +8.00";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_mudarmor_rhino";
    readonly monsterCode: "mudarmor_rhino";
    readonly monsterName: "泥甲犀";
    readonly name: "泥甲犀·卡片";
    readonly level: 25;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["upper", "lower"];
    readonly effectText: "生命上限 +284.08";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_rottedroot_python";
    readonly monsterCode: "rottedroot_python";
    readonly monsterName: "腐根巨蟒";
    readonly name: "腐根巨蟒·卡片";
    readonly level: 28;
    readonly tier: "large";
    readonly allowedSlots: readonly ["lower"];
    readonly effectText: "生命上限 +585.65";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_reed_shaman";
    readonly monsterCode: "reed_shaman";
    readonly monsterName: "芦荡巫医";
    readonly name: "芦荡巫医·卡片";
    readonly level: 30;
    readonly tier: "elite";
    readonly allowedSlots: readonly ["necklace"];
    readonly effectText: "主动治疗量 +5%";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_threehead_mother";
    readonly monsterCode: "threehead_mother";
    readonly monsterName: "三首雾沼蛇母";
    readonly name: "三首雾沼蛇母·卡片";
    readonly level: 32;
    readonly tier: "boss";
    readonly allowedSlots: readonly ["necklace"];
    readonly effectText: "木、火、风元素精通各 +15；主动治疗量 +10%";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_starmud_slime";
    readonly monsterCode: "starmud_slime";
    readonly monsterName: "星泥史莱姆";
    readonly name: "星泥史莱姆·卡片";
    readonly level: 36;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["necklace", "bracelet", "ring"];
    readonly effectText: "暗元素精通 +10.00";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_crater_toad";
    readonly monsterCode: "crater_toad";
    readonly monsterName: "陨坑蟾蜍";
    readonly name: "陨坑蟾蜍·卡片";
    readonly level: 36;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["upper", "lower"];
    readonly effectText: "生命上限 +477.48";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_darkbog_snake";
    readonly monsterCode: "darkbog_snake";
    readonly monsterName: "暗沼水蛇";
    readonly name: "暗沼水蛇·卡片";
    readonly level: 37;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["shoulder", "waist", "feet"];
    readonly effectText: "暴击 +210.26";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_fallenstar_murloc";
    readonly monsterCode: "fallenstar_murloc";
    readonly monsterName: "沉星鱼人";
    readonly name: "沉星鱼人·卡片";
    readonly level: 37;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["shoulder", "waist", "feet"];
    readonly effectText: "命中 +210.26";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_mud_parasite";
    readonly monsterCode: "mud_parasite";
    readonly monsterName: "泥星寄生虫";
    readonly name: "泥星寄生虫·卡片";
    readonly level: 38;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["shoulder", "waist", "feet"];
    readonly effectText: "破韧 +91.77";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_faceless_bogspirit";
    readonly monsterCode: "faceless_bogspirit";
    readonly monsterName: "无面沼灵";
    readonly name: "无面沼灵·卡片";
    readonly level: 38;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["upper", "lower"];
    readonly effectText: "魔法防御 +119.99";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_meteor_carapace";
    readonly monsterCode: "meteor_carapace";
    readonly monsterName: "坠星甲兽";
    readonly name: "坠星甲兽·卡片";
    readonly level: 39;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["upper", "lower"];
    readonly effectText: "物理防御 +123.64";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_lost_lamplighter";
    readonly monsterCode: "lost_lamplighter";
    readonly monsterName: "迷航灯使";
    readonly name: "迷航灯使·卡片";
    readonly level: 39;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["necklace", "bracelet", "ring"];
    readonly effectText: "暗元素抗性 +10.00";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_crater_eel";
    readonly monsterCode: "crater_eel";
    readonly monsterName: "陨潭巨鳗";
    readonly name: "陨潭巨鳗·卡片";
    readonly level: 40;
    readonly tier: "large";
    readonly allowedSlots: readonly ["necklace"];
    readonly effectText: "雷元素精通 +24.20";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_fallenstar_warden";
    readonly monsterCode: "fallenstar_warden";
    readonly monsterName: "沉星看守";
    readonly name: "沉星看守·卡片";
    readonly level: 40;
    readonly tier: "elite";
    readonly allowedSlots: readonly ["upper"];
    readonly effectText: "承受魔法伤害降低 4%";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_fallingstar_mudid";
    readonly monsterCode: "fallingstar_mudid";
    readonly monsterName: "坠星泥偶";
    readonly name: "坠星泥偶·卡片";
    readonly level: 40;
    readonly tier: "boss";
    readonly allowedSlots: readonly ["ring"];
    readonly effectText: "暗元素精通 +36；实际命中 +6 个百分点";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_tundra_wolf";
    readonly monsterCode: "tundra_wolf";
    readonly monsterName: "冻原狼";
    readonly name: "冻原狼·卡片";
    readonly level: 40;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["shoulder", "waist", "feet"];
    readonly effectText: "暴击 +244.56";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_snowplush_bear";
    readonly monsterCode: "snowplush_bear";
    readonly monsterName: "雪绒熊";
    readonly name: "雪绒熊·卡片";
    readonly level: 40;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["upper", "lower"];
    readonly effectText: "生命上限 +564.62";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_ice_spike_sprite";
    readonly monsterCode: "ice_spike_sprite";
    readonly monsterName: "冰棱精";
    readonly name: "冰棱精·卡片";
    readonly level: 41;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["necklace", "bracelet", "ring"];
    readonly effectText: "冰元素精通 +11.00";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_coldpine_ent";
    readonly monsterCode: "coldpine_ent";
    readonly monsterName: "寒松树精";
    readonly name: "寒松树精·卡片";
    readonly level: 41;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["necklace", "bracelet", "ring"];
    readonly effectText: "冰元素抗性 +11.00";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_whiteantler_guard";
    readonly monsterCode: "whiteantler_guard";
    readonly monsterName: "白角鹿王卫";
    readonly name: "白角鹿王卫·卡片";
    readonly level: 42;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["upper", "lower"];
    readonly effectText: "韧性 +245.99";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_snowblind_eagle";
    readonly monsterCode: "snowblind_eagle";
    readonly monsterName: "雪盲鹰";
    readonly name: "雪盲鹰·卡片";
    readonly level: 42;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["shoulder", "waist", "feet"];
    readonly effectText: "命中 +261.76";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_icelake_spirit";
    readonly monsterCode: "icelake_spirit";
    readonly monsterName: "冰湖水灵";
    readonly name: "冰湖水灵·卡片";
    readonly level: 43;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["upper", "lower"];
    readonly effectText: "魔法防御 +146.77";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_frostarmored_rider";
    readonly monsterCode: "frostarmored_rider";
    readonly monsterName: "霜甲骑尸";
    readonly name: "霜甲骑尸·卡片";
    readonly level: 43;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["upper", "lower"];
    readonly effectText: "物理防御 +149.13";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_permafrost_giant";
    readonly monsterCode: "permafrost_giant";
    readonly monsterName: "冻土巨人";
    readonly name: "冻土巨人·卡片";
    readonly level: 45;
    readonly tier: "large";
    readonly allowedSlots: readonly ["lower"];
    readonly effectText: "物理防御 +122.55；魔法防御 +120.52";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_snowline_hunter";
    readonly monsterCode: "snowline_hunter";
    readonly monsterName: "雪线猎官";
    readonly name: "雪线猎官·卡片";
    readonly level: 45;
    readonly tier: "elite";
    readonly allowedSlots: readonly ["shoulder"];
    readonly effectText: "命中修正 +5%";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_frostking_whiteantler";
    readonly monsterCode: "frostking_whiteantler";
    readonly monsterName: "白角霜王";
    readonly name: "白角霜王·卡片";
    readonly level: 45;
    readonly tier: "boss";
    readonly allowedSlots: readonly ["weapon"];
    readonly effectText: "无元素普通攻击赋予冰属性；冰元素精通 +40；冰元素伤害提高 8%";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_thunderhawk";
    readonly monsterCode: "thunderhawk";
    readonly monsterName: "雷羽隼";
    readonly name: "雷羽隼·卡片";
    readonly level: 45;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["necklace", "bracelet", "ring"];
    readonly effectText: "雷元素精通 +12.00";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_cliff_ram_thunder";
    readonly monsterCode: "cliff_ram_thunder";
    readonly monsterName: "峭壁雷羊";
    readonly name: "峭壁雷羊·卡片";
    readonly level: 45;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["shoulder", "waist", "feet"];
    readonly effectText: "破韧 +122.55";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_storm_gargoyle";
    readonly monsterCode: "storm_gargoyle";
    readonly monsterName: "风暴石像";
    readonly name: "风暴石像·卡片";
    readonly level: 46;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["upper", "lower"];
    readonly effectText: "物理防御 +177.22";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_cloudsplit_bat";
    readonly monsterCode: "cloudsplit_bat";
    readonly monsterName: "裂云蝠";
    readonly name: "裂云蝠·卡片";
    readonly level: 46;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["shoulder", "waist", "feet"];
    readonly effectText: "速度 +207.47";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_thundercopper_golem";
    readonly monsterCode: "thundercopper_golem";
    readonly monsterName: "雷铜傀儡";
    readonly name: "雷铜傀儡·卡片";
    readonly level: 47;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["necklace", "bracelet", "ring"];
    readonly effectText: "雷元素抗性 +12.00";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_bridge_raider";
    readonly monsterCode: "bridge_raider";
    readonly monsterName: "悬桥掠夺者";
    readonly name: "悬桥掠夺者·卡片";
    readonly level: 47;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["shoulder", "waist", "feet"];
    readonly effectText: "暴伤 +310.21";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_windblade_elemental";
    readonly monsterCode: "windblade_elemental";
    readonly monsterName: "风刃元素";
    readonly name: "风刃元素·卡片";
    readonly level: 48;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["necklace", "bracelet", "ring"];
    readonly effectText: "风元素精通 +12.00";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_storm_priest";
    readonly monsterCode: "storm_priest";
    readonly monsterName: "雷暴祭司";
    readonly name: "雷暴祭司·卡片";
    readonly level: 48;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["weapon", "offhand"];
    readonly effectText: "魔法攻击 +57.91";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_clifftop_lizard";
    readonly monsterCode: "clifftop_lizard";
    readonly monsterName: "崖顶雷蜥";
    readonly name: "崖顶雷蜥·卡片";
    readonly level: 49;
    readonly tier: "large";
    readonly allowedSlots: readonly ["necklace"];
    readonly effectText: "雷元素精通 +10.80；雷元素抗性 +10.80";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_cliff_arbiter";
    readonly monsterCode: "cliff_arbiter";
    readonly monsterName: "断崖裁断者";
    readonly name: "断崖裁断者·卡片";
    readonly level: 50;
    readonly tier: "elite";
    readonly allowedSlots: readonly ["waist"];
    readonly effectText: "命中修正 +4%；雷元素抗性 +8";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_askr_stormroc";
    readonly monsterCode: "askr_stormroc";
    readonly monsterName: "风暴巨隼·阿斯克";
    readonly name: "风暴巨隼·阿斯克·卡片";
    readonly level: 50;
    readonly tier: "boss";
    readonly allowedSlots: readonly ["weapon"];
    readonly effectText: "无元素普通攻击赋予雷属性；实际命中 +8 个百分点；雷元素伤害提高 8%";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_moon_dust_wraith";
    readonly monsterCode: "moon_dust_wraith";
    readonly monsterName: "月尘幽魂";
    readonly name: "月尘幽魂·卡片";
    readonly level: 48;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["necklace", "bracelet", "ring"];
    readonly effectText: "暗元素精通 +12.00";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_ruin_stoneguard";
    readonly monsterCode: "ruin_stoneguard";
    readonly monsterName: "遗迹石卫";
    readonly name: "遗迹石卫·卡片";
    readonly level: 48;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["upper", "lower"];
    readonly effectText: "物理防御 +181.52";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_solar_eclipse_priest";
    readonly monsterCode: "solar_eclipse_priest";
    readonly monsterName: "日蚀祭司";
    readonly name: "日蚀祭司·卡片";
    readonly level: 49;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["necklace", "bracelet", "ring"];
    readonly effectText: "光元素精通 +12.00";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_lunar_eclipse_assassin";
    readonly monsterCode: "lunar_eclipse_assassin";
    readonly monsterName: "月蚀刺客";
    readonly name: "月蚀刺客·卡片";
    readonly level: 49;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["shoulder", "waist", "feet"];
    readonly effectText: "暴击 +327.41";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_starchart_doll";
    readonly monsterCode: "starchart_doll";
    readonly monsterName: "星图魔偶";
    readonly name: "星图魔偶·卡片";
    readonly level: 49;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["weapon", "offhand"];
    readonly effectText: "魔法攻击 +57.91";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_well_wraith";
    readonly monsterCode: "well_wraith";
    readonly monsterName: "古井怨灵";
    readonly name: "古井怨灵·卡片";
    readonly level: 50;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["necklace", "bracelet", "ring"];
    readonly effectText: "暗元素抗性 +13.00";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_lost_inquisitor";
    readonly monsterCode: "lost_inquisitor";
    readonly monsterName: "失落审判官";
    readonly name: "失落审判官·卡片";
    readonly level: 50;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["necklace", "bracelet", "ring"];
    readonly effectText: "光元素抗性 +13.00";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_broken_armillary";
    readonly monsterCode: "broken_armillary";
    readonly monsterName: "破损天仪";
    readonly name: "破损天仪·卡片";
    readonly level: 50;
    readonly tier: "normal";
    readonly allowedSlots: readonly ["shoulder", "waist", "feet"];
    readonly effectText: "命中 +354.58";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_moonwheel_tombbeast";
    readonly monsterCode: "moonwheel_tombbeast";
    readonly monsterName: "月轮守墓兽";
    readonly name: "月轮守墓兽·卡片";
    readonly level: 50;
    readonly tier: "large";
    readonly allowedSlots: readonly ["upper"];
    readonly effectText: "暴抗 +638.25";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_keykeeper_ruin";
    readonly monsterCode: "keykeeper_ruin";
    readonly monsterName: "遗迹执钥人";
    readonly name: "遗迹执钥人·卡片";
    readonly level: 50;
    readonly tier: "elite";
    readonly allowedSlots: readonly ["bracelet"];
    readonly effectText: "暴免修正 +5%";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_seles_eclipse_watcher";
    readonly monsterCode: "seles_eclipse_watcher";
    readonly monsterName: "月蚀守望者·塞勒斯";
    readonly name: "月蚀守望者·塞勒斯·卡片";
    readonly level: 50;
    readonly tier: "boss";
    readonly allowedSlots: readonly ["weapon"];
    readonly effectText: "无元素普通攻击赋予光属性；光元素精通 +45；实际暴击 +6 个百分点";
    readonly sourcePolicy: "kill";
}, {
    readonly cardCode: "monster_card_city_marshal_blake_s3";
    readonly monsterCode: "city_marshal_blake";
    readonly monsterName: "布莱克";
    readonly name: "布莱克·巡街步法·卡片";
    readonly level: 20;
    readonly tier: "elite";
    readonly allowedSlots: readonly ["feet"];
    readonly effectText: "地图单次移动上限 +1格";
    readonly sourcePolicy: "city_pursuit";
    readonly pursuitRank: "s3";
}, {
    readonly cardCode: "monster_card_city_marshal_blake_s4";
    readonly monsterCode: "city_marshal_blake";
    readonly monsterName: "布莱克";
    readonly name: "布莱克·街巷追击·卡片";
    readonly level: 25;
    readonly tier: "elite";
    readonly allowedSlots: readonly ["feet"];
    readonly effectText: "地图单次移动上限 +1格；负重导致的移动惩罚减少20%";
    readonly sourcePolicy: "city_pursuit";
    readonly pursuitRank: "s4";
}, {
    readonly cardCode: "monster_card_city_priest_mare_s4";
    readonly monsterCode: "city_priest_mare";
    readonly monsterName: "玛蕾";
    readonly name: "玛蕾·安抚言辞·卡片";
    readonly level: 25;
    readonly tier: "elite";
    readonly allowedSlots: readonly ["necklace"];
    readonly effectText: "合法怪物交涉成功率 +2个百分点";
    readonly sourcePolicy: "city_pursuit";
    readonly pursuitRank: "s4";
}, {
    readonly cardCode: "monster_card_city_captain_roderick_s5";
    readonly monsterCode: "city_captain_roderick";
    readonly monsterName: "罗德里克";
    readonly name: "罗德里克·封锁线·卡片";
    readonly level: 30;
    readonly tier: "elite";
    readonly allowedSlots: readonly ["waist"];
    readonly effectText: "普通感知半径 +1格；显示范围内怪物的移动/静止状态";
    readonly sourcePolicy: "city_pursuit";
    readonly pursuitRank: "s5";
}, {
    readonly cardCode: "monster_card_city_mage_sen_s5";
    readonly monsterCode: "city_mage_sen";
    readonly monsterName: "赛恩";
    readonly name: "赛恩·元素勘察·卡片";
    readonly level: 30;
    readonly tier: "elite";
    readonly allowedSlots: readonly ["ring"];
    readonly effectText: "普通感知半径 +1格；每个怪物实例首次鉴识额外揭示其最高元素抗性对应元素及数值";
    readonly sourcePolicy: "city_pursuit";
    readonly pursuitRank: "s5";
}, {
    readonly cardCode: "monster_card_city_priest_mare_s5";
    readonly monsterCode: "city_priest_mare";
    readonly monsterName: "玛蕾";
    readonly name: "玛蕾·止争祷词·卡片";
    readonly level: 30;
    readonly tier: "elite";
    readonly allowedSlots: readonly ["necklace"];
    readonly effectText: "合法怪物交涉成功率 +3个百分点；中性礼物引发的敌意概率降低10%";
    readonly sourcePolicy: "city_pursuit";
    readonly pursuitRank: "s5";
}, {
    readonly cardCode: "monster_card_city_rogue_loke_s5";
    readonly monsterCode: "city_rogue_loke";
    readonly monsterName: "洛克";
    readonly name: "洛克·巷影·卡片";
    readonly level: 30;
    readonly tier: "elite";
    readonly allowedSlots: readonly ["feet"];
    readonly effectText: "地图单次移动上限 +1格；普通移动引发的可随机野外遭遇概率降低10%";
    readonly sourcePolicy: "city_pursuit";
    readonly pursuitRank: "s5";
}, {
    readonly cardCode: "monster_card_city_executioner_arlen_k1";
    readonly monsterCode: "city_executioner_arlen";
    readonly monsterName: "阿伦";
    readonly name: "阿伦·追迹·卡片";
    readonly level: 35;
    readonly tier: "elite";
    readonly allowedSlots: readonly ["shoulder"];
    readonly effectText: "普通感知半径 +1格；标记1只已感知的普通/大怪，记录其最后确认位置3次本人移动";
    readonly sourcePolicy: "city_pursuit";
    readonly pursuitRank: "k1";
}, {
    readonly cardCode: "monster_card_city_executioner_arlen_k2";
    readonly monsterCode: "city_executioner_arlen";
    readonly monsterName: "阿伦";
    readonly name: "阿伦·锁迹·卡片";
    readonly level: 40;
    readonly tier: "elite";
    readonly allowedSlots: readonly ["shoulder"];
    readonly effectText: "普通感知半径 +1格；标记可包含精英，最后确认位置保留5次本人移动";
    readonly sourcePolicy: "city_pursuit";
    readonly pursuitRank: "k2";
}, {
    readonly cardCode: "monster_card_city_inquisitor_lynn_k2";
    readonly monsterCode: "city_inquisitor_lynn";
    readonly monsterName: "琳恩";
    readonly name: "琳恩·审读·卡片";
    readonly level: 40;
    readonly tier: "elite";
    readonly allowedSlots: readonly ["ring"];
    readonly effectText: "合法怪物交涉成功率 +3个百分点；交涉页面揭示当前心情所属区间";
    readonly sourcePolicy: "city_pursuit";
    readonly pursuitRank: "k2";
}, {
    readonly cardCode: "monster_card_city_executioner_arlen_k3";
    readonly monsterCode: "city_executioner_arlen";
    readonly monsterName: "阿伦";
    readonly name: "阿伦·远望追缉·卡片";
    readonly level: 45;
    readonly tier: "elite";
    readonly allowedSlots: readonly ["shoulder"];
    readonly effectText: "普通感知半径 +2格；标记1只普通/大怪/精英，最后确认位置保留5次本人移动";
    readonly sourcePolicy: "city_pursuit";
    readonly pursuitRank: "k3";
}, {
    readonly cardCode: "monster_card_city_inquisitor_lynn_k3";
    readonly monsterCode: "city_inquisitor_lynn";
    readonly monsterName: "琳恩";
    readonly name: "琳恩·问心·卡片";
    readonly level: 45;
    readonly tier: "elite";
    readonly allowedSlots: readonly ["ring"];
    readonly effectText: "合法怪物交涉成功率 +4个百分点；每场交涉首次试探不因“连续失败计数”额外提高敌意概率";
    readonly sourcePolicy: "city_pursuit";
    readonly pursuitRank: "k3";
}, {
    readonly cardCode: "monster_card_city_confessor_sola_k3";
    readonly monsterCode: "city_confessor_sola";
    readonly monsterName: "索拉";
    readonly name: "索拉·调停·卡片";
    readonly level: 45;
    readonly tier: "elite";
    readonly allowedSlots: readonly ["necklace"];
    readonly effectText: "合法怪物交涉成功率 +4个百分点；中性礼物引发的敌意概率降低15%";
    readonly sourcePolicy: "city_pursuit";
    readonly pursuitRank: "k3";
}, {
    readonly cardCode: "monster_card_city_executioner_arlen_k4";
    readonly monsterCode: "city_executioner_arlen";
    readonly monsterName: "阿伦";
    readonly name: "阿伦·天罗观察·卡片";
    readonly level: 50;
    readonly tier: "elite";
    readonly allowedSlots: readonly ["shoulder"];
    readonly effectText: "普通感知半径 +2格；可标记2只普通/大怪/精英，最后确认位置保留8次本人移动";
    readonly sourcePolicy: "city_pursuit";
    readonly pursuitRank: "k4";
}, {
    readonly cardCode: "monster_card_city_inquisitor_lynn_k4";
    readonly monsterCode: "city_inquisitor_lynn";
    readonly monsterName: "琳恩";
    readonly name: "琳恩·洞悉·卡片";
    readonly level: 50;
    readonly tier: "elite";
    readonly allowedSlots: readonly ["ring"];
    readonly effectText: "合法怪物交涉成功率 +5个百分点；每场首次送出非讨厌礼物后揭示一个该怪物的喜好类别";
    readonly sourcePolicy: "city_pursuit";
    readonly pursuitRank: "k4";
}, {
    readonly cardCode: "monster_card_city_confessor_sola_k4";
    readonly monsterCode: "city_confessor_sola";
    readonly monsterName: "索拉";
    readonly name: "索拉·宽恕·卡片";
    readonly level: 50;
    readonly tier: "elite";
    readonly allowedSlots: readonly ["necklace"];
    readonly effectText: "合法怪物交涉成功率 +5个百分点；每场首次中性礼物的敌意判定失败后，允许一次原概率重判，第二次仍失败才开战";
    readonly sourcePolicy: "city_pursuit";
    readonly pursuitRank: "k4";
}, {
    readonly cardCode: "monster_card_city_hunter_lyra_k4";
    readonly monsterCode: "city_hunter_lyra";
    readonly monsterName: "莱拉";
    readonly name: "莱拉·无痕猎途·卡片";
    readonly level: 50;
    readonly tier: "elite";
    readonly allowedSlots: readonly ["feet"];
    readonly effectText: "地图单次移动上限 +2格；普通随机野外遭遇概率降低15%；中度以下地形额外移动体力消耗降低25%";
    readonly sourcePolicy: "city_pursuit";
    readonly pursuitRank: "k4";
}, {
    readonly cardCode: "monster_card_city_chief_executor_k5";
    readonly monsterCode: "city_chief_executor";
    readonly monsterName: "凯尔";
    readonly name: "凯尔·王都通行印·卡片";
    readonly level: 80;
    readonly tier: "boss";
    readonly allowedSlots: readonly ["waist"];
    readonly effectText: "普通感知半径 +2格；无战斗且本次移动不触发强制事件时，连续3次合法移动后下次移动上限临时 +2格，随后重置；与NPC普通交谈距离 +1格";
    readonly sourcePolicy: "city_pursuit";
    readonly pursuitRank: "k5";
}, {
    readonly cardCode: "monster_card_city_executioner_arlen_k5";
    readonly monsterCode: "city_executioner_arlen";
    readonly monsterName: "阿伦";
    readonly name: "阿伦·裁决视野·卡片";
    readonly level: 60;
    readonly tier: "elite";
    readonly allowedSlots: readonly ["shoulder"];
    readonly effectText: "普通感知半径 +3格；可标记2只含BOSS的怪物，最后确认位置保留10次本人移动";
    readonly sourcePolicy: "city_pursuit";
    readonly pursuitRank: "k5";
}, {
    readonly cardCode: "monster_card_city_inquisitor_lynn_k5";
    readonly monsterCode: "city_inquisitor_lynn";
    readonly monsterName: "琳恩";
    readonly name: "琳恩·真实之证·卡片";
    readonly level: 60;
    readonly tier: "elite";
    readonly allowedSlots: readonly ["ring"];
    readonly effectText: "合法怪物交涉成功率 +6个百分点；每场首次非讨厌礼物揭示一个喜好类别；额外显示一次送礼后心情上升/下降方向";
    readonly sourcePolicy: "city_pursuit";
    readonly pursuitRank: "k5";
}, {
    readonly cardCode: "monster_card_city_confessor_sola_k5";
    readonly monsterCode: "city_confessor_sola";
    readonly monsterName: "索拉";
    readonly name: "索拉·终止敌意·卡片";
    readonly level: 60;
    readonly tier: "elite";
    readonly allowedSlots: readonly ["necklace"];
    readonly effectText: "合法怪物交涉成功率 +6个百分点；每场首次因普通交谈触发开战时作一次原敌意概率重判，第二次仍触发才开战";
    readonly sourcePolicy: "city_pursuit";
    readonly pursuitRank: "k5";
}];
