import { Format } from 'alemonjs';
import { battleStatus } from '../game/adventure.service';
export declare const appendBattleState: (markdown: ReturnType<typeof Format.createMarkdown>, battle: Awaited<ReturnType<typeof battleStatus>>) => import("alemonjs").FormatMarkDown;
export declare const battleOperationFormat: (text: string, battle: Awaited<ReturnType<typeof battleStatus>>) => Format;
export declare const battleStartFormat: (text: string, battle: Awaited<ReturnType<typeof battleStatus>>, reward?: string) => Format;
export declare const scheduleTravelCompletion: (message: any, qqUserId: string, seconds: number) => void;
export declare const guildFrontDeskFormat: (qqUserId: string, text?: string, continuingChat?: boolean) => Promise<Format>;
export declare const exploreHandler: () => Promise<void>;
export declare const inventoryHandler: () => Promise<void>;
export declare const dungeonEnterHandler: () => Promise<void>;
export declare const dungeonDownHandler: () => Promise<void>;
export declare const dungeonUpHandler: () => Promise<void>;
export declare const dungeonLeaveHandler: () => Promise<void>;
export declare const dungeonEscapeHandler: () => Promise<void>;
export declare const dungeonChestHandler: () => Promise<void>;
export declare const dungeonPvpHandler: () => Promise<void>;
export declare const playerPvpHandler: () => Promise<void>;
export declare const confirmPlayerPvpHandler: () => Promise<void>;
export declare const playerInteractionHandler: () => Promise<void>;
export declare const coordinateInteractionHandler: () => Promise<void>;
export declare const continueStoryHandler: () => Promise<void>;
export declare const buildingHandler: (action: "enter" | "ignore" | "leave" | "area") => () => Promise<void>;
export declare const guildRegistrationHandler: () => Promise<void>;
export declare const professionHandler: (action: "select" | "detail" | "choose") => () => Promise<void>;
export declare const guildChatHandler: () => Promise<void>;
export declare const guildBarrierHandler: () => Promise<void>;
export declare const adventurerCardHandler: () => Promise<void>;
export declare const pearGuideHandler: () => Promise<void>;
export declare const pearGuidePreviewHandler: () => Promise<void>;
export declare const pearGuideChatHandler: () => Promise<void>;
export declare const pearGuideLeaveHandler: () => Promise<void>;
export declare const npcLeaveHandler: () => Promise<void>;
export declare const npcEncounterHandler: (action: "talk" | "ignore") => () => Promise<void>;
export declare const mineResourceHandler: () => Promise<void>;
export declare const refreshMiningHandler: () => Promise<void>;
export declare const cancelMiningHandler: () => Promise<void>;
export declare const moveHandler: () => Promise<void>;
export declare const goToHandler: () => Promise<void>;
export declare const goToMapHandler: () => Promise<void>;
export declare const huntHandler: () => Promise<void>;
export declare const cancelTravelHandler: () => Promise<void>;
export declare const adjustMovementHandler: () => Promise<void>;
export declare const refreshTravelHandler: () => Promise<void>;
export declare const targetHandler: () => Promise<void>;
export declare const nearbyMonsterInteractionHandler: () => Promise<void>;
export declare const nearbyMonsterAttackHandler: () => Promise<void>;
export declare const ambushHandler: () => Promise<void>;
export declare const queueAmbushHandler: () => Promise<void>;
export declare const leaveOccupiedBattleHandler: () => Promise<void>;
export declare const forestGuideHandler: () => Promise<void>;
export declare const startOpeningForestBattle: (qqUserId: string, choice: "join" | "depart", message: {
    send: (params: any) => Promise<any>;
}) => Promise<void>;
export declare const switchTargetHandler: () => Promise<void>;
export declare const attackHandler: () => Promise<void>;
export declare const skillHandler: () => Promise<void>;
export declare const advancedSkillHandler: () => Promise<void>;
export declare const summonSpiritHandler: () => Promise<void>;
export declare const itemHandler: () => Promise<void>;
export declare const escapeHandler: () => Promise<void>;
export declare const deviceBattleHandler: () => Promise<void>;
export declare const deviceSkillHandler: () => Promise<void>;
export declare const deviceTargetHandler: () => Promise<void>;
export declare const combatDeviceStatusHandler: () => Promise<void>;
export declare const encounterHandler: (action: "avoid" | "persuade", title: string) => () => Promise<void>;
export declare const alchemyAllyHandler: () => Promise<void>;
export declare const hiddenCombatConfirmHandler: () => Promise<void>;
export declare const defendHandler: () => Promise<void>;
