import { Format } from 'alemonjs';
export declare const oddWorkshopFormat: (qqUserId: string, dialogue?: string) => Promise<Format>;
export declare const oddWorkshopHandler: () => Promise<void>;
export declare const oddWorkshopChatHandler: () => Promise<void>;
export declare const oddWorkshopTradeHandler: (action: "buy" | "sell") => () => Promise<void>;
export declare const oddWorkshopSellPageHandler: () => Promise<void>;
export declare const oddWorkshopSellSearchHandler: () => Promise<void>;
export declare const oddWorkshopSellItemHandler: () => Promise<void>;
export declare const deconstructorAboutHandler: () => Promise<void>;
export declare const deconstructorProfessionSelectHandler: () => Promise<void>;
export declare const acceptDeconstructorQuestHandler: () => Promise<void>;
export declare const claimDeconstructorQuestHandler: () => Promise<void>;
export declare const deconstructorProfessionFormat: (qqUserId: string) => Promise<Format>;
export declare const deconstructorFeatureHandler: (feature: "\u5206\u89E3" | "\u6784\u9020") => () => Promise<void>;
export declare const deconstructionPageHandler: () => Promise<void>;
export declare const deconstructionSearchHandler: () => Promise<void>;
export declare const constructionPageHandler: () => Promise<void>;
export declare const constructionSearchHandler: () => Promise<void>;
export declare const deconstructItemHandler: () => Promise<void>;
export declare const constructItemHandler: () => Promise<void>;
