import { Format } from 'alemonjs';
export declare const guildShopFormat: (text?: string, speaker?: string, continuingChat?: boolean) => Format;
export declare const guildShopHandler: () => Promise<void>;
export declare const shopBuyListHandler: () => Promise<void>;
export declare const shopSearchHandler: () => Promise<void>;
export declare const shopPurchaseHandler: () => Promise<void>;
export declare const shopSellListHandler: () => Promise<void>;
export declare const shopSellSearchHandler: () => Promise<void>;
export declare const shopSellHandler: () => Promise<void>;
export declare const shopChatHandler: () => Promise<void>;
