declare const _default: () => Promise<void>;
export default _default;
export declare const skillPageHandler: () => Promise<void>;
export declare const skillSearchHandler: () => Promise<void>;
export declare const passiveLinkHandler: () => Promise<void>;
export declare const skillInfusionHandler: () => Promise<void>;
export declare const skillDetailHandler: () => Promise<void>;
export declare const learnSkillHandler: () => Promise<void>;
export declare const skillShortcutHandler: () => Promise<void>;
export declare const upgradeSkillHandler: () => Promise<void>;
export declare const upgradeSpecializationHandler: () => Promise<void>;
export declare const upgradeAppraisalHandler: () => Promise<void>;
