import type { PoolConnection } from 'mysql2/promise';
import type { RuleUnit } from './combat-rule-registry';
import { type AchievementFact } from './achievement-events';
type Evidence = {
    damage: number;
    kills: string[];
    elements: string[];
    crit: boolean;
    dodged: boolean;
    shield: boolean;
    received: number;
    receivedHits: number;
    healed: number;
    lowHeal: boolean;
    cleansedDot?: boolean;
    interrupted?: boolean;
    brokeShield?: boolean;
    friendlyDamage?: boolean;
    receivedActions?: string[];
    playerSupport?: number;
    actualHpLost?: number;
    bossOpeningKnockout?: string;
    componentHits?: string[];
    defeatSequence?: string[];
    actionKinds?: string[];
    contributionActions?: string[];
    dotKills?: string[];
    normalAttackDamage?: boolean;
};
export declare const achievementBattleEvidence: (unit: RuleUnit) => Evidence;
export declare const achievementBattleAction: (unit: RuleUnit, kind: "attack" | "defend" | "support") => void;
export declare const achievementBattleContribution: (unit: RuleUnit, kind: "defend" | "support") => void;
export declare const achievementHit: (source: RuleUnit, target: RuleUnit, damage: number, element: string, absorbed: number, loss?: any) => void;
export declare const componentVictoryFacts: (evidence: Evidence, bossKeys: Set<string>) => AchievementFact[];
export declare const achievementCombatObserved: (c: PoolConnection, sessionId: string, members: Record<string, any>[]) => void;
export declare const achievementCombatVictory: (c: PoolConnection, sessionId: string, members: Record<string, any>[], targets: Record<string, any>[]) => Promise<void>;
export {};
