const advancedResourceDefinitions = {
    bulwark_guard: { professionCode: 'bulwark_guard', code: 'guard_stance', name: '守势', summary: '承受攻击、嘲讽与格挡会积攒；用于壁垒裁决。' },
    war_lord: { professionCode: 'war_lord', code: 'battle_fervor', name: '战意', summary: '命中敌人与压制受控目标会积攒；用于战旗与横扫。' },
    ironbreaker: { professionCode: 'ironbreaker', code: 'sunder_momentum', name: '裂势', summary: '暴击与命中破甲、易伤目标会积攒；用于处决。' },
    elementalist: { professionCode: 'elementalist', code: 'arcana', name: '奥能', summary: '施加异种元素印记、命中元素弱点会积攒；用于元素爆发。' },
    spirit_summoner: { professionCode: 'spirit_summoner', code: 'spirit_pact', name: '灵契', summary: '灵兽回应，以及队友受到治疗或壁垒时积攒；用于灵契超载。' },
    spellblade: { professionCode: 'spellblade', code: 'spell_edge', name: '法刃', summary: '物理技能以物攻+魔攻×35%为攻击基础，且不超过实际魔攻；交替使用魔法与物理技会积攒，用于破法回旋与决斗。' },
    nightblade: { professionCode: 'nightblade', code: 'opening', name: '破绽', summary: '暴击或攻击受控、易伤、破甲目标会积攒；用于割喉与终章。' },
    venomancer: { professionCode: 'venomancer', code: 'toxicity', name: '毒性', summary: '持续伤害结算、对中毒目标施加新状态会积攒；用于毒血引爆。' },
    trickster_ranger: { professionCode: 'trickster_ranger', code: 'chips', name: '筹码', summary: '追猎目标被命中、敌人被减速或束缚会积攒；用于烟幕与协猎。' },
    saint_healer: { professionCode: 'saint_healer', code: 'faith', name: '信念', summary: '救治低血队友、净化控制会积攒；用于群体急救。' },
    aegis_priest: { professionCode: 'aegis_priest', code: 'faith', name: '信念', summary: '壁垒承伤与守护转移会积攒；用于团队屏障。' },
    dawn_inquisitor: { professionCode: 'dawn_inquisitor', code: 'faith', name: '信念', summary: '光术命中暗蚀或驱散增益、队友获得祷言会积攒；用于审判。' }
};
const advancedSkillResourceRequirements = {
    bulwark_bastion_judgment: { professionCode: 'bulwark_guard', amount: 100 },
    warlord_triumph_banner: { professionCode: 'war_lord', amount: 50 },
    warlord_hundred_battle_sweep: { professionCode: 'war_lord', amount: 100 },
    ironbreaker_gap_execution: { professionCode: 'ironbreaker', amount: 60 },
    ironbreaker_steel_flash: { professionCode: 'ironbreaker', amount: 100 },
    elementalist_fourfold_resonance: { professionCode: 'elementalist', amount: 50 },
    elementalist_sky_sequence: { professionCode: 'elementalist', amount: 100 },
    summoner_returning_veil: { professionCode: 'spirit_summoner', amount: 50 },
    summoner_star_pact: { professionCode: 'spirit_summoner', amount: 100 },
    spellblade_spellbreak_whirl: { professionCode: 'spellblade', amount: 50 },
    spellblade_starfire_duel: { professionCode: 'spellblade', amount: 100 },
    nightblade_crescent_throat: { professionCode: 'nightblade', amount: 60 },
    nightblade_silent_finale: { professionCode: 'nightblade', amount: 100 },
    venomancer_venom_burst: { professionCode: 'venomancer', amount: 50 },
    venomancer_thousand_throat: { professionCode: 'venomancer', amount: 100 },
    ranger_guiding_smoke: { professionCode: 'trickster_ranger', amount: 50 },
    ranger_hundred_hunt: { professionCode: 'trickster_ranger', amount: 100 },
    saint_healer_resonant_mass: { professionCode: 'saint_healer', amount: 50 },
    saint_healer_revival_sanctuary: { professionCode: 'saint_healer', amount: 100 },
    aegis_luminous_echo: { professionCode: 'aegis_priest', amount: 50 },
    aegis_undying_dome: { professionCode: 'aegis_priest', amount: 100 },
    dawn_judgment_litany: { professionCode: 'dawn_inquisitor', amount: 50 },
    dawn_daybreak_decree: { professionCode: 'dawn_inquisitor', amount: 100 }
};
const advancedSkillDescriptions = {
    bulwark_shieldwall_advance: '115%物理伤害；令目标嘲讽2回合，自身获得12%减伤并获得20守势。被嘲讽的敌人会优先攻击盾卫。',
    bulwark_vicarious_guard: '为生命比例最低的队友施加2回合守护：其首次受到的单体伤害有35%转移给你；自身同时获得2回合20%伤害减免。按转移前伤害获得守势，单次最多30。',
    bulwark_immovable_mountain: '自身获得2回合35%减伤与20%控制抗性。本回合承受3次攻击后，下一次行动前以90%物理系数反击一次。',
    bulwark_bastion_judgment: '消耗100守势。对全体造成145%物理伤害；主目标额外受到60%伤害并被嘲讽，全队获得2回合15%减伤壁垒。',
    warlord_quake_command: '对全体造成105%物理伤害并减速20%持续2回合；每命中一个敌人获得15战意。',
    warlord_break_formation: '130%物理伤害并施加2回合破甲；下一次来自任意队友的技能命中该目标时额外造成12%伤害。',
    warlord_triumph_banner: '消耗50战意。全队获得2回合10%伤害提升与15%控制抗性；敌人不少于3名时，全队立刻回复8%最大生命。',
    warlord_hundred_battle_sweep: '消耗100战意。对全体造成170%物理伤害；每个带减速、束缚或眩晕的目标使其本次伤害额外+15%，最多+60%。',
    ironbreaker_armor_rend: '150%物理伤害并施加2回合破甲；目标原本已有破甲时，额外施加易伤。',
    ironbreaker_breaking_pursuit: '135%物理伤害；对带易伤或追猎的目标额外+35%，命中该条件时获得20裂势。',
    ironbreaker_gap_execution: '消耗60裂势。185%物理伤害；目标低于35%生命时额外+45%，击杀则返还本技能一半冷却。',
    ironbreaker_steel_flash: '消耗100裂势。245%物理伤害，不能暴击；清除目标全部易伤，每层使本次伤害额外+8%。',
    elementalist_cinderfrost_cycle: '火、冰自动交替的125%魔法伤害，并留下对应印记4回合；在已有异种印记的目标上首次补入新印记时+25奥能。冰命中火印记时附加25%减速(1)。',
    elementalist_storm_chain: '对全体造成105%雷系魔法伤害并留下雷印记4回合；目标已有的火、冰、风印记每种使其本次伤害+15%，最多+30%。首次将雷印记补入已有元素印记的目标时+25奥能（每次施法一次）。',
    elementalist_fourfold_resonance: '消耗50奥能，造成150%风系魔法伤害；目标已有的火、冰、雷印记每种使伤害+10%，最多+30%。刷新已有印记至4回合并加入风印记；首次以火、冰、雷补齐风印记时奥能充满。',
    elementalist_sky_sequence: '消耗100奥能。对全体造成145%风系魔法伤害，消耗全部元素印记；每种印记使本次伤害+10%，最多+40%。火→灼烧5%(2)、冰→减速25%(1)、风→失衡15%(1)、雷→破障8%(2，魔防降低)，不会造成硬控制。',
    summoner_contract_spirit: '延长场上全部存活契灵1回合。契灵是可被攻击的独立友方单位，会在自己的速度回合行动。',
    summoner_spirit_tether: '令场上全部存活契灵立即各行动一次，并获得20灵契。',
    summoner_returning_veil: '消耗50灵契。全队获得2回合10%减伤壁垒；场上有契灵时，额外净化每人一个可净化负面状态。',
    summoner_star_pact: '消耗100灵契，需场上至少1只存活契灵。令全部存活契灵立刻进行第1次超载行动，并在后续共完成3次超载行动：攻击灵改为范围攻击、治疗灵改为群体治疗与壁垒；每只灵完成第3次超载行动后退场。',
    spellblade_arcane_thrust: '战斗法师的物理技能以物攻+魔攻×35%为攻击基础，且不超过实际魔攻。近战判定的120%魔法伤害；上一行动为物理时额外+35%。施放魔法获得20法刃。',
    spellblade_phase_guard: '获得1回合25%减伤与20%速度；成功闪避一次攻击时额外获得30法刃。',
    spellblade_spellbreak_whirl: '消耗50法刃。对全体造成120%魔法伤害；带元素印记的目标额外获得易伤。',
    spellblade_starfire_duel: '消耗100法刃。对单体造成210%魔法伤害，并获得2回合20%减伤壁垒；击杀时重置相位格挡。',
    nightblade_shadow_mark: '造成105%物理伤害并施加3回合追猎；目标下一次受到你攻击时伤害+20%，并获得20破绽。',
    nightblade_gap_stab: '125%物理伤害；目标同时带追猎与易伤、破甲或控制时，以两段各85%的连刺结算并获得额外20破绽。',
    nightblade_crescent_throat: '消耗60破绽。175%物理伤害；目标低于40%生命时改为215%，并施加2回合40%降疗（受到的治疗量降低40%）。',
    nightblade_silent_finale: '消耗100破绽，只能对带追猎的目标使用。230%物理伤害；击杀返还50MP，并获得1回合50%减伤隐匿。',
    venomancer_serpent_kiss: '105%物理伤害并施加可叠加的3回合剧毒。普通目标每层每回合损失5%最大生命、最多5层；首领每层最多1.5%、最多3层有效。剧毒结算会为施加者提供毒性。',
    venomancer_corrosion_mist: '对全体造成90%魔法伤害，并施加2回合腐蚀：物防、魔防各降低8%；已中毒目标额外叠加一层剧毒。',
    venomancer_venom_burst: '消耗50毒性。165%魔法伤害，并立即结算目标剩余剧毒总伤害的60%（首领40%，单次最多首领最大生命的6%）；保留一层剧毒并刷新为1回合。',
    venomancer_thousand_throat: '消耗100毒性。160%暗系魔法伤害，令剧毒补至3层，并施加2回合60%降疗（首领30%）。',
    ranger_grapple_trap: '施加追猎与束缚；首领会将束缚降级为30%减速。钩索本体造成80%物理伤害。',
    ranger_weakness_survey: '100%物理伤害并施加2回合测绘：全队对该目标命中+15%、暴击+8%；自身获得20筹码。',
    ranger_guiding_smoke: '消耗50筹码。全队获得1回合20%闪避与15%减伤；敌方全体命中-15%。',
    ranger_hundred_hunt: '消耗100筹码，只能对带追猎目标使用。160%物理伤害后，本回合速度最高的另一名队友追加一次70%基础协同追击。',
    saint_healer_mending_prayer: '治疗生命最低队友90%魔攻+8%最大生命，并施加再生；目标低于50%生命时获得25信念。',
    saint_healer_absolution_hand: '净化生命最低队友最多两个可净化负面状态并治疗60%魔攻；若净化了控制，额外给予10%减伤壁垒并获得20信念。',
    saint_healer_resonant_mass: '消耗50信念。全队治疗65%魔攻+5%最大生命；生命低于40%的队友额外获得祷言。',
    saint_healer_revival_sanctuary: '消耗100信念。全队立即回复18%最大生命、净化一个负面状态并获得2回合再生；不能复活。',
    aegis_watch_bastion: '为生命最低队友提供2回合15%减伤壁垒与20%控制抗性。圣盾使施加的任意壁垒每名受护者每回合首次承伤时，施法者获得10信念。',
    aegis_shared_vow: '两名生命最低队友获得2回合20%减伤；队内有战士时，该战士获得10点对应专属资源。',
    aegis_luminous_echo: '消耗50信念。全队获得1回合10%减伤壁垒与再生；壁垒首次承伤后为其回复7%最大生命。',
    aegis_undying_dome: '消耗100信念。全队获得2回合20%减伤壁垒；期间每人可触发一次濒危不倒，生命保留为1。',
    dawn_morning_mark: '125%光系魔法伤害并施加晨星印记；目标下一次元素反应伤害提高20%。',
    dawn_exorcism_word: '135%光系魔法伤害，驱散目标一个可驱散增益或壁垒；成功时全队回复4%最大MP。',
    dawn_judgment_litany: '消耗50信念。165%光系魔法伤害并施加两层易伤；目标带暗性标记时额外净化全队一个负面状态。',
    dawn_daybreak_decree: '消耗100信念。对全体造成150%光系魔法伤害，逐个驱散一个增益；每次成功驱散都会为全队提供短暂壁垒。'
};
const advancedResourceForProfession = (professionCode) => professionCode ? advancedResourceDefinitions[professionCode] : undefined;
const advancedResourceRequirementForSkill = (skillCode) => advancedSkillResourceRequirements[skillCode];

export { advancedResourceDefinitions, advancedResourceForProfession, advancedResourceRequirementForSkill, advancedSkillDescriptions, advancedSkillResourceRequirements };
