import { type DispelAuthority } from './combat-dispel-policy';
import { type SkillSpecializationResult } from './skill-specialization';
import { type ResidentSkill } from './resident-skill.config';
export type RuleStatus = {
    code: string;
    value: number;
    until: number;
    source: string;
    debuff: boolean;
    stacks: number;
    legacyId?: number;
    data?: string;
    mechanism?: string;
};
export type RuleState = {
    statuses: RuleStatus[];
    memory: Record<string, string | number>;
    cast?: {
        code: string;
        skillId: number;
        target: string;
        paid: number;
        releaseTurn: number;
        cooldown: number;
        action?: unknown;
    };
};
export type RuleUnit = {
    key: string;
    name: string;
    side: string;
    level: number;
    boss: boolean;
    hp: number;
    hpMax: number;
    mp: number;
    mpMax: number;
    attack: number;
    magic: number;
    defense: number;
    magicDefense: number;
    accuracy: number;
    evasion: number;
    speed: number;
    crit: number;
    critResist: number;
    critDamage: number;
    critReduction: number;
    pierce: number;
    tenacity: number;
    state: RuleState;
    cooldowns: Record<string, unknown>;
    passives: string[];
    selected?: string;
    weaponsDifferent?: boolean;
    appraisal?: number;
    resistance: Record<string, number>;
    mastery: Record<string, number>;
    modifiers?: Record<string, number>;
    castSpecialization?: SkillSpecializationResult;
    passiveSpecializations?: Record<string, number>;
};
export type RuleHooks = {
    absorb: (unit: RuleUnit, damage: number) => Promise<number>;
    legacyEffects: (unit: RuleUnit) => RuleStatus[];
    removeLegacy: (id: number) => Promise<void>;
    updateLegacy?: (effect: RuleStatus) => Promise<void>;
    directMultiplier?: (source: RuleUnit, target: RuleUnit, element: string, magic: boolean, single: boolean, damageType: string) => number;
    extraAction: (unit: RuleUnit) => void;
    swapThreat: (a: RuleUnit, b: RuleUnit) => Promise<void>;
};
export declare const emptyRuleState: () => RuleState;
export declare const readRuleState: (value: unknown) => RuleState;
export declare const displayedRuleName: (state: RuleState, code: string, actual: string, turn: number, ownView: boolean) => string;
export declare const ruleStatusSummary: (state: RuleState, turn: number, ownView?: boolean) => string;
export declare const visibleResidentBuff: (state: RuleState, skillCode: string, turn: number) => boolean;
export declare const maskRuleBattleLog: (lines: string[], hiddenNames: string[], ownNames: string[]) => string[];
export declare const ruleManaCost: (state: RuleState, passives: string[], base: number, turn: number) => number;
export declare class CombatRules {
    units: RuleUnit[];
    turn: number;
    log: string[];
    hooks: RuleHooks;
    weather: string;
    sparLevelBand?: [number, number] | undefined;
    random: () => number;
    private expansionScale;
    constructor(units: RuleUnit[], turn: number, log: string[], hooks: RuleHooks, weather?: string, sparLevelBand?: [number, number] | undefined, random?: () => number);
    allies(unit: RuleUnit): RuleUnit[];
    enemies(unit: RuleUnit): RuleUnit[];
    pick<T>(items: T[]): T | undefined;
    lowest(items: RuleUnit[]): RuleUnit;
    status(unit: RuleUnit, code: string): RuleStatus | undefined;
    effects(unit: RuleUnit): RuleStatus[];
    value(unit: RuleUnit, code: string): number;
    passive(unit: RuleUnit, id: string): number;
    once(unit: RuleUnit, key: string, battle?: boolean): boolean;
    add(unit: RuleUnit, code: string, value: number, duration: number, source: RuleUnit, debuff?: boolean, data?: string): RuleStatus;
    remove(unit: RuleUnit, predicate: (effect: RuleStatus) => boolean, limit?: number): Promise<RuleStatus[]>;
    sameEffect(a: RuleStatus, b: RuleStatus): boolean;
    removeEffect(unit: RuleUnit, effect: RuleStatus): Promise<RuleStatus[]>;
    removeLayers(unit: RuleUnit, predicate: (effect: RuleStatus) => boolean, layers?: number): Promise<RuleStatus[]>;
    shieldValue(unit: RuleUnit): number;
    drainShield(unit: RuleUnit, amount: number): Promise<number>;
    consume(unit: RuleUnit, code: string): Promise<RuleStatus | undefined>;
    control(source: RuleUnit, target: RuleUnit, code: string, chance: number, duration: number): Promise<boolean>;
    beforeAction(unit: RuleUnit): Promise<boolean>;
    redirect(source: RuleUnit, target: RuleUnit, harmful: boolean): RuleUnit;
    speed(unit: RuleUnit): number;
    manaCost(unit: RuleUnit, base: number): number;
    paid(unit: RuleUnit, amount: number, skill: {
        category: string;
        cooldown: number;
    }): Promise<void>;
    healingMultiplier(source: RuleUnit, target: RuleUnit, equipment?: boolean): number;
    restore(source: RuleUnit, target: RuleUnit, hp: number, mp?: number, echo?: boolean): Promise<void>;
    rootEcho(source: RuleUnit): Promise<void>;
    shield(source: RuleUnit, target: RuleUnit, amount: number, duration: number): Promise<void>;
    supportSnapshot(unit: RuleUnit): {
        hp: number;
        mp: number;
        effects: {
            code: string;
            value: number;
            until: number;
            source: string;
            debuff: boolean;
            stacks: number;
            legacyId?: number;
            data?: string;
            mechanism?: string;
        }[];
    };
    echoSupport(source: RuleUnit, original: RuleUnit, before: ReturnType<CombatRules['supportSnapshot']>): Promise<void>;
    dispel(source: RuleUnit, target: RuleUnit, debuff: boolean, count?: number, filter?: (effect: RuleStatus) => boolean, authority?: DispelAuthority): Promise<RuleStatus[]>;
    reduceCooldown(unit: RuleUnit, utility?: boolean): void;
    elementFactor(source: RuleUnit, target: RuleUnit, element: string): number;
    secondary(source: RuleUnit, target: RuleUnit, damage: number, label: string, element?: string): Promise<void>;
    take(target: RuleUnit, damage: number): Promise<number>;
    incoming(source: RuleUnit, target: RuleUnit, raw: number, element: string, magic: boolean, skill: boolean, single?: boolean, legacyResolved?: boolean): Promise<number>;
    afterHit(source: RuleUnit, target: RuleUnit, damage: number, element: string, skill: boolean, absorbed?: number, extra?: boolean): Promise<void>;
    weatherElement(weather?: string): "水" | "火" | "风" | "冰" | "雷" | "";
    attackSetup(source: RuleUnit, target: RuleUnit, magic: boolean, skill: boolean, ranged?: boolean): Promise<{
        forceHit: boolean;
        powerFactor: number;
        hitBonus: number;
        hitFactor: number;
    }>;
    missed(source: RuleUnit, target: RuleUnit): Promise<void>;
    strike(source: RuleUnit, original: RuleUnit, power: number, element: string, magic: boolean, extra?: boolean, forceHit?: boolean, secondaryScale?: number, options?: {
        skill?: boolean;
        redirected?: boolean;
        single?: boolean;
        damageType?: string;
        ranged?: boolean;
        hitPenalty?: number;
        specializedPower?: boolean;
    }): Promise<boolean>;
    cast(source: RuleUnit, target: RuleUnit, skill: ResidentSkill, paid: number, elementChoice?: string, extra?: boolean): Promise<void>;
    addMechanism(source: RuleUnit, target: RuleUnit, code: string, value: number, key: string, debuff?: boolean): RuleStatus;
    releaseMechanism(key: string): Promise<void>;
    start(): void;
    end(): void;
}
export declare const registeredResidentActives: string[];
