import type { CombatRules, RuleUnit } from './combat-rule-registry';
import type { BossPhaseTransition } from './kingbeast.config';
export declare const regionalV2Codes: readonly ["gruen_mountainheart", "valk_forge_overseer"];
export type RegionalV2Code = typeof regionalV2Codes[number];
export declare const isRegionalV2: (code: unknown) => code is RegionalV2Code;
export type RegionalAction = 'attack' | 'damage_skill' | 'support_skill' | 'sustain' | 'defend';
export type FurnaceOrder = 'light' | 'heavy' | 'hold';
export declare const furnaceOrderNames: Record<FurnaceOrder, string>;
export type RegionalState = {
    version: 2;
    code: RegionalV2Code;
    phase: number;
    slot: number;
    pressure: number;
    heat: number;
    warningAt: number;
    unstableUntil: number;
    unstableReset: number;
    peeledTurn: number;
    reliefs: number;
    weight: Record<string, number>;
    weightTarget: string;
    rubble: Record<string, number>;
    orders: Record<string, FurnaceOrder>;
    previousOrders: Record<string, FurnaceOrder>;
    actions: Record<string, RegionalAction>;
    orderDue: number;
    foreman: string;
    foremanCursor: number;
    scars: Record<string, number>;
    obeyed: Record<string, boolean>;
    cancelProcess: boolean;
    lastCancel: boolean;
    breachUntil: number;
    fullFires: number;
    lastFullFire: boolean;
    overloadAt: number;
    revolt: boolean;
    revoltWon: boolean;
    revoltRetry: number;
    recastUsed: boolean;
    chainMarked: string[];
    collapseAt: number;
    rockArmorActive: boolean;
    reflectionTurn: number;
    reflectionTaken: Record<string, number>;
    mechanismHealTurn: number;
    mechanismHealed: number;
    scorchAppliedTurn: Record<string, number>;
    sealBlockedUntil: Record<string, number>;
    coldRound: number;
};
export declare const newRegionalState: (code: RegionalV2Code) => RegionalState;
export declare const readRegionalState: (cooldowns: Record<string, unknown>) => RegionalState | undefined;
export declare const pressureChange: (action: RegionalAction, weighted?: boolean) => number;
export declare const obeysFurnaceOrder: (order: FurnaceOrder, action: RegionalAction) => boolean;
export declare const nextFurnaceOrder: (previous: FurnaceOrder | undefined, canSkill: boolean, seed: number) => FurnaceOrder;
export declare const regionalIncomingFactor: (state: RegionalState, turn: number) => number;
export declare const regionalOutgoingFactor: (state: RegionalState, fire: boolean) => 1 | 1.15 | 1.3 | 0.9 | 1.2 | 1.35 | 0.85;
export declare const installRegionalV2Damage: (rules: CombatRules, battles: RegionalBossBattle[]) => void;
export declare const regionalHealingFactor: (rules: CombatRules, target: RuleUnit) => number;
export declare const regionalStateSummary: (state: RegionalState, names?: Record<string, string>, turn?: number) => string;
export type RegionalOrderResult = {
    effective: string[];
    rebels: string[];
    threshold: number;
    success: boolean;
    totalRevolt: boolean;
    wounds: Array<{
        key: string;
        fraction: number;
    }>;
};
export declare const settleFurnaceOrders: (state: RegionalState) => RegionalOrderResult;
export declare class RegionalBossBattle {
    readonly rules: CombatRules;
    readonly boss: RuleUnit;
    readonly announce: (event: BossPhaseTransition) => void;
    readonly canSkill: (unit: RuleUnit) => Promise<boolean>;
    readonly rescue: (unit: RuleUnit) => Promise<void>;
    readonly state: RegionalState;
    constructor(rules: CombatRules, boss: RuleUnit, code: RegionalV2Code, announce: (event: BossPhaseTransition) => void, canSkill?: (unit: RuleUnit) => Promise<boolean>, rescue?: (unit: RuleUnit) => Promise<void>);
    players(): RuleUnit[];
    beginRound(): void;
    event(code: string, title: string, description: string, kind?: 'phase' | 'chant'): void;
    mechanism(unit: RuleUnit, fraction: number, title: string): Promise<void>;
    healBoss(fraction: number, title: string, capped?: boolean): Promise<number>;
    reflectDirect(source: RuleUnit, actualHpDamage: number): Promise<void>;
    addScorch(unit: RuleUnit): void;
    addHealSeal(unit: RuleUnit): void;
    clearValkPressure(all?: boolean): Promise<void>;
    strike(targets: RuleUnit[], power: number, name: string, element?: string, magic?: boolean, factor?: number): Promise<Set<string>>;
    changePressure(delta: number): Promise<void>;
    playerAction(unit: RuleUnit, action: RegionalAction): Promise<void>;
    issueOrders(revolt?: boolean): Promise<void>;
    settleOrders(): Promise<void>;
    checkOverload(): Promise<void>;
    endRound(): Promise<void>;
    bossTurn(victim: RuleUnit): Promise<void>;
    gruenTurn(victim: RuleUnit): Promise<void>;
}
