import type { CombatRules, RuleUnit, RuleStatus } from './combat-rule-registry';
export type TalentAction = {
    serial: number;
    kind: string;
    single: boolean;
    damageType: string;
    ranged: boolean;
    extra: boolean;
    low: boolean;
    fire: boolean;
    prayer: boolean;
    core: boolean;
    hits: Record<string, number>;
    first: Record<string, boolean>;
    struck: Record<string, boolean>;
};
export type TalentBattleState = {
    clock: number;
    serial: number;
    action?: TalentAction;
    seen: string[];
    hit: string[];
    previousType?: string;
    chainRoot?: string;
    chain: number;
    attacks: number;
    normal: number;
    stacks: number;
    core: boolean;
    fireUsed?: boolean;
    fireUntil?: number;
    fireCost?: boolean;
    noAid?: boolean;
    poorBroken?: boolean;
    phase?: string;
    defend?: boolean;
    lastBasic?: {
        target: string;
        damage: number;
    };
    shadowedNormal?: number;
    stoneShield?: number;
    stoneGranted?: boolean;
    kills?: string[];
    leech?: number;
    startedFull?: boolean;
    completed?: number;
    enemyHpLoss?: number;
    delayed: {
        target: string;
        amount: number;
        due: number;
        label: string;
    }[];
    burns: {
        source: string;
        amount: number;
        ticks: number;
    }[];
};
export declare const talentState: (unit: RuleUnit) => TalentBattleState;
export declare const hasTalent: (unit: Pick<RuleUnit, "companion" | "opening">, id: string) => boolean;
export declare const talentBurnEffects: (unit: RuleUnit, turn: number) => RuleStatus[];
export declare const talentOpeningShield: (unit: RuleUnit) => void;
export declare const fireActive: (unit: RuleUnit) => boolean;
export declare const talentSupport: (source: RuleUnit, target: RuleUnit) => void;
export declare const talentReceiveHealing: (source: RuleUnit, target: RuleUnit) => 0 | 1 | 0.5;
export declare const talentSpellHealing: (source: RuleUnit, target?: RuleUnit) => number;
export declare const talentManaFactor: (unit: Pick<RuleUnit, "companion" | "opening">) => number;
export declare const talentBeginAction: (rules: CombatRules, unit: RuleUnit, extra?: boolean) => Promise<void>;
export declare const talentCommitAction: (unit: RuleUnit, kind: string, damageType?: string, single?: boolean, ranged?: boolean, prayer?: boolean) => void;
export declare const talentCanPaySkill: (unit: RuleUnit, harmful: boolean) => boolean;
export declare const talentPaySkill: (unit: RuleUnit, harmful: boolean) => void;
export declare const talentAttackAttempt: (source: RuleUnit, target: RuleUnit) => void;
export declare const talentDirectFactor: (source: RuleUnit, target: RuleUnit, magic: boolean, skill: boolean, _element: string) => number;
export declare const talentIncomingFactor: (source: RuleUnit, target: RuleUnit, element: string) => number;
export declare const talentHpDamage: (unit: RuleUnit, damage: number) => number;
export declare const talentRecordEnemyDamage: (source: RuleUnit | undefined, target: RuleUnit, loss: number) => void;
export declare const talentAfterHit: (rules: CombatRules, source: RuleUnit, target: RuleUnit, hpLoss: number, absorbed: number, element: string, extra: boolean, magic: boolean) => Promise<void>;
export declare const talentEndAction: (rules: CombatRules, unit: RuleUnit) => Promise<void>;
export declare const talentFinishFire: (unit: RuleUnit) => void;
export declare const installTalentHealingGuard: (unit: RuleUnit, row: Record<string, any>) => void;
