"""从已校验的逐题 TSV 和结果文案生成运行时题库。"""
from pathlib import Path
import json
import re
from hashlib import sha256

root = Path(__file__).resolve().parents[1]
names = {"体": "constitution", "精": "spirit", "力": "strength", "智": "intelligence", "敏": "agility", "感": "perception"}
cards = []
for source in sorted((root / "docs" / "问心事件题库素材").glob("[0-9][0-9]-*.tsv")):
    for line in source.read_text(encoding="utf-8").splitlines():
        title, prompt, *raw = line.split("|")
        code = f"WQ-{len(cards)+1:03d}"
        options = []
        for answer in raw:
            pair, body = answer.split(":", 1)
            favor, repel = pair.split(">", 1)
            options.append((favor, {"text": body, "favor": names[favor], "repel": names[repel]}))
        options.sort(key=lambda entry: sha256(f"{code}:{entry[0]}".encode("utf-8")).digest())
        cards.append({"code": code, "version": 3, "title": title, "prompt": prompt, "options": [option for _, option in options]})
assert len(cards) == 500 and all(len(card["options"]) == 6 for card in cards)

copy = (root / "docs" / "窥尘问心选择结果文案V1.md").read_text(encoding="utf-8")
normal = re.findall(r"^\| N\d\d \| (.*?) \|$", copy, re.M)
great = re.findall(r"^\| G\d\d \| (.*?) \|$", copy, re.M)
assert len(normal) == 24 and len(great) == 12

output = root / "src" / "game" / "heart-question-content.ts"
output.write_text(
    "// Generated by scripts/build-heart-question-data.py; edit the TSV / Markdown source.\n"
    "import type { AttributeKey } from './types';\n"
    "export type HeartOption = { text: string; favor: AttributeKey; repel: AttributeKey };\n"
    "export type HeartCard = { code: string; version: number; title: string; prompt: string; options: HeartOption[] };\n"
    "export const heartCards: HeartCard[] = " + json.dumps(cards, ensure_ascii=False, separators=(",", ":")) + ";\n"
    "export const normalHeartCopy: string[] = " + json.dumps(normal, ensure_ascii=False) + ";\n"
    "export const greatHeartCopy: string[] = " + json.dumps(great, ensure_ascii=False) + ";\n",
    encoding="utf-8",
)
print(f"generated {len(cards)} questions and {len(normal)+len(great)} result descriptions")
