/** Compiles the new seven maps only. Legacy snapshots and talent data are never overwritten. */
import { readFileSync, writeFileSync } from 'node:fs';
import { openingSevenScenes } from '../src/game/opening-seven.config';
import type { OpeningBranch, OpeningPage, OpeningRewardKind, OpeningRoute } from '../src/game/opening.types';

const read = (name: string) => readFileSync(`docs/${name}.md`, 'utf8').replace(/\r/g, '');
const source = read('六地图奇幻开局与神界世界线重设计V3');
const rewards = read('地图初始路线奖励与信物修订V4');
const regions: Record<string, string> = { S:'gravelwind_shore', D:'dark_forest_deep', H:'ridge_foothills', I:'rediron_pass', W:'mistalgae_marsh', B:'baina_town', Y:'world_tree' };
const bonus: Record<string,string> = { 'S01-A':'opening_tide_chest', 'D02-A':'opening_twilight_dew', 'I02-B':'opening_birthday_chest' };
const quoted = (text:string) => text.split('\n').filter(line=>line.startsWith('>')).map(line=>line.replace(/^> ?/,'')).join('\n').trim();
const pages = (title:string,text:string):OpeningPage[] => {
  const result:OpeningPage[]=[];
  for(const part of text.split(/\n\n+/).filter(Boolean)){
    const last=result.at(-1);
    if(last&&last.text.length+part.length<330)last.text+='\n\n'+part;
    else result.push({title,text:part});
  }
  return result;
};
const routes:OpeningRoute[]=[];
for(const match of source.matchAll(/^### ([SDHIWBY]\d{2}) (.+)\n([\s\S]*?)(?=^### |^## |$(?![\s\S]))/gm)){
  const [,code,title,text]=match;
  const scene=openingSevenScenes[code];
  if(!scene)throw new Error(`Missing scene ${code}`);
  const heads=[...text.matchAll(/^\*\*选择 ([ABC])｜([^*]+)\*\*/gm)];
  const end=text.indexOf('**归途与结算：**');
  const row=rewards.split('\n').find(line=>line.startsWith('| ')&&line.includes(` ${code} `));
  if(!row||end<0||heads.length<2)throw new Error(`Incomplete story ${code}`);
  const cells=row.split('|').map(v=>v.trim());
  const quest=text.slice(end).match(/完成《([^》]+)》/)?.[1];
  const name=text.match(/^【([^】]+)】 \[详情\]/m)?.[1];
  if(!quest||!name)throw new Error(`Missing quest/person ${code}`);
  const choices=heads.map((head,i)=>{
    const reward=cells[2+i],kind=reward.split('＋')[0] as OpeningRewardKind;
    if(!['路费','药袋','餐食','工料','手艺','照料'].includes(kind))throw new Error(`Unknown reward ${code}-${head[1]}`);
    return {code:head[1] as OpeningBranch,label:head[2],pages:pages(title,quoted(text.slice(head.index!+head[0].length,heads[i+1]?.index??end))),
      quest,task:'核对本次见闻与安全交接',farewell:scene.farewell,rewardCode:`opening_v4_${code.toLowerCase()}_${head[1].toLowerCase()}`,
      rewardName:reward,rewardUse:scene.lesson,future:scene.future,rewardKind:kind,bonusItem:bonus[`${code}-${head[1]}`]};
  });
  routes.push({code,version:4,title,region:regions[code[0]],destination:['D','B'].includes(code[0])?'baina_town':'world_tree',
    moveEntry:text.match(/^- \*\*首次移动：\*\*(.+)$/m)?.[1]??'',huntEntry:text.match(/^- \*\*首次寻怪：\*\*(.+)$/m)?.[1]??'',
    pages:pages(title,quoted(text.slice(0,heads[0].index))),choices,arrival:pages('灯火已经在前方',scene.arrival),
    person:{name,description:scene.description},lessonText:scene.lesson});
}
if(routes.length!==21||new Set(routes.map(r=>r.code)).size!==21||routes.reduce((n,r)=>n+r.choices.length,0)!==53
  ||routes.some(r=>!r.moveEntry||!r.huntEntry||!r.pages.length||r.choices.some(c=>!c.pages.length)))throw new Error('Incomplete seven-map scripts');
const output=`// Generated by scripts/generate-opening-content.ts. Legacy scripts remain in opening-content.generated.ts.\nimport type { OpeningRoute } from './opening.types';\nexport const generatedSevenOpeningRoutes: OpeningRoute[] = ${JSON.stringify(routes,null,2)};\n`;
const target='src/game/opening-seven.generated.ts';
if(process.argv.includes('--check')){
  if(readFileSync(target,'utf8')!==output)throw new Error('Seven-map scripts are stale; regenerate before release.');
}else writeFileSync(target,output);
console.log(JSON.stringify({routes:routes.length,branches:53,version:4,talentsUntouched:true}));
