import { logger, useEvent, useMessage, useRoute } from 'alemonjs';
import { combatAction, chooseTarget, encounterAction, explore, inventory, move } from '../game/adventure.service';
import { messageFormat } from '../game/message';

const fail = async (message: any, error: unknown, title = '操作失败') => message.send({ format: messageFormat(title, error instanceof Error ? error.message : '请稍后重试。') });

export const exploreHandler = async () => { const [event] = useEvent(); const [message] = useMessage(); try { const result = await explore(event.current.UserId); const targets = result.spawns.length ? `\n\n可选目标\n${result.spawns.map(s => `#${s.id} ${s.name} Lv.${s.level}｜HP ${s.current_hp}/${s.hp_max}`).join('\n')}\n\n发送 /目标 编号 进入战斗。` : ''; await message.send({ format: messageFormat('探索', result.text + targets) }); } catch (error) { logger.warn({ err: error }, 'explore failed'); await fail(message, error); } };
export const inventoryHandler = async () => { const [event] = useEvent(); const [message] = useMessage(); try { const bag = await inventory(event.current.UserId); await message.send({ format: messageFormat('冒险背包', `负重 ${bag.weight.toFixed(2)}/${bag.capacity}｜速度惩罚 -${bag.speedPenalty}\n当前速度 ${bag.speed}\n\n${bag.items.length ? bag.items.map(i => `${i.quick_slot ? `[道具${i.quick_slot}] ` : ''}${i.name} ×${i.quantity}（${i.weight}kg）`).join('\n') : '背包为空。'}`) }); } catch (error) { await fail(message, error); } };
export const moveHandler = async () => { const [event] = useEvent(); const [route] = useRoute(); const [message] = useMessage(); try { const result = await move(event.current.UserId, String(route.param('direction'))); await message.send({ format: messageFormat('队伍移动', `已向${route.param('direction')}移动。\n当前位置：(${result.pos_x}, ${result.pos_y}, ${result.pos_z})\n发送 /探索 搜寻附近目标。`) }); } catch (error) { await fail(message, error, '无法移动'); } };
export const targetHandler = async () => { const [event] = useEvent(); const [route] = useRoute(); const [message] = useMessage(); try { const result = await chooseTarget(event.current.UserId, Number(route.param('id'))); await message.send({ format: messageFormat('战斗开始', `目标：${result.spawn.name} Lv.${result.spawn.level}\n敌方 HP ${result.spawn.current_hp}/${result.spawn.hp_max}\n\n你的 HP ${result.playerHp}｜MP ${result.playerMp}\n\n行动：/攻击｜/技能 1-4｜/道具 1-4｜/逃跑`) }); } catch (error) { await fail(message, error, '无法锁定目标'); } };
const actionHandler = (action: 'attack' | 'skill' | 'item' | 'escape') => async () => { const [event] = useEvent(); const [route] = useRoute(); const [message] = useMessage(); try { const result = await combatAction(event.current.UserId, action, Number(route.param('slot')) || undefined); await message.send({ format: messageFormat(result.ended ? '战斗结算' : '战斗回合', result.log) }); } catch (error) { await fail(message, error, '战斗操作失败'); } };
export const attackHandler = actionHandler('attack'); export const skillHandler = actionHandler('skill'); export const itemHandler = actionHandler('item'); export const escapeHandler = actionHandler('escape');
export const encounterHandler = (action: 'sneak' | 'avoid' | 'persuade', title: string) => async () => { const [event] = useEvent(); const [route] = useRoute(); const [message] = useMessage(); try { const text = await encounterAction(event.current.UserId, Number(route.param('id')), action); await message.send({ format: messageFormat(title, text) }); } catch (error) { await fail(message, error, `${title}失败`); } };
