import { Format, logger, useEvent, useMessage, useRoute } from 'alemonjs';
import { combatAction, chooseTarget, encounterAction, explore, inventory, move } from '../game/adventure.service';
import { messageFormat } from '../game/message';

const fail = async (message: any, error: unknown, title = '操作失败') => message.send({ format: messageFormat(title, error instanceof Error ? error.message : '请稍后重试。') });
const moveButtons = () => Format.createButtonGroup()
  .addRow().addButton('上', '/移动 上', { type: 'command', autoEnter: true, style: 'blue' })
  .addRow().addButton('左', '/移动 左', { type: 'command', autoEnter: true }).addButton('右', '/移动 右', { type: 'command', autoEnter: true })
  .addRow().addButton('下', '/移动 下', { type: 'command', autoEnter: true, style: 'blue' })
  .addRow().addButton('背包', '/背包', { type: 'command', autoEnter: true }).addButton('面板', '/面板', { type: 'command', autoEnter: true });
const battleButtons = () => Format.createButtonGroup()
  .addRow().addButton('普攻', '/攻击', { type: 'command', autoEnter: true, style: 'blue' }).addButton('技能①', '/技能 1', { type: 'command', autoEnter: true, style: 'blue' }).addButton('技能②', '/技能 2', { type: 'command', autoEnter: true, style: 'blue' })
  .addRow().addButton('道具①', '/道具 1', { type: 'command', autoEnter: true }).addButton('逃跑', '/逃跑', { type: 'command', autoEnter: true });

export const exploreHandler = async () => { const [event] = useEvent(); const [message] = useMessage(); try { const result = await explore(event.current.UserId); const targets = result.spawns.length ? `\n\n可选目标\n${result.spawns.map(s => `#${s.id} ${s.name} Lv.${s.level}｜HP ${s.current_hp}/${s.hp_max}`).join('\n')}\n\n发送 /目标 编号 进入战斗。` : ''; await message.send({ format: messageFormat('探索', result.text + targets) }); } catch (error) { logger.warn({ err: error }, 'explore failed'); await fail(message, error); } };
export const inventoryHandler = async () => { const [event] = useEvent(); const [message] = useMessage(); try { const bag = await inventory(event.current.UserId); await message.send({ format: messageFormat('冒险背包', `负重 ${bag.weight.toFixed(2)}/${bag.capacity}｜速度惩罚 -${bag.speedPenalty}\n当前速度 ${bag.speed}\n\n${bag.items.length ? bag.items.map(i => `${i.equipped_slot ? `[已装备·${i.equipped_slot}] ` : i.quick_slot ? `[道具${i.quick_slot}] ` : ''}${i.name} ×${i.quantity}（${i.weight}kg）`).join('\n') : '背包为空。'}`) }); } catch (error) { await fail(message, error); } };
export const moveHandler = async () => { const [event] = useEvent(); const [route] = useRoute(); const [message] = useMessage(); try { const result = await move(event.current.UserId, String(route.param('direction'))); const position = `当前位置：(${result.character.pos_x}, ${result.character.pos_y}, ${result.character.pos_z})`; if (result.kind === 'battle') { await message.send({ format: Format.create().addMarkdown(Format.createMarkdown().addTitle('遭遇战').addText(`你踏入格子时遭遇 ${result.spawn.name} Lv.${result.spawn.level}！\n敌方 HP ${result.spawn.current_hp}/${result.spawn.hp_max}\n你的 HP ${result.playerHp}｜MP ${result.playerMp}\n${position}`)).addButtonGroup(battleButtons()) }); } else await message.send({ format: Format.create().addMarkdown(Format.createMarkdown().addTitle('格子奇遇').addText(`${result.text}\n${position}`)).addButtonGroup(moveButtons()) }); } catch (error) { await fail(message, error, '无法移动'); } };
export const targetHandler = async () => { const [event] = useEvent(); const [route] = useRoute(); const [message] = useMessage(); try { const result = await chooseTarget(event.current.UserId, Number(route.param('id'))); await message.send({ format: Format.create().addMarkdown(Format.createMarkdown().addTitle('战斗开始').addText(`目标：${result.spawn.name} Lv.${result.spawn.level}\n敌方 HP ${result.spawn.current_hp}/${result.spawn.hp_max}\n\n你的 HP ${result.playerHp}｜MP ${result.playerMp}`)).addButtonGroup(battleButtons()) }); } catch (error) { await fail(message, error, '无法锁定目标'); } };
const actionHandler = (action: 'attack' | 'skill' | 'item' | 'escape') => async () => { const [event] = useEvent(); const [route] = useRoute(); const [message] = useMessage(); try { const result = await combatAction(event.current.UserId, action, Number(route.param('slot')) || undefined); await message.send({ format: Format.create().addMarkdown(Format.createMarkdown().addTitle(result.ended ? '战斗结算' : '战斗回合').addText(result.log)).addButtonGroup(result.ended ? moveButtons() : battleButtons()) }); } catch (error) { await fail(message, error, '战斗操作失败'); } };
export const attackHandler = actionHandler('attack'); export const skillHandler = actionHandler('skill'); export const itemHandler = actionHandler('item'); export const escapeHandler = actionHandler('escape');
export const encounterHandler = (action: 'sneak' | 'avoid' | 'persuade', title: string) => async () => { const [event] = useEvent(); const [route] = useRoute(); const [message] = useMessage(); try { const text = await encounterAction(event.current.UserId, Number(route.param('id')), action); await message.send({ format: messageFormat(title, text) }); } catch (error) { await fail(message, error, `${title}失败`); } };
