import { Format, logger, useEvent, useMessage, useRoute } from 'alemonjs';
import { battleStatus, combatAction, chooseTarget, encounterAction, explore, inventory, move, moveTo, nearbyPoints } from '../game/adventure.service';
import { messageFormat } from '../game/message';
import { movedLocationText, outsidePanel, panelButtons } from './panel';

const fail = async (message: any, error: unknown, title = '操作失败') => message.send({ format: messageFormat(title, error instanceof Error ? error.message : '请稍后重试。') });
const moveButtons = panelButtons;
const battleButtons = () => Format.createButtonGroup()
  .addRow().addButton('普攻', '/攻击', { type: 'command', autoEnter: true, style: 'blue' }).addButton('技能①', '/技能 1', { type: 'command', autoEnter: true, style: 'blue' }).addButton('技能②', '/技能 2', { type: 'command', autoEnter: true, style: 'blue' })
  .addRow().addButton('道具①', '/道具 1', { type: 'command', autoEnter: true }).addButton('逃跑', '/逃跑', { type: 'command', autoEnter: true });
const encounterButtons = (spawnId: number) => Format.createButtonGroup()
  .addRow().addButton('战斗', `/目标 ${spawnId}`, { type: 'command', autoEnter: true, style: 'blue' }).addButton('说服', `/交涉 ${spawnId}`, { type: 'command', autoEnter: true }).addButton('躲避', `/躲避 ${spawnId}`, { type: 'command', autoEnter: true })
  .addRow().addButton('偷袭', `/偷袭 ${spawnId}`, { type: 'command', autoEnter: true }).addButton('继续移动', '/面板', { type: 'command', autoEnter: true });

export const exploreHandler = async () => { const [event] = useEvent(); const [message] = useMessage(); try { const result = await explore(event.current.UserId); const targets = result.spawns.length ? `\n\n可选目标\n${result.spawns.map(s => `#${s.id} ${s.name} Lv.${s.level}｜HP ${s.current_hp}/${s.hp_max}`).join('\n')}\n\n发送 /目标 编号 进入战斗。` : ''; await message.send({ format: messageFormat('探索', result.text + targets) }); } catch (error) { logger.warn({ err: error }, 'explore failed'); await fail(message, error); } };
export const inventoryHandler = async () => { const [event] = useEvent(); const [message] = useMessage(); try { const bag = await inventory(event.current.UserId); await message.send({ format: messageFormat('冒险背包', `负重 ${bag.weight.toFixed(2)}/${bag.capacity}｜速度惩罚 -${bag.speedPenalty}\n当前速度 ${bag.speed}\n\n${bag.items.length ? bag.items.map(i => `${i.equipped_slot ? `[已装备·${i.equipped_slot}] ` : i.quick_slot ? `[道具${i.quick_slot}] ` : ''}${i.name} ×${i.quantity}（${i.weight}kg）`).join('\n') : '背包为空。'}`) }); } catch (error) { await fail(message, error); } };
const movementPanel = async (qqUserId: string, description: string) => { const [bag, nearby] = await Promise.all([inventory(qqUserId), nearbyPoints(qqUserId)]); return outsidePanel('行动', movedLocationText(nearby.character), bag.movementSpeed, nearby.range, Number(nearby.character.pos_x), Number(nearby.character.pos_y), description, nearby.points); };
const showMoveResult = async (message: any, qqUserId: string, result: any) => { if (result.kind === 'encounter') { const first = result.spawns[0]; const targets = result.spawns.map((spawn: any) => `#${spawn.id} ${spawn.name} Lv.${spawn.level}｜HP ${spawn.current_hp}/${spawn.hp_max}`).join('\n'); await message.send({ format: (await movementPanel(qqUserId, `薄雾中出现了敌对生物：\n${targets}\n\n请选择如何应对；若有多个目标，可使用 /目标 编号 选择战斗对象。`)).addButtonGroup(encounterButtons(first.id)).addButtonGroup(panelButtons()) }); } else await message.send({ format: (await movementPanel(qqUserId, result.text)).addButtonGroup(panelButtons()) }); };
export const moveHandler = async () => { const [event] = useEvent(); const [route] = useRoute(); const [message] = useMessage(); try { await showMoveResult(message, event.current.UserId, await move(event.current.UserId, String(route.param('direction')))); } catch (error) { await fail(message, error, '无法移动'); } };
export const goToHandler = async () => { const [event] = useEvent(); const [route] = useRoute(); const [message] = useMessage(); try { await showMoveResult(message, event.current.UserId, await moveTo(event.current.UserId, Number(route.param('x')), Number(route.param('y')))); } catch (error) { await fail(message, error, '无法前往该位置'); } };
export const targetHandler = async () => { const [event] = useEvent(); const [route] = useRoute(); const [message] = useMessage(); try { const result = await chooseTarget(event.current.UserId, Number(route.param('id'))); await message.send({ format: Format.create().addMarkdown(Format.createMarkdown().addTitle('战斗开始').addText(`目标：${result.spawn.name} Lv.${result.spawn.level}\n敌方 HP ${result.spawn.current_hp}/${result.spawn.hp_max}\n\n你的 HP ${result.playerHp}｜MP ${result.playerMp}`)).addButtonGroup(battleButtons()) }); } catch (error) { await fail(message, error, '无法锁定目标'); } };
const actionHandler = (action: 'attack' | 'skill' | 'item' | 'escape') => async () => { const [event] = useEvent(); const [route] = useRoute(); const [message] = useMessage(); try { const result = await combatAction(event.current.UserId, action, Number(route.param('slot')) || undefined); await message.send({ format: Format.create().addMarkdown(Format.createMarkdown().addTitle(result.ended ? '战斗结算' : '战斗回合').addText(result.log)).addButtonGroup(result.ended ? moveButtons() : battleButtons()) }); } catch (error) { await fail(message, error, '战斗操作失败'); } };
export const attackHandler = actionHandler('attack'); export const skillHandler = actionHandler('skill'); export const itemHandler = actionHandler('item'); export const escapeHandler = actionHandler('escape');
export const encounterHandler = (action: 'sneak' | 'avoid' | 'persuade', title: string) => async () => { const [event] = useEvent(); const [route] = useRoute(); const [message] = useMessage(); try { const text = await encounterAction(event.current.UserId, Number(route.param('id')), action); try { await battleStatus(event.current.UserId); await message.send({ format: Format.create().addMarkdown(Format.createMarkdown().addTitle(title).addText(text)).addButtonGroup(battleButtons()) }); } catch { await message.send({ format: Format.create().addMarkdown(Format.createMarkdown().addTitle(title).addText(text)).addButtonGroup(moveButtons()) }); } } catch (error) { await fail(message, error, `${title}失败`); } };
