import { Format, useEvent, useMessage, useRoute } from 'alemonjs';
import { requireNpcAtCurrentPosition } from '../game/adventure.service';
import { acceptBlacksmithQuest, addForgeMaterial, blacksmithQuest, blacksmithWeapons, craftForgeEquipment, forgeState, fuseWeapon, fusionMaterials, refineWeapon, refinementMaterials, removeForgeMaterial, selectForgeCategory, selectForgeLevel, selectForgeSubtype } from '../game/blacksmith.service';
import { messageFormat } from '../game/message';

const requireBlacksmith = (qqUserId: string) => requireNpcAtCurrentPosition(qqUserId, 'blacksmith');
const buttons = () => Format.createButtonGroup().addRow().addButton('打造装备', '/打造装备', { type: 'command', autoEnter: true, style: 'blue' }).addButton('精炼', '/精炼', { type: 'command', autoEnter: true, style: 'blue' }).addButton('熔铸', '/熔铸', { type: 'command', autoEnter: true, style: 'blue' }).addRow().addButton('关于 锻造师', '/关于锻造师', { type: 'command', autoEnter: true, style: 'blue' }).addButton('离开铁匠铺', '/建筑离开 blacksmith', { type: 'command', autoEnter: true });
const effectText = (effect: Record<string, unknown>) => {
  const labels: Record<string, string> = { hpPct: '生命上限', mpPct: '魔力上限', physicalAttackPct: '物攻', magicAttackPct: '魔攻', physicalDefensePct: '物防', magicDefensePct: '魔防', accuracyPct: '命中', evasionPct: '闪避', speedPct: '速度', critRatePct: '暴击', magicDamagePct: '伤害提高' };
  return Object.entries(effect).filter(([key, value]) => labels[key] && Number(value)).map(([key, value]) => `${labels[key]}+${value}%`).join('｜') || '随机基础强化';
};
export const blacksmithFormat = () => Format.create().addMarkdown(Format.createMarkdown().addTitle('百纳镇·铁匠铺').addNewline().addNewline().addBlockquote('炉火映亮了铁砧，矮人铁匠正用厚布擦拭一柄刚打好的短剑。“把家伙事交给我吧，火候和力道都不会含糊。”')).addButtonGroup(buttons());
const weaponList = async (qqUserId: string, mode: 'refine' | 'fuse') => {
  const weapons = await blacksmithWeapons(qqUserId); const title = mode === 'refine' ? '精炼' : '熔铸'; const markdown = Format.createMarkdown().addTitle(title).addNewline().addNewline().addBlockquote(mode === 'refine' ? '选择一把武器放上铁砧。品质越高，精炼越困难；每次精炼有 3% 概率大成功。' : '选择一把武器放上熔炉。每 10 级获得 1 次熔铸机会，优秀及以上品质会额外增加机会。').addNewline().addNewline();
  if (!weapons.length) markdown.addText('背包中没有可操作的武器。');
  for (const weapon of weapons) markdown.addText(`【武器】${weapon.name} #${weapon.id}\n`).addBlockquote(`品质：${weapon.quality.toFixed(2)}%｜稀有度：${weapon.rarity}｜熔铸：${weapon.fusionCount}/${weapon.fusionLimit}`).addNewline().addButton('[放入]', { data: mode === 'refine' ? `/精炼放入 ${weapon.id}` : `/熔铸放入 ${weapon.id}`, autoEnter: false }).addNewline().addNewline();
  return Format.create().addMarkdown(markdown).addButtonGroup(buttons());
};
const materialList = async (qqUserId: string, mode: 'refine' | 'fuse', instanceId: number) => {
  const weapons = await blacksmithWeapons(qqUserId); const weapon = weapons.find(item => item.id === instanceId); if (!weapon) throw new Error('未找到该武器。');
  const materials: any[] = mode === 'refine' ? await refinementMaterials(qqUserId) : await fusionMaterials(qqUserId); const markdown = Format.createMarkdown().addTitle(mode === 'refine' ? '精炼·选择材料' : '熔铸·选择材料').addNewline().addNewline().addText(`已放入：【武器】${weapon.name}\n`).addBlockquote(`品质：${weapon.quality.toFixed(2)}%｜熔铸：${weapon.fusionCount}/${weapon.fusionLimit}`).addNewline().addNewline();
  if (!materials.length) markdown.addText(mode === 'refine' ? '没有可用的精炼材料。' : '背包中没有可用的熔铸材料。');
  for (const material of materials) { const detail = mode === 'refine' ? `本次提升 ${material.minGain}%～${material.maxGain}%` : effectText(material.effect); markdown.addText(`【${material.category}】${material.name}×${material.quantity} `).addButton('[使用]', { data: mode === 'refine' ? `/精炼执行 ${instanceId} ${material.id}` : `/熔铸执行 ${instanceId} ${material.id}`, autoEnter: false }).addNewline().addBlockquote(detail).addNewline(); }
  return Format.create().addMarkdown(markdown).addButtonGroup(buttons());
};
export const refineListHandler = async () => { const [event] = useEvent(); const [message] = useMessage(); try { await requireBlacksmith(event.current.UserId); await message.send({ format: await weaponList(event.current.UserId, 'refine') }); } catch (error) { await message.send({ format: messageFormat('无法精炼', error instanceof Error ? error.message : '请稍后重试。') }); } };
export const refinePutHandler = async () => { const [event] = useEvent(); const [route] = useRoute(); const [message] = useMessage(); try { await requireBlacksmith(event.current.UserId); await message.send({ format: await materialList(event.current.UserId, 'refine', Number(route.param('id'))) }); } catch (error) { await message.send({ format: messageFormat('无法放入武器', error instanceof Error ? error.message : '请稍后重试。') }); } };
export const refineExecuteHandler = async () => { const [event] = useEvent(); const [route] = useRoute(); const [message] = useMessage(); try { await requireBlacksmith(event.current.UserId); const result = await refineWeapon(event.current.UserId, Number(route.param('instanceId')), Number(route.param('materialId'))); const text = result.failed ? `【${result.name}】的精炼未能突破瓶颈。\n消耗【${result.material}】×1\n品质维持 ${result.oldQuality.toFixed(2)}%` : `【${result.name}】精炼${result.great ? '大成功！' : '成功！'}\n消耗【${result.material}】×1\n品质：${result.oldQuality.toFixed(2)}% → ${result.newQuality.toFixed(2)}%（+${result.gain.toFixed(2)}%）`; await message.send({ format: messageFormat('精炼结果', text) }); await message.send({ format: await materialList(event.current.UserId, 'refine', Number(route.param('instanceId'))) }); } catch (error) { await message.send({ format: messageFormat('精炼失败', error instanceof Error ? error.message : '请稍后重试。') }); } };
export const fuseListHandler = async () => { const [event] = useEvent(); const [message] = useMessage(); try { await requireBlacksmith(event.current.UserId); await message.send({ format: await weaponList(event.current.UserId, 'fuse') }); } catch (error) { await message.send({ format: messageFormat('无法熔铸', error instanceof Error ? error.message : '请稍后重试。') }); } };
export const fusePutHandler = async () => { const [event] = useEvent(); const [route] = useRoute(); const [message] = useMessage(); try { await requireBlacksmith(event.current.UserId); await message.send({ format: await materialList(event.current.UserId, 'fuse', Number(route.param('id'))) }); } catch (error) { await message.send({ format: messageFormat('无法放入武器', error instanceof Error ? error.message : '请稍后重试。') }); } };
export const fuseExecuteHandler = async () => { const [event] = useEvent(); const [route] = useRoute(); const [message] = useMessage(); try { await requireBlacksmith(event.current.UserId); const result = await fuseWeapon(event.current.UserId, Number(route.param('instanceId')), Number(route.param('materialId'))); await message.send({ format: messageFormat('熔铸完成', `【${result.name}】融入了【${result.material}】\n获得：${effectText(result.effect)}\n熔铸次数：${result.count}/${result.limit}`) }); await message.send({ format: await materialList(event.current.UserId, 'fuse', Number(route.param('instanceId'))) }); } catch (error) { await message.send({ format: messageFormat('熔铸失败', error instanceof Error ? error.message : '请稍后重试。') }); } };

const forgeFormat = async (qqUserId: string) => { const state = await forgeState(qqUserId); const markdown = Format.createMarkdown().addTitle('打造装备').addNewline().addNewline().addBlockquote('选择想打造的装备部位。首饰暂不开放打造。').addNewline().addNewline(); if (state.category) markdown.addText(`当前目标：${state.category}${state.subtype ? `·${state.subtype}` : ''}${state.level ? `·Lv.${state.level}` : ''}\n`); return Format.create().addMarkdown(markdown).addButtonGroup(Format.createButtonGroup().addRow().addButton('武器', '/打造部位 武器', { type: 'command', autoEnter: true, style: 'blue' }).addButton('头肩', '/打造部位 头肩', { type: 'command', autoEnter: true, style: 'blue' }).addButton('上装', '/打造部位 上装', { type: 'command', autoEnter: true, style: 'blue' }).addButton('腰部', '/打造部位 腰部', { type: 'command', autoEnter: true, style: 'blue' }).addRow().addButton('下装', '/打造部位 下装', { type: 'command', autoEnter: true, style: 'blue' }).addButton('脚部', '/打造部位 脚部', { type: 'command', autoEnter: true, style: 'blue' }).addButton('返回铁匠铺', '/铁匠铺', { type: 'command', autoEnter: true })); };
const forgeSubtypeFormat = async (qqUserId: string) => { const state = await forgeState(qqUserId); if (!state.category) throw new Error('请先选择打造部位。'); const types = state.category === '武器' ? ['长剑', '法杖', '匕首', '拳刃'] : ['布甲', '皮甲', '轻甲', '重甲', '板甲']; const buttons = Format.createButtonGroup().addRow(); for (const type of types) buttons.addButton(type, `/打造类型 ${type}`, { type: 'command', autoEnter: true, style: 'blue' }); buttons.addRow().addButton('返回打造', '/打造装备', { type: 'command', autoEnter: true }); return Format.create().addMarkdown(Format.createMarkdown().addTitle(`打造·${state.category}`).addNewline().addNewline().addBlockquote(state.category === '武器' ? '请选择武器类型。不同武器会拥有不同的基础属性倾向。' : '请选择护甲类型。布甲偏魔防与魔力，皮甲偏闪避，轻甲均衡，重甲与板甲偏防御和生命。')).addButtonGroup(buttons); };
const forgeLevelFormat = async (qqUserId: string) => { const state = await forgeState(qqUserId); if (!state.subtype) throw new Error('请先选择装备类型。'); const buttons = Format.createButtonGroup(); for (let base = 5; base <= 50; base += 25) { const row = buttons.addRow(); for (let level = base; level < base + 25 && level <= 50; level += 5) row.addButton(`Lv.${level}`, `/打造等级 ${level}`, { type: 'command', autoEnter: true, style: 'blue' }); } buttons.addRow().addButton('返回类型', '/打造装备', { type: 'command', autoEnter: true }); return Format.create().addMarkdown(Format.createMarkdown().addTitle(`打造·${state.category}·${state.subtype}`).addNewline().addNewline().addBlockquote('请选择欲打造装备的适应等级。等级越高，基础属性越高。')).addButtonGroup(buttons); };
const forgeMaterialsFormat = async (qqUserId: string) => { const state = await forgeState(qqUserId); if (!state.category || !state.subtype || !state.level) throw new Error('请完成部位、类型和等级选择。'); const markdown = Format.createMarkdown().addTitle('打造·放入材料').addNewline().addNewline().addText(`目标：${state.category}·${state.subtype}·Lv.${state.level}\n成功率：${state.success}%\n手续费：铜币×60\n`).addBlockquote(state.success >= 100 ? '成功率已满，可以开始打造。' : '成功率不足 100% 时，开始打造将需要二次确认；失败会损失全部投入材料。').addNewline().addNewline(); for (const material of state.materials) { markdown.addText(`【${material.category}】${material.name}×${material.quantity}（已放入${material.selected}） `).addButton('[放入]', { data: `/放入打造材料 ${material.id}`, autoEnter: false }); if (material.selected) markdown.addText(' ').addButton('[取出]', { data: `/取出打造材料 ${material.id}`, autoEnter: false }); markdown.addNewline().addBlockquote(`每份成功率+${material.contribution}%`).addNewline(); } return Format.create().addMarkdown(markdown).addButtonGroup(Format.createButtonGroup().addRow().addButton('开始打造', '/开始打造', { type: 'command', autoEnter: true, style: state.materials.some(item => item.selected) ? 'blue' : undefined }).addButton('重新选择', '/打造装备', { type: 'command', autoEnter: true })); };
export const forgeHandler = async () => { const [event] = useEvent(); const [message] = useMessage(); try { await requireBlacksmith(event.current.UserId); await message.send({ format: await forgeFormat(event.current.UserId) }); } catch (error) { await message.send({ format: messageFormat('无法打造', error instanceof Error ? error.message : '请稍后重试。') }); } };
export const forgeCategoryHandler = async () => { const [event] = useEvent(); const [route] = useRoute(); const [message] = useMessage(); try { await requireBlacksmith(event.current.UserId); await selectForgeCategory(event.current.UserId, String(route.param('category'))); await message.send({ format: await forgeSubtypeFormat(event.current.UserId) }); } catch (error) { await message.send({ format: messageFormat('选择失败', error instanceof Error ? error.message : '请稍后重试。') }); } };
export const forgeSubtypeHandler = async () => { const [event] = useEvent(); const [route] = useRoute(); const [message] = useMessage(); try { await requireBlacksmith(event.current.UserId); await selectForgeSubtype(event.current.UserId, String(route.param('subtype'))); await message.send({ format: await forgeLevelFormat(event.current.UserId) }); } catch (error) { await message.send({ format: messageFormat('选择失败', error instanceof Error ? error.message : '请稍后重试。') }); } };
export const forgeLevelHandler = async () => { const [event] = useEvent(); const [route] = useRoute(); const [message] = useMessage(); try { await requireBlacksmith(event.current.UserId); await selectForgeLevel(event.current.UserId, Number(route.param('level'))); await message.send({ format: await forgeMaterialsFormat(event.current.UserId) }); } catch (error) { await message.send({ format: messageFormat('选择失败', error instanceof Error ? error.message : '请稍后重试。') }); } };
export const forgeMaterialHandler = async () => { const [event] = useEvent(); const [route] = useRoute(); const [message] = useMessage(); try { await requireBlacksmith(event.current.UserId); await addForgeMaterial(event.current.UserId, Number(route.param('id'))); await message.send({ format: await forgeMaterialsFormat(event.current.UserId) }); } catch (error) { await message.send({ format: messageFormat('无法放入材料', error instanceof Error ? error.message : '请稍后重试。') }); } };
export const forgeMaterialRemoveHandler = async () => { const [event] = useEvent(); const [route] = useRoute(); const [message] = useMessage(); try { await requireBlacksmith(event.current.UserId); await removeForgeMaterial(event.current.UserId, Number(route.param('id'))); await message.send({ format: await forgeMaterialsFormat(event.current.UserId) }); } catch (error) { await message.send({ format: messageFormat('无法取出材料', error instanceof Error ? error.message : '请稍后重试。') }); } };
export const forgeMaterialListHandler = async () => { const [event] = useEvent(); const [message] = useMessage(); try { await requireBlacksmith(event.current.UserId); await message.send({ format: await forgeMaterialsFormat(event.current.UserId) }); } catch (error) { await message.send({ format: messageFormat('无法查看材料', error instanceof Error ? error.message : '请稍后重试。') }); } };
export const forgeStartHandler = (confirmed = false) => async () => { const [event] = useEvent(); const [message] = useMessage(); try { await requireBlacksmith(event.current.UserId); const result = await craftForgeEquipment(event.current.UserId, confirmed); if (result.needsConfirm) { await message.send({ format: Format.create().addMarkdown(Format.createMarkdown().addTitle('打造确认').addNewline().addNewline().addText(`当前成功率：${result.success}%\n失败将损失全部投入材料。是否仍要开始打造？`)).addButtonGroup(Format.createButtonGroup().addRow().addButton('确认打造', '/确认打造', { type: 'command', autoEnter: true, style: 'blue' }).addButton('继续加料', '/打造材料', { type: 'command', autoEnter: true })) }); return; } if (result.failed) { await message.send({ format: messageFormat('打造失败', `炉火熄灭前，材料没能凝成理想的形状。\n成功率：${result.success}%\n投入材料与铜币×60已消耗。`) }); return; } await message.send({ format: Format.create().addMarkdown(Format.createMarkdown().addTitle('打造成功').addNewline().addNewline().addText(`获得【${result.name}】\n稀有度：${result.rarity}\n品质：${result.quality.toFixed(2)}%\n`).addNewline().addBlockquote(effectText(result.effect))).addButtonGroup(Format.createButtonGroup().addRow().addButton('查看装备', `/装备详情 ${result.instanceId}`, { type: 'command', autoEnter: true, style: 'blue' }).addButton('返回铁匠铺', '/铁匠铺', { type: 'command', autoEnter: true })) }); } catch (error) { await message.send({ format: messageFormat('打造失败', error instanceof Error ? error.message : '请稍后重试。') }); } };
export const blacksmithAboutHandler = async () => { const [event] = useEvent(); const [message] = useMessage(); try { await requireBlacksmith(event.current.UserId); const quest = await blacksmithQuest(event.current.UserId); if (quest.status === 'none') { await message.send({ format: Format.create().addMarkdown(Format.createMarkdown().addTitle('关于 锻造师').addNewline().addNewline().addBlockquote('赫拉格是百纳镇经验最老到的锻造师之一。他相信金属并非冰冷的死物：每一块矿石、每一次落锤和每一道火候，都会决定武器最终能否回应持有者。成为锻造师后，你可以亲手打造装备、精炼品质，并以材料为装备熔铸新的力量。')).addButtonGroup(Format.createButtonGroup().addRow().addButton('选定副职业 锻造师', '/选择副职业 锻造师', { type: 'command', autoEnter: true, style: 'blue' })) }); return; } if (quest.status === 'completed') { await message.send({ format: Format.create().addMarkdown(Format.createMarkdown().addTitle('锻造师任务').addNewline().addNewline().addText(`活木：${quest.wood}/1\n兽核：${quest.core}/1\n任务已完成，回到赫拉格面前提交吧。`)).addButtonGroup(Format.createButtonGroup().addRow().addButton('提交任务', '/提交锻造师任务', { type: 'command', autoEnter: true, style: 'blue' })) }); return; } if (quest.status === 'claimed') { await message.send({ format: Format.create().addMarkdown(Format.createMarkdown().addTitle('关于 锻造师').addNewline().addNewline().addBlockquote('赫拉格点了点头：“火候记在心里，手上的锤子才不会骗人。你已经是锻造师了。”')).addButtonGroup(Format.createButtonGroup().addRow().addButton('查看 副职业', '/副职业', { type: 'command', autoEnter: true, style: 'blue' })) }); return; } await message.send({ format: Format.create().addMarkdown(Format.createMarkdown().addTitle('锻造师任务').addNewline().addNewline().addText(`收集活木与兽核各 1 份。\n活木：${quest.wood}/1\n兽核：${quest.core}/1`)).addButtonGroup(Format.createButtonGroup().addRow().addButton('任务栏', '/任务', { type: 'command', autoEnter: true, style: 'blue' }).addButton('放弃任务', '/铁匠铺', { type: 'command', autoEnter: true })) }); } catch (error) { await message.send({ format: messageFormat('无法交谈', error instanceof Error ? error.message : '请稍后重试。') }); } };
export const blacksmithProfessionSelectHandler = async () => { const [event] = useEvent(); const [message] = useMessage(); try { await requireBlacksmith(event.current.UserId); const quest = await blacksmithQuest(event.current.UserId); if (quest.status !== 'none') throw new Error('你已经接取或完成了锻造师任务。'); const markdown = Format.createMarkdown().addTitle('我想成为锻造师').addNewline().addNewline().addBlockquote('“我叫赫拉格。想学打铁，不必先会挥锤——先去替我找一块活木和一枚兽核，让我看看你有没有把材料带回来的本事。”').addNewline().addNewline().addText('发现新支线，是否接受？\n（只可拥有一个副职业，请谨慎决定）'); const buttons = Format.createButtonGroup().addRow().addButton('接受任务', '/接受锻造师任务', { type: 'command', autoEnter: true, style: 'blue' }).addButton('放弃任务', '/关于锻造师', { type: 'command', autoEnter: true }); await message.send({ format: Format.create().addMarkdown(markdown).addButtonGroup(buttons) }); } catch (error) { await message.send({ format: messageFormat('无法选择副职业', error instanceof Error ? error.message : '请稍后重试。') }); } };
export const acceptBlacksmithQuestHandler = async () => { const [event] = useEvent(); const [message] = useMessage(); try { await requireBlacksmith(event.current.UserId); await acceptBlacksmithQuest(event.current.UserId); await message.send({ format: messageFormat('接受任务', '已接受【副职业·锻造师入门】\n收集：活木×1、兽核×1\n可随时通过“任务”查看进度。') }); } catch (error) { await message.send({ format: messageFormat('接受失败', error instanceof Error ? error.message : '请稍后重试。') }); } };
export const claimBlacksmithQuestHandler = async () => { const [event] = useEvent(); const [message] = useMessage(); try { await requireBlacksmith(event.current.UserId); const { claimBlacksmithQuest } = await import('../game/blacksmith.service'); await claimBlacksmithQuest(event.current.UserId); await message.send({ format: Format.create().addMarkdown(Format.createMarkdown().addTitle('副职业转职成功').addNewline().addNewline().addBlockquote('赫拉格将活木投入炉火，又把兽核嵌进铁砧凹槽。火星在你手边炸开，他把锤柄递来：“从今天起，听铁的声音，也听你自己的声音。”')).addButtonGroup(Format.createButtonGroup().addRow().addButton('查看 副职业', '/副职业', { type: 'command', autoEnter: true, style: 'blue' })) }); } catch (error) { await message.send({ format: messageFormat('提交失败', error instanceof Error ? error.message : '请稍后重试。') }); } };
export const secondaryProfessionHandler = async () => { const [event] = useEvent(); const [message] = useMessage(); try { const quest = await blacksmithQuest(event.current.UserId); await message.send({ format: Format.create().addMarkdown(Format.createMarkdown().addTitle('副职业').addNewline().addNewline().addText(quest.status === 'claimed' ? '副职业：锻造师\n等级：Lv.1\n能力：可在百纳镇铁匠铺打造装备、精炼装备品质与熔铸材料属性。' : '尚未获得副职业。')).addButtonGroup(Format.createButtonGroup().addRow().addButton('前往铁匠铺', '/前往 -17 -123', { type: 'command', autoEnter: true, style: 'blue' })) }); } catch (error) { await message.send({ format: messageFormat('无法查看副职业', error instanceof Error ? error.message : '请稍后重试。') }); } };
