import { Router, logger, defineChildren, setCron, setInterval } from 'alemonjs';
import expose from './expose';
import koaRouter from 'koa-router';
import { getPool } from './database/pool';
import { settleDueTravels, spawnMonsters } from './game/adventure.service';
import { refreshBounties } from './game/bounty.service';
import { refreshShopStocks } from './game/shop-stock.service';
import { refreshDungeons } from './game/dungeon.service';
import { installGroupReplyMention } from './middleware/group-reply-mention';

installGroupReplyMention();

let settlingDueTravels = false;

const r = new koaRouter({
  prefix: '/api'
});

// 简单的 HTTP 路由示例 /app/api/ping
r.get('/ping', (ctx) => {
  ctx.body = 'pong';
});

const router = Router.create({
  events: ['message.create', 'private.message.create', 'interaction.create', 'private.interaction.create']
});

// 顶层登记群 group_openid；必须在具体命令处理前执行，私聊触发时才能找到公告目标群。
router.res({}, () => import('./middleware/remember-group-channel'));
router.res({}, () => import('./middleware/warrant-passive-notice'));

const appGroup = router.group({ // 精准规则匹配，复杂度 O1，稳定 且 几乎无损耗
  routeText: {
    prefixes: ['/', '#', '＃', '!', '！'],   // 允许使用的前缀
    stripPrefix: true, // 匹配时去掉前缀 
    allowBare: true  // 允许不使用前缀 
  }
})

appGroup.use("hello", () => import('./response/hello'))
appGroup.use("help", () => import('./response/help'))
appGroup.use('菜单', () => import('./response/help'))
appGroup.use('注销账户', () => import('./response/account-delete'))
appGroup.use({ path: '确认注销', schema: { usage: '/确认注销 <6位验证码>', args: [{ name: 'code', rules: [{ required: true, type: 'string' }] }] } }, () => import('./response/account-delete').then(module => ({ default: module.confirmAccountDeleteHandler })))
appGroup.use({ path: '确认注销账户', schema: { usage: '/确认注销账户 <6位验证码>', args: [{ name: 'code', rules: [{ required: true, type: 'string' }] }] } }, () => import('./response/account-delete').then(module => ({ default: module.confirmAccountDeleteHandler })))
appGroup.use('注册', () => import('./response/game-register'))
appGroup.use('注册 继续', () => import('./response/game-continue'))
appGroup.use('询问 这里是哪里', () => import('./response/ask-where'))
appGroup.use({ path: '选择去向', schema: { usage: '/选择去向 <天堂|异世界>', args: [{ name: 'destination', rules: [{ required: true, type: 'enum', enum: ['天堂', '异世界'] }] }] } }, () => import('./response/destination-select'))
appGroup.use({ path: '恩赐列表', schema: { usage: '/恩赐列表 <神器|神技>', args: [{ name: 'category', rules: [{ required: true, type: 'enum', enum: ['神器', '神技', '能力'] }] }] } }, () => import('./response/gift-catalog'))
appGroup.use({ path: '恩赐分页', schema: { usage: '/恩赐分页 <神器|神技> <页码> [关键词]', args: [{ name: 'category', rules: [{ required: true, type: 'enum', enum: ['神器', '神技', '能力'] }] }, { name: 'page', rules: [{ required: true, type: 'number', min: 1 }] }, { name: 'keyword', rules: [{ type: 'rest' }] }] } }, () => import('./response/gift-catalog').then(module => ({ default: module.giftPageHandler })))
appGroup.use({ path: '恩赐搜索', schema: { usage: '/恩赐搜索 <神器|神技> <关键词>', args: [{ name: 'category', rules: [{ required: true, type: 'enum', enum: ['神器', '神技', '能力'] }] }, { name: 'keyword', rules: [{ required: true, type: 'rest' }] }] } }, () => import('./response/gift-catalog').then(module => ({ default: module.giftSearchHandler })))
appGroup.use({ path: '选择恩赐', schema: { usage: '/选择恩赐 <代号>', args: [{ name: 'gift', rules: [{ required: true, type: 'string' }] }] } }, () => import('./response/gift-select'))
appGroup.use('冒险者登记', () => import('./response/adventurer-register'))
appGroup.use('角色', () => import('./response/character'))
appGroup.use('我', () => import('./response/character'))
appGroup.use('角色详情', () => import('./response/character').then(module => ({ default: module.characterDetailHandler })))
appGroup.use({ path: '改名', schema: { usage: '/改名 <新昵称>', args: [{ name: 'name', rules: [{ required: true }] }] } }, () => import('./response/change-name'))
appGroup.use({ path: '改性', schema: { usage: '/改性 <男|女>', args: [{ name: 'gender', rules: [{ required: true, type: 'enum', enum: ['男', '女'] }] }] } }, () => import('./response/change-gender'))
appGroup.use('地图', () => import('./response/map'))
appGroup.use('邮件', () => import('./response/mail'))
appGroup.use({ path: '邮件页', schema: { usage: '/邮件页 <页码> [关键词]', args: [{ name: 'page', rules: [{ required: true, type: 'number', min: 1 }] }, { name: 'keyword' }] } }, () => import('./response/mail').then(module => ({ default: module.mailPageHandler })))
appGroup.use({ path: '邮件搜索', schema: { usage: '/邮件搜索 <关键词>', args: [{ name: 'keyword', rules: [{ required: true }] }] } }, () => import('./response/mail').then(module => ({ default: module.mailSearchHandler })))
appGroup.use({ path: '查看邮件', schema: { usage: '/查看邮件 <邮件编号>', args: [{ name: 'id', rules: [{ required: true, type: 'number', min: 1 }] }] } }, () => import('./response/mail').then(module => ({ default: module.mailDetailHandler })))
appGroup.use({ path: '领取邮件', schema: { usage: '/领取邮件 <邮件编号>', args: [{ name: 'id', rules: [{ required: true, type: 'number', min: 1 }] }] } }, () => import('./response/mail').then(module => ({ default: module.mailClaimHandler })))
appGroup.use('一键领取邮件', () => import('./response/mail').then(module => ({ default: module.mailClaimAllHandler })))
appGroup.use({ path: '删除邮件', schema: { usage: '/删除邮件 <邮件编号>', args: [{ name: 'id', rules: [{ required: true, type: 'number', min: 1 }] }] } }, () => import('./response/mail').then(module => ({ default: module.mailDeleteHandler })))
appGroup.use('管理', () => import('./response/admin'))
appGroup.use('玩家数据核查', () => import('./response/admin').then(module => ({ default: module.playerAuditPanelHandler })))
appGroup.use('玩家操作', () => import('./response/admin').then(module => ({ default: module.playerOperationPanelHandler })))
appGroup.use({ path: '玩家核查', schema: { usage: '/玩家核查 <角色|背包|装备|技能|状态> @玩家', args: [{ name: 'type', rules: [{ required: true, type: 'enum', enum: ['角色', '背包', '装备', '技能', '状态'] }] }] } }, () => import('./response/admin').then(module => ({ default: module.playerAuditHandler })))
appGroup.use('清空背包', () => import('./response/admin').then(module => ({ default: module.clearPlayerBackpackHandler })))
appGroup.use('全服玩家核查', () => import('./response/admin').then(module => ({ default: module.allPlayersAuditHandler })))
appGroup.use('管理日志', () => import('./response/admin').then(module => ({ default: module.adminLogHandler })))
appGroup.use({ path: '管理日志页', schema: { usage: '/管理日志页 <页码> [人员|操作|时间] [筛选值]', args: [{ name: 'page', rules: [{ required: true, type: 'number', min: 1 }] }, { name: 'filter', rules: [{ type: 'enum', enum: ['人员', '操作', '时间'] }] }, { name: 'value' }] } }, () => import('./response/admin').then(module => ({ default: module.adminLogPageHandler })))
appGroup.use({ path: '管理日志搜索', schema: { usage: '/管理日志搜索 <关键词>', args: [{ name: 'keyword', rules: [{ required: true, type: 'rest' }] }] } }, () => import('./response/admin').then(module => ({ default: module.adminLogSearchHandler })))
appGroup.use({ path: '管理日志筛选', schema: { usage: '/管理日志筛选 <人员|操作|时间> <筛选值>', args: [{ name: 'filter', rules: [{ required: true, type: 'enum', enum: ['人员', '操作', '时间'] }] }, { name: 'value', rules: [{ required: true, type: 'rest' }] }] } }, () => import('./response/admin').then(module => ({ default: module.adminLogFilterHandler })))
appGroup.use('注销记录', () => import('./response/admin').then(module => ({ default: module.accountDeletionRecordHandler })))
appGroup.use({ path: '注销记录页', schema: { usage: '/注销记录页 <页码> [玩家|状态|时间] [筛选值]', args: [{ name: 'page', rules: [{ required: true, type: 'number', min: 1 }] }, { name: 'filter', rules: [{ type: 'enum', enum: ['玩家', '状态', '时间'] }] }, { name: 'value' }] } }, () => import('./response/admin').then(module => ({ default: module.accountDeletionRecordPageHandler })))
appGroup.use({ path: '注销记录搜索', schema: { usage: '/注销记录搜索 <关键词>', args: [{ name: 'keyword', rules: [{ required: true, type: 'rest' }] }] } }, () => import('./response/admin').then(module => ({ default: module.accountDeletionRecordSearchHandler })))
appGroup.use({ path: '注销记录筛选', schema: { usage: '/注销记录筛选 <玩家|状态|时间> <筛选值>', args: [{ name: 'filter', rules: [{ required: true, type: 'enum', enum: ['玩家', '状态', '时间'] }] }, { name: 'value', rules: [{ required: true, type: 'rest' }] }] } }, () => import('./response/admin').then(module => ({ default: module.accountDeletionRecordFilterHandler })))
appGroup.use({ path: '恢复注销账号', schema: { usage: '/恢复注销账号 <记录编号>', args: [{ name: 'id', rules: [{ required: true, type: 'number', min: 1 }] }] } }, () => import('./response/admin').then(module => ({ default: module.restoreDeletedAccountHandler })))
appGroup.use({ path: '确认覆盖恢复', schema: { usage: '/确认覆盖恢复 <记录编号>', args: [{ name: 'id', rules: [{ required: true, type: 'number', min: 1 }] }] } }, () => import('./response/admin').then(module => ({ default: module.overwriteRestoreDeletedAccountHandler })))
appGroup.use('BOSS管理', () => import('./response/admin').then(module => ({ default: module.bossManagementHandler })))
appGroup.use('迷宫管理', () => import('./response/admin').then(module => ({ default: module.dungeonManagementHandler })))
appGroup.use('重建迷宫', () => import('./response/admin').then(module => ({ default: module.rebuildDungeonHandler })))
appGroup.use('BOSS词条说明', () => import('./response/boss-trait'))
appGroup.use({ path: 'BOSS刷新', schema: { usage: '/BOSS刷新 <Boss代号>', args: [{ name: 'code', rules: [{ required: true }] }] } }, () => import('./response/admin').then(module => ({ default: module.bossSpawnHandler })))
appGroup.use({ path: 'BOSS消灭', schema: { usage: '/BOSS消灭 <Boss代号>', args: [{ name: 'code', rules: [{ required: true }] }] } }, () => import('./response/admin').then(module => ({ default: module.bossDefeatHandler })))
appGroup.use({ path: 'BOSS上赏', schema: { usage: '/BOSS上赏 <Boss代号>', args: [{ name: 'code', rules: [{ required: true }] }] } }, () => import('./response/admin').then(module => ({ default: module.bossBountyHandler })))
appGroup.use({ path: '管理员登录', schema: { usage: '/管理员登录 <密码>', args: [{ name: 'password', rules: [{ required: true }] }] } }, () => import('./response/admin').then(module => ({ default: module.ownerLoginHandler })))
appGroup.use('给予权限', () => import('./response/admin').then(module => ({ default: module.grantAdministratorHandler })))
appGroup.use({ path: '撤销权限', schema: { usage: '/撤销权限 <QID> 或 @玩家', args: [{ name: 'qq' }] } }, () => import('./response/admin').then(module => ({ default: module.revokeAdministratorHandler })))
appGroup.use('查看权限', () => import('./response/admin').then(module => ({ default: module.permissionListHandler })))
appGroup.use({ path: '管理员命令 邮件发放', schema: { usage: '/管理员命令 邮件发放 <个人|全服>', args: [{ name: 'scope', rules: [{ required: true, type: 'enum', enum: ['个人', '全服'] }] }] } }, () => import('./response/admin').then(module => ({ default: module.adminMailTargetHandler })))
appGroup.use('管理员邮件 切换全服', () => import('./response/admin').then(module => ({ default: module.switchMailScopeHandler })))
appGroup.use('管理员邮件 添加收件人', () => import('./response/admin').then(module => ({ default: module.addRecipientHandler })))
appGroup.use({ path: '管理员邮件 添加昵称', schema: { usage: '/管理员邮件 添加昵称 <昵称>', args: [{ name: 'name', rules: [{ required: true, type: 'rest' }] }] } }, () => import('./response/admin').then(module => ({ default: module.addRecipientNameHandler })))
appGroup.use({ path: '管理员邮件 删除收件人', schema: { usage: '/管理员邮件 删除收件人 <QID>', args: [{ name: 'qq', rules: [{ required: true }] }] } }, () => import('./response/admin').then(module => ({ default: module.removeRecipientHandler })))
appGroup.use({ path: '管理员邮件 编辑内容', schema: { usage: '/管理员邮件 编辑内容 <内容>', args: [{ name: 'content', rules: [{ required: true, type: 'rest' }] }] } }, () => import('./response/admin').then(module => ({ default: module.updateContentHandler })))
appGroup.use('管理员邮件 清空内容', () => import('./response/admin').then(module => ({ default: module.clearContentHandler })))
appGroup.use({ path: '管理员邮件 编辑标题', schema: { usage: '/管理员邮件 编辑标题 <标题>', args: [{ name: 'title', rules: [{ required: true, type: 'rest' }] }] } }, () => import('./response/admin').then(module => ({ default: module.updateTitleHandler })))
appGroup.use('管理员邮件 清空标题', () => import('./response/admin').then(module => ({ default: module.clearTitleHandler })))
appGroup.use({ path: '管理员邮件 添加附件ID', schema: { usage: '/管理员邮件 添加附件ID <物品ID> [数量]', args: [{ name: 'item', rules: [{ required: true }] }, { name: 'quantity', rules: [{ type: 'number', min: 1 }] }] } }, () => import('./response/admin').then(module => ({ default: module.addAttachmentHandler })))
appGroup.use({ path: '管理员邮件 添加附件名称', schema: { usage: '/管理员邮件 添加附件名称 <名称> [数量]', args: [{ name: 'item', rules: [{ required: true }] }, { name: 'quantity', rules: [{ type: 'number', min: 1 }] }] } }, () => import('./response/admin').then(module => ({ default: module.addAttachmentHandler })))
appGroup.use({ path: '管理员邮件 修改附件数量', schema: { usage: '/管理员邮件 修改附件数量 <物品ID> <数量>', args: [{ name: 'id', rules: [{ required: true, type: 'number', min: 1 }] }, { name: 'quantity', rules: [{ required: true, type: 'number', min: 1 }] }] } }, () => import('./response/admin').then(module => ({ default: module.updateAttachmentQuantityHandler })))
appGroup.use({ path: '管理员邮件 删除附件', schema: { usage: '/管理员邮件 删除附件 <物品ID>', args: [{ name: 'id', rules: [{ required: true, type: 'number', min: 1 }] }] } }, () => import('./response/admin').then(module => ({ default: module.removeAttachmentHandler })))
appGroup.use('管理员邮件 继续编辑', () => import('./response/admin').then(module => ({ default: module.continueEditHandler })))
appGroup.use('管理员邮件 暂存编辑', () => import('./response/admin').then(module => ({ default: module.stashEditHandler })))
appGroup.use('管理员邮件 退出编辑', () => import('./response/admin').then(module => ({ default: module.discardEditHandler })))
appGroup.use('管理员邮件 发送', () => import('./response/admin').then(module => ({ default: module.previewEditHandler })))
appGroup.use('管理员邮件 确认发放', () => import('./response/admin').then(module => ({ default: module.confirmEditHandler })))
appGroup.use('面板', () => import('./response/panel'))
appGroup.use({ path: '地图标识', schema: { usage: '/地图标识 <折叠|显示>', args: [{ name: 'state', rules: [{ required: true, type: 'enum', enum: ['折叠', '显示'] }] }] } }, () => import('./response/panel').then(module => ({ default: module.mapLandmarkVisibilityHandler })))
appGroup.use({ path: '感知内目标', schema: { usage: '/感知内目标 <隐藏玩家|显示玩家>', args: [{ name: 'state', rules: [{ required: true, type: 'enum', enum: ['隐藏玩家', '显示玩家'] }] }] } }, () => import('./response/panel').then(module => ({ default: module.nearbyPlayersVisibilityHandler })))
appGroup.use('战斗信息', () => import('./response/battle-info'))
appGroup.use('探索', () => import('./response/explore'))
appGroup.use({ path: '背包', schema: { usage: '/背包 [装备|道具|材料]', args: [{ name: 'category', rules: [{ type: 'enum', enum: ['装备', '道具', '材料'] }] }] } }, () => import('./response/inventory'))
appGroup.use({ path: '背包分页', schema: { usage: '/背包分页 <装备|道具|材料> <页码> [关键词]', args: [{ name: 'category', rules: [{ required: true, type: 'enum', enum: ['装备', '道具', '材料'] }] }, { name: 'page', rules: [{ required: true, type: 'number', min: 1 }] }, { name: 'keyword', rules: [{ type: 'rest' }] }] } }, () => import('./response/inventory').then(module => ({ default: module.inventoryPageHandler })))
appGroup.use({ path: '背包搜索', schema: { usage: '/背包搜索 <装备|道具|材料> <关键词>', args: [{ name: 'category', rules: [{ required: true, type: 'enum', enum: ['装备', '道具', '材料'] }] }, { name: 'keyword', rules: [{ required: true, type: 'rest' }] }] } }, () => import('./response/inventory').then(module => ({ default: module.inventorySearchHandler })))
appGroup.use({ path: '背包分类', schema: { usage: '/背包分类 <装备|道具|材料> <子分类> [页码] [关键词]', args: [{ name: 'category', rules: [{ required: true, type: 'enum', enum: ['装备', '道具', '材料'] }] }, { name: 'subcategory', rules: [{ required: true }] }, { name: 'page', rules: [{ type: 'number', min: 1 }] }, { name: 'keyword', rules: [{ type: 'rest' }] }] } }, () => import('./response/inventory').then(module => ({ default: module.inventorySubcategoryHandler })))
appGroup.use({ path: '背包分类搜索', schema: { usage: '/背包分类搜索 <装备|道具|材料> <子分类> <关键词>', args: [{ name: 'category', rules: [{ required: true, type: 'enum', enum: ['装备', '道具', '材料'] }] }, { name: 'subcategory', rules: [{ required: true }] }, { name: 'keyword', rules: [{ required: true, type: 'rest' }] }] } }, () => import('./response/inventory').then(module => ({ default: module.inventorySubcategorySearchHandler })))
appGroup.use({ path: '丢弃材料', schema: { usage: '/丢弃材料 <物品编号> [数量]', args: [{ name: 'id', rules: [{ required: true, type: 'number', min: 1 }] }, { name: 'quantity', rules: [{ type: 'number', min: 1 }] }] } }, () => import('./response/inventory').then(module => ({ default: module.discardMaterialHandler })))
appGroup.use('异械', () => import('./response/inventory').then(module => ({ default: module.deviceHandler })))
appGroup.use({ path: '异械分页', schema: { usage: '/异械分页 <页码> [关键词]', args: [{ name: 'page', rules: [{ required: true, type: 'number', min: 1 }] }, { name: 'keyword', rules: [{ type: 'rest' }] }] } }, () => import('./response/inventory').then(module => ({ default: module.devicePageHandler })))
appGroup.use({ path: '异械搜索', schema: { usage: '/异械搜索 <关键词>', args: [{ name: 'keyword', rules: [{ required: true, type: 'rest' }] }] } }, () => import('./response/inventory').then(module => ({ default: module.deviceSearchHandler })))
appGroup.use({ path: '异械生效', schema: { usage: '/异械生效 <装备编号>', args: [{ name: 'id', rules: [{ required: true, type: 'number', min: 1 }] }] } }, () => import('./response/inventory').then(module => ({ default: module.activateDeviceHandler })))
appGroup.use({ path: '异械解除', schema: { usage: '/异械解除 <装备编号>', args: [{ name: 'id', rules: [{ required: true, type: 'number', min: 1 }] }] } }, () => import('./response/inventory').then(module => ({ default: module.deactivateDeviceHandler })))
appGroup.use('道具配置', () => import('./response/inventory').then(module => ({ default: module.quickItemConfigHandler })))
appGroup.use({ path: '道具配置分页', schema: { usage: '/道具配置分页 <页码> [关键词]', args: [{ name: 'page', rules: [{ required: true, type: 'number', min: 1 }] }, { name: 'keyword', rules: [{ type: 'rest' }] }] } }, () => import('./response/inventory').then(module => ({ default: module.quickItemConfigPageHandler })))
appGroup.use({ path: '道具配置筛选', schema: { usage: '/道具配置筛选 <关键词>', args: [{ name: 'keyword', rules: [{ required: true, type: 'rest' }] }] } }, () => import('./response/inventory').then(module => ({ default: module.quickItemConfigSearchHandler })))
appGroup.use({ path: '道具快捷', schema: { usage: '/道具快捷 <物品编号>', args: [{ name: 'id', rules: [{ required: true, type: 'number', min: 1 }] }] } }, () => import('./response/inventory').then(module => ({ default: module.quickItemToggleHandler })))
appGroup.use({ path: '道具配置选择', schema: { usage: '/道具配置选择 <栏位> [页码] [关键词]', args: [{ name: 'slot', rules: [{ required: true, type: 'number', min: 1, max: 4 }] }, { name: 'page', rules: [{ type: 'number', min: 1 }] }, { name: 'keyword', rules: [{ type: 'rest' }] }] } }, () => import('./response/inventory').then(module => ({ default: module.quickItemChoiceHandler })))
appGroup.use({ path: '道具配置搜索', schema: { usage: '/道具配置搜索 <栏位> <关键词>', args: [{ name: 'slot', rules: [{ required: true, type: 'number', min: 1, max: 4 }] }, { name: 'keyword', rules: [{ required: true, type: 'rest' }] }] } }, () => import('./response/inventory').then(module => ({ default: module.quickItemSearchHandler })))
appGroup.use({ path: '道具配置设置', schema: { usage: '/道具配置设置 <栏位> <物品编号>', args: [{ name: 'slot', rules: [{ required: true, type: 'number', min: 1, max: 4 }] }, { name: 'id', rules: [{ required: true, type: 'number', min: 1 }] }] } }, () => import('./response/inventory').then(module => ({ default: module.quickItemSetHandler })))
appGroup.use({ path: '道具配置取消', schema: { usage: '/道具配置取消 <栏位>', args: [{ name: 'slot', rules: [{ required: true, type: 'number', min: 1, max: 4 }] }] } }, () => import('./response/inventory').then(module => ({ default: module.quickItemClearHandler })))
appGroup.use('图鉴', () => import('./response/codex'))
appGroup.use({ path: '图鉴列表', schema: { usage: '/图鉴列表 <装备|道具|材料|怪物|技能> [子分类]', args: [{ name: 'kind', rules: [{ required: true, type: 'enum', enum: ['装备', '道具', '材料', '怪物', '技能'] }] }, { name: 'category' }] } }, () => import('./response/codex').then(module => ({ default: module.codexListHandler })))
appGroup.use({ path: '图鉴分页', schema: { usage: '/图鉴分页 <分类> <子分类> <页码> [关键词]', args: [{ name: 'kind', rules: [{ required: true, type: 'enum', enum: ['装备', '道具', '材料', '怪物', '技能'] }] }, { name: 'category', rules: [{ required: true }] }, { name: 'page', rules: [{ required: true, type: 'number', min: 1 }] }, { name: 'keyword', rules: [{ type: 'rest' }] }] } }, () => import('./response/codex').then(module => ({ default: module.codexPageHandler })))
appGroup.use({ path: '图鉴搜索', schema: { usage: '/图鉴搜索 <分类> <关键词>', args: [{ name: 'kind', rules: [{ required: true, type: 'enum', enum: ['装备', '道具', '材料', '怪物', '技能'] }] }, { name: 'keyword', rules: [{ required: true, type: 'rest' }] }] } }, () => import('./response/codex').then(module => ({ default: module.codexSearchHandler })))
appGroup.use({ path: '物品图鉴', schema: { usage: '/物品图鉴 <物品ID>', args: [{ name: 'id', rules: [{ required: true, type: 'number', min: 1 }] }] } }, () => import('./response/item-codex'))
appGroup.use({ path: '装备详情', schema: { usage: '/装备详情 <装备编号>', args: [{ name: 'id', rules: [{ required: true, type: 'number', min: 1 }] }] } }, () => import('./response/equipment-detail'))
appGroup.use({ path: '卸下装备', schema: { usage: '/卸下装备 <部位>', args: [{ name: 'slot', rules: [{ required: true, type: 'enum', enum: ['weapon', 'offhand', 'shoulder', 'upper', 'waist', 'lower', 'feet', 'necklace', 'bracelet', 'ring'] }] }] } }, () => import('./response/equipment').then(module => ({ default: module.unequipHandler })))
appGroup.use({ path: '选择装备', schema: { usage: '/选择装备 <部位>', args: [{ name: 'slot', rules: [{ required: true, type: 'enum', enum: ['weapon', 'offhand', 'shoulder', 'upper', 'waist', 'lower', 'feet', 'necklace', 'bracelet', 'ring'] }] }] } }, () => import('./response/equipment').then(module => ({ default: module.chooseEquipmentHandler })))
appGroup.use({ path: '穿戴装备', schema: { usage: '/穿戴装备 <部位> <装备编号>', args: [{ name: 'slot', rules: [{ required: true, type: 'enum', enum: ['weapon', 'offhand', 'shoulder', 'upper', 'waist', 'lower', 'feet', 'necklace', 'bracelet', 'ring'] }] }, { name: 'id', rules: [{ required: true, type: 'number', min: 1 }] }] } }, () => import('./response/equipment').then(module => ({ default: module.equipHandler })))
appGroup.use('装备', () => import('./response/equipment'))
appGroup.use({ path: '技能列表', schema: { usage: '/技能列表 [已学习|未学习]', args: [{ name: 'view', rules: [{ type: 'enum', enum: ['已学习', '未学习'] }] }] } }, () => import('./response/skill-list'))
appGroup.use({ path: '技能分页', schema: { usage: '/技能分页 <已学习|未学习> <页码> [关键词]', args: [{ name: 'view', rules: [{ required: true, type: 'enum', enum: ['已学习', '未学习'] }] }, { name: 'page', rules: [{ required: true, type: 'number', min: 1 }] }, { name: 'keyword', rules: [{ type: 'rest' }] }] } }, () => import('./response/skill-list').then(module => ({ default: module.skillPageHandler })))
appGroup.use({ path: '技能搜索', schema: { usage: '/技能搜索 <已学习|未学习> <关键词>', args: [{ name: 'view', rules: [{ required: true, type: 'enum', enum: ['已学习', '未学习'] }] }, { name: 'keyword', rules: [{ required: true, type: 'rest' }] }] } }, () => import('./response/skill-list').then(module => ({ default: module.skillSearchHandler })))
appGroup.use({ path: '技能详情', schema: { usage: '/技能详情 <技能编号>', args: [{ name: 'id', rules: [{ required: true, type: 'number', min: 1 }] }] } }, () => import('./response/skill-list').then(module => ({ default: module.skillDetailHandler })))
appGroup.use({ path: '技能图鉴详情', schema: { usage: '/技能图鉴详情 <技能编号>', args: [{ name: 'id', rules: [{ required: true, type: 'number', min: 1 }] }] } }, () => import('./response/codex').then(module => ({ default: module.skillCodexDetailHandler })))
appGroup.use({ path: '学习技能', schema: { usage: '/学习技能 <技能编号>', args: [{ name: 'id', rules: [{ required: true, type: 'number', min: 1 }] }] } }, () => import('./response/skill-list').then(module => ({ default: module.learnSkillHandler })))
appGroup.use({ path: '技能快捷', schema: { usage: '/技能快捷 <技能编号>', args: [{ name: 'id', rules: [{ required: true, type: 'number', min: 1 }] }] } }, () => import('./response/skill-list').then(module => ({ default: module.skillShortcutHandler })))
appGroup.use({ path: '链接被动', schema: { usage: '/链接被动 <技能编号>', args: [{ name: 'id', rules: [{ required: true, type: 'number', min: 1 }] }] } }, () => import('./response/skill-list').then(module => ({ default: module.passiveLinkHandler })))
appGroup.use('技能贯注', () => import('./response/skill-list').then(module => ({ default: module.skillInfusionHandler })))
appGroup.use({ path: '升级技能', schema: { usage: '/升级技能 <技能编号>', args: [{ name: 'id', rules: [{ required: true, type: 'number', min: 1 }] }] } }, () => import('./response/skill-list').then(module => ({ default: module.upgradeSkillHandler })))
appGroup.use({ path: '升级专精', schema: { usage: '/升级专精 <技能编号> <过充|瞬息|节能|强效|娴熟|随心>', args: [{ name: 'id', rules: [{ required: true, type: 'number', min: 1 }] }, { name: 'specialization', rules: [{ required: true, type: 'enum', enum: ['过充', '瞬息', '节能', '强效', '娴熟', '随心'] }] }] } }, () => import('./response/skill-list').then(module => ({ default: module.upgradeSpecializationHandler })))
appGroup.use({ path: '升级鉴识', schema: { usage: '/升级鉴识 <慧眼|识珠>', args: [{ name: 'direction', rules: [{ required: true, type: 'enum', enum: ['慧眼', '识珠'] }] }] } }, () => import('./response/skill-list').then(module => ({ default: module.upgradeAppraisalHandler })))
appGroup.use('队伍', () => import('./response/party-info'))
appGroup.use('队伍列表', () => import('./response/party-info').then(module => ({ default: module.listHandler })))
appGroup.use('退出队伍', () => import('./response/party-info').then(module => ({ default: module.leaveHandler })))
appGroup.use({ path: '修改队伍名', schema: { usage: '/修改队伍名 <新队伍名>', args: [{ name: 'name', rules: [{ required: true, type: 'rest' }] }] } }, () => import('./response/party-info').then(module => ({ default: module.renameHandler })))
appGroup.use({ path: '委任队长', schema: { usage: '/委任队长 <游戏ID>', args: [{ name: 'id', rules: [{ required: true, type: 'number', min: 10000001 }] }] } }, () => import('./response/party-info').then(module => ({ default: module.transferHandler })))
appGroup.use({ path: '队伍成员信息', schema: { usage: '/队伍成员信息 <游戏ID>', args: [{ name: 'id', rules: [{ required: true, type: 'number', min: 10000001 }] }] } }, () => import('./response/party-info').then(module => ({ default: module.memberInfoHandler })))
appGroup.use({ path: '移动', schema: { usage: '/移动 <上|下|左|右>', args: [{ name: 'direction', rules: [{ required: true, type: 'enum', enum: ['上', '下', '左', '右'] }] }] } }, () => import('./response/move'))
appGroup.use({ path: '调整移速', schema: { usage: '/调整移速 <单次移动距离>', args: [{ name: 'step', rules: [{ required: true, type: 'number', min: 1, max: 10 }] }] } }, () => import('./response/adventure').then(module => ({ default: module.adjustMovementHandler })))
appGroup.use('休息', () => import('./response/panel').then(module => ({ default: module.restHandler })))
appGroup.use('行动', () => import('./response/panel').then(module => ({ default: module.resumeActionHandler })))
appGroup.use({ path: '自动战斗', schema: { usage: '/自动战斗 [开启|关闭|PVE|PVP]', args: [{ name: 'action', rules: [{ type: 'enum', enum: ['开启', '关闭', '配置', 'PVE', 'PVP'] }] }, { name: 'mode', rules: [{ type: 'enum', enum: ['PVE', 'PVP'] }] }] } }, () => import('./response/auto-battle'))
appGroup.use('自动战斗 默认选择', () => import('./response/auto-battle').then(module => ({ default: module.toggleDefaultEncounterActionHandler })))
appGroup.use({ path: '自动战斗 出招选择', schema: { usage: '/自动战斗 出招选择 <位置> [页码] [PVP]', args: [{ name: 'sequence', rules: [{ required: true, type: 'number', min: 1, max: 30 }] }, { name: 'page', rules: [{ type: 'number', min: 1 }] }, { name: 'mode', rules: [{ type: 'enum', enum: ['PVP'] }] }] } }, () => import('./response/auto-battle').then(module => ({ default: module.selectActionHandler })))
appGroup.use({ path: '自动战斗 选择出招', schema: { usage: '/自动战斗 选择出招 <位置> <技能编号，普攻为0> [PVP]', args: [{ name: 'sequence', rules: [{ required: true, type: 'number', min: 1, max: 30 }] }, { name: 'skill', rules: [{ required: true, type: 'number', min: 0 }] }, { name: 'mode', rules: [{ type: 'enum', enum: ['PVP'] }] }] } }, () => import('./response/auto-battle').then(module => ({ default: module.chooseActionHandler })))
appGroup.use({ path: '自动战斗 出招搜索', schema: { usage: '/自动战斗 出招搜索 <位置> <关键词>', args: [{ name: 'sequence', rules: [{ required: true, type: 'number', min: 1, max: 30 }] }, { name: 'keyword', rules: [{ required: true, type: 'rest' }] }] } }, () => import('./response/auto-battle').then(module => ({ default: module.actionSearchHandler })))
appGroup.use({ path: '自动战斗 删除', schema: { usage: '/自动战斗 删除 <位置> [PVP]', args: [{ name: 'sequence', rules: [{ required: true, type: 'number', min: 1, max: 30 }] }, { name: 'mode', rules: [{ type: 'enum', enum: ['PVP'] }] }] } }, () => import('./response/auto-battle').then(module => ({ default: module.deleteActionHandler })))
appGroup.use({ path: '自动战斗 快速配置', schema: { usage: '/自动战斗 快速配置 [PVP]', args: [{ name: 'mode', rules: [{ type: 'enum', enum: ['PVP'] }] }] } }, () => import('./response/auto-battle').then(module => ({ default: module.quickSetupHandler })))
appGroup.use({ path: '自动战斗 快速选择', schema: { usage: '/自动战斗 快速选择 <技能编号，普攻为0> [PVP]', args: [{ name: 'skill', rules: [{ required: true, type: 'number', min: 0 }] }, { name: 'mode', rules: [{ type: 'enum', enum: ['PVP'] }] }] } }, () => import('./response/auto-battle').then(module => ({ default: module.quickChoiceHandler })))
appGroup.use({ path: '自动战斗 快速选择页', schema: { usage: '/自动战斗 快速选择页 <页码> [PVP]', args: [{ name: 'page', rules: [{ required: true, type: 'number', min: 1 }] }, { name: 'mode', rules: [{ type: 'enum', enum: ['PVP'] }] }] } }, () => import('./response/auto-battle').then(module => ({ default: module.quickPageHandler })))
appGroup.use({ path: '自动战斗 快速搜索', schema: { usage: '/自动战斗 快速搜索 <关键词>', args: [{ name: 'keyword', rules: [{ required: true, type: 'rest' }] }] } }, () => import('./response/auto-battle').then(module => ({ default: module.quickSearchHandler })))
appGroup.use({ path: '自动战斗 完成配置', schema: { usage: '/自动战斗 完成配置 [PVP]', args: [{ name: 'mode', rules: [{ type: 'enum', enum: ['PVP'] }] }] } }, () => import('./response/auto-battle').then(module => ({ default: module.quickFinishHandler })))
appGroup.use({ path: '自动战斗 嗑药', schema: { usage: '/自动战斗 嗑药 <开启|关闭> [PVP]', args: [{ name: 'state', rules: [{ required: true, type: 'enum', enum: ['开启', '关闭'] }] }, { name: 'mode', rules: [{ type: 'enum', enum: ['PVP'] }] }] } }, () => import('./response/auto-battle').then(module => ({ default: module.potionToggleHandler })))
appGroup.use({ path: '自动战斗 设置门槛', schema: { usage: '/自动战斗 设置门槛 <生命|魔力> [百分比] [PVP]', args: [{ name: 'kind', rules: [{ required: true, type: 'enum', enum: ['生命', '魔力'] }] }, { name: 'value' }, { name: 'mode', rules: [{ type: 'enum', enum: ['PVP'] }] }] } }, () => import('./response/auto-battle').then(module => ({ default: module.thresholdHandler })))
appGroup.use({ path: '自动战斗 药剂选择', schema: { usage: '/自动战斗 药剂选择 <生命|魔力> [页码] [PVP]', args: [{ name: 'kind', rules: [{ required: true, type: 'enum', enum: ['生命', '魔力'] }] }, { name: 'page' }, { name: 'mode', rules: [{ type: 'enum', enum: ['PVP'] }] }] } }, () => import('./response/auto-battle').then(module => ({ default: module.potionListHandler })))
appGroup.use({ path: '自动战斗 选择药剂', schema: { usage: '/自动战斗 选择药剂 <生命|魔力> <物品编号> [PVP]', args: [{ name: 'kind', rules: [{ required: true, type: 'enum', enum: ['生命', '魔力'] }] }, { name: 'item', rules: [{ required: true, type: 'number', min: 0 }] }, { name: 'mode', rules: [{ type: 'enum', enum: ['PVP'] }] }] } }, () => import('./response/auto-battle').then(module => ({ default: module.potionChoiceHandler })))
appGroup.use({ path: '自动战斗 药剂搜索', schema: { usage: '/自动战斗 药剂搜索 <生命|魔力> <关键词>', args: [{ name: 'kind', rules: [{ required: true, type: 'enum', enum: ['生命', '魔力'] }] }, { name: 'keyword', rules: [{ required: true, type: 'rest' }] }] } }, () => import('./response/auto-battle').then(module => ({ default: module.potionSearchHandler })))
appGroup.use({ path: '前往', schema: { usage: '/前往 <横坐标> <纵坐标>', args: [{ name: 'x', rules: [{ required: true, type: 'number' }] }, { name: 'y', rules: [{ required: true, type: 'number' }] }] } }, () => import('./response/go-to'))
appGroup.use({ path: '前往地图', schema: { usage: '/前往地图 <地图编号>', args: [{ name: 'code', rules: [{ required: true }] }] } }, () => import('./response/adventure').then(module => ({ default: module.goToMapHandler })))
appGroup.use('寻怪', () => import('./response/adventure').then(module => ({ default: module.huntHandler })))
appGroup.use({ path: '下迷宫', schema: { usage: '/下迷宫 <入口编号>', args: [{ name: 'id', rules: [{ required: true, type: 'number', min: 1 }] }] } }, () => import('./response/adventure').then(module => ({ default: module.dungeonEnterHandler })))
appGroup.use({ path: '地下的秘密', schema: { usage: '/地下的秘密 <入口编号>', args: [{ name: 'id', rules: [{ required: true, type: 'number', min: 1 }] }] } }, () => import('./response/dungeon-quest').then(module => ({ default: module.dungeonSecretEntranceHandler })))
appGroup.use('询问地下的秘密', () => import('./response/dungeon-quest').then(module => ({ default: module.dungeonSecretGuildHandler })))
appGroup.use('异工坊 地下的秘密', () => import('./response/dungeon-quest').then(module => ({ default: module.dungeonSecretWorkshopHandler })))
appGroup.use('地宫下行', () => import('./response/adventure').then(module => ({ default: module.dungeonDownHandler })))
appGroup.use('地宫上行', () => import('./response/adventure').then(module => ({ default: module.dungeonUpHandler })))
appGroup.use('离开迷宫', () => import('./response/adventure').then(module => ({ default: module.dungeonLeaveHandler })))
appGroup.use('脱离', () => import('./response/adventure').then(module => ({ default: module.dungeonEscapeHandler })))
appGroup.use({ path: '开启地宫宝箱', schema: { usage: '/开启地宫宝箱 <宝箱编号>', args: [{ name: 'id', rules: [{ required: true, type: 'number', min: 1 }] }] } }, () => import('./response/adventure').then(module => ({ default: module.dungeonChestHandler })))
appGroup.use({ path: '地宫攻击', schema: { usage: '/地宫攻击 <玩家游戏ID>', args: [{ name: 'id', rules: [{ required: true, type: 'number', min: 10000001 }] }] } }, () => import('./response/adventure').then(module => ({ default: module.dungeonPvpHandler })))
appGroup.use({ path: '玩家攻击', schema: { usage: '/玩家攻击 <玩家游戏ID>', args: [{ name: 'id', rules: [{ required: true, type: 'number', min: 10000001 }] }] } }, () => import('./response/adventure').then(module => ({ default: module.playerPvpHandler })))
appGroup.use({ path: '确认攻击', schema: { usage: '/确认攻击 <玩家游戏ID>', args: [{ name: 'id', rules: [{ required: true, type: 'number', min: 10000001 }] }] } }, () => import('./response/adventure').then(module => ({ default: module.confirmPlayerPvpHandler })))
appGroup.use('通缉令', () => import('./response/warrant'))
appGroup.use('通缉', () => import('./response/warrant').then(module => ({ default: module.activeWarrantHandler })))
appGroup.use({ path: '通缉筛选', schema: { usage: '/通缉筛选 <已暴露|近期露面|无行踪>', args: [{ name: 'filter', rules: [{ required: true, type: 'enum', enum: ['已暴露', '近期露面', '无行踪'] }] }] } }, () => import('./response/warrant').then(module => ({ default: module.filterWarrantHandler })))
appGroup.use({ path: '失物返还详情', schema: { usage: '/失物返还详情 <编号>', args: [{ name: 'id', rules: [{ required: true }] }] } }, () => import('./response/restitution-detail'))
appGroup.use({ path: '通缉上赏', schema: { usage: '/通缉上赏 <通缉编号> <铜币|物品> <金额或物品编号> [数量]', args: [{ name: 'warrant', rules: [{ required: true, type: 'number', min: 1 }] }, { name: 'kind', rules: [{ required: true, type: 'enum', enum: ['铜币', '物品'] }] }, { name: 'itemOrAmount', rules: [{ required: true, type: 'number', min: 1 }] }, { name: 'quantity', rules: [{ type: 'number', min: 1 }] }] } }, () => import('./response/warrant').then(module => ({ default: module.addRewardHandler })))
appGroup.use({ path: '玩家互动', schema: { usage: '/玩家互动 <玩家游戏ID>', args: [{ name: 'id', rules: [{ required: true, type: 'number', min: 10000001 }] }] } }, () => import('./response/adventure').then(module => ({ default: module.playerInteractionHandler })))
appGroup.use({ path: '坐标互动', schema: { usage: '/坐标互动 <玩家|NPC|建筑|资源|入口|地标> <目标编号>', args: [{ name: 'type', rules: [{ required: true, type: 'enum', enum: ['玩家', 'NPC', '建筑', '资源', '入口', '地标'] }] }, { name: 'id', rules: [{ required: true }] }] } }, () => import('./response/adventure').then(module => ({ default: module.coordinateInteractionHandler })))
appGroup.use('取消移动', () => import('./response/adventure').then(module => ({ default: module.cancelTravelHandler })))
appGroup.use('取消寻怪', () => import('./response/adventure').then(module => ({ default: module.cancelTravelHandler })))
appGroup.use('刷新行动', () => import('./response/adventure').then(module => ({ default: module.refreshTravelHandler })))
appGroup.use({ path: '开采', schema: { usage: '/开采 <资源编号>', args: [{ name: 'id', rules: [{ required: true, type: 'number', min: 1 }] }] } }, () => import('./response/adventure').then(module => ({ default: module.mineResourceHandler })))
appGroup.use('刷新开采', () => import('./response/adventure').then(module => ({ default: module.refreshMiningHandler })))
appGroup.use('取消开采', () => import('./response/adventure').then(module => ({ default: module.cancelMiningHandler })))
appGroup.use({ path: '目标', schema: { usage: '/目标 <编号>', args: [{ name: 'id', rules: [{ required: true, type: 'number', min: 1 }] }] } }, () => import('./response/target'))
appGroup.use({ path: '怪物攻击', schema: { usage: '/怪物攻击 <怪物编号>', args: [{ name: 'id', rules: [{ required: true, type: 'number', min: 1 }] }] } }, () => import('./response/adventure').then(module => ({ default: module.nearbyMonsterAttackHandler })))
appGroup.use({ path: '偷袭', schema: { usage: '/偷袭 <编号>', args: [{ name: 'id', rules: [{ required: true, type: 'number', min: 1 }] }] } }, () => import('./response/adventure').then(module => ({ default: module.ambushHandler })))
appGroup.use({ path: '伏击', schema: { usage: '/伏击 <编号>', args: [{ name: 'id', rules: [{ required: true, type: 'number', min: 1 }] }] } }, () => import('./response/adventure').then(module => ({ default: module.queueAmbushHandler })))
appGroup.use('离开战斗', () => import('./response/adventure').then(module => ({ default: module.leaveOccupiedBattleHandler })))
appGroup.use({ path: '怪物详情', schema: { usage: '/怪物详情 <编号>', args: [{ name: 'id', rules: [{ required: true, type: 'number', min: 1 }] }] } }, () => import('./response/monster-detail'))
appGroup.use({ path: 'NPC详情', schema: { usage: '/NPC详情 <NPC代号>', args: [{ name: 'code', rules: [{ required: true }] }] } }, () => import('./response/npc-detail'))
appGroup.use({ path: '怪物图鉴详情', schema: { usage: '/怪物图鉴详情 <编号>', args: [{ name: 'id', rules: [{ required: true, type: 'number', min: 1 }] }] } }, () => import('./response/codex').then(module => ({ default: module.monsterCodexDetailHandler })))
appGroup.use({ path: '切换目标', schema: { usage: '/切换目标 <编号>', args: [{ name: 'id', rules: [{ required: true, type: 'number', min: 1 }] }] } }, () => import('./response/adventure').then(module => ({ default: module.switchTargetHandler })))
appGroup.use({ path: '躲避', schema: { usage: '/躲避 <编号>', args: [{ name: 'id', rules: [{ required: true, type: 'number', min: 1 }] }] } }, () => import('./response/encounter').then(module => ({ default: module.encounterHandler('avoid', '躲避') })))
appGroup.use({ path: '交涉', schema: { usage: '/交涉 <编号>', args: [{ name: 'id', rules: [{ required: true, type: 'number', min: 1 }] }] } }, () => import('./response/encounter').then(module => ({ default: module.encounterHandler('persuade', '交涉') })))
appGroup.use({ path: '初章 包容之镇', schema: { usage: '/初章 包容之镇 <选项>', args: [{ name: 'action', rules: [{ required: true, type: 'enum', enum: ['循声而去', '上前打招呼', '我也不清楚，睁开眼时就在这儿了', '加入', '婉拒并询问城镇位置'] }] }] } }, () => import('./response/adventure').then(module => ({ default: module.forestGuideHandler })))
appGroup.use('继续剧情', () => import('./response/adventure').then(module => ({ default: module.continueStoryHandler })))
appGroup.use({ path: '建筑进入', schema: { usage: '/建筑进入 <编号>', args: [{ name: 'code', rules: [{ required: true }] }] } }, () => import('./response/adventure').then(module => ({ default: module.buildingHandler('enter') })))
appGroup.use({ path: '建筑忽略', schema: { usage: '/建筑忽略 <编号>', args: [{ name: 'code', rules: [{ required: true }] }] } }, () => import('./response/adventure').then(module => ({ default: module.buildingHandler('ignore') })))
appGroup.use({ path: '建筑离开', schema: { usage: '/建筑离开 <编号>', args: [{ name: 'code', rules: [{ required: true }] }] } }, () => import('./response/adventure').then(module => ({ default: module.buildingHandler('leave') })))
appGroup.use({ path: '建筑区域', schema: { usage: '/建筑区域 <编号> <区域>', args: [{ name: 'code', rules: [{ required: true }] }, { name: 'area', rules: [{ required: true }] }] } }, () => import('./response/adventure').then(module => ({ default: module.buildingHandler('area') })))
appGroup.use('公会注册', () => import('./response/adventure').then(module => ({ default: module.guildRegistrationHandler })))
appGroup.use('悬赏板', () => import('./response/bounty').then(module => ({ default: module.bountyBoardHandler })))
appGroup.use('任务', () => import('./response/bounty').then(module => ({ default: module.taskHandler })))
appGroup.use('任务栏', () => import('./response/bounty').then(module => ({ default: module.taskHandler })))
appGroup.use({ path: '任务分类', schema: { usage: '/任务分类 <分类>', args: [{ name: 'category', rules: [{ required: true, type: 'enum', enum: ['主线', '支线', '悬赏', '委托', '其他'] }] }] } }, () => import('./response/bounty').then(module => ({ default: module.taskCategoryHandler })))
appGroup.use({ path: '任务页', schema: { usage: '/任务页 <分类|全部> <页码> [关键词]', args: [{ name: 'category', rules: [{ required: true, type: 'enum', enum: ['全部', '主线', '支线', '悬赏', '委托', '其他'] }] }, { name: 'page', rules: [{ required: true, type: 'number', min: 1 }] }, { name: 'keyword' }] } }, () => import('./response/bounty').then(module => ({ default: module.taskPageHandler })))
appGroup.use({ path: '任务搜索', schema: { usage: '/任务搜索 <关键词>', args: [{ name: 'keyword', rules: [{ required: true }] }] } }, () => import('./response/bounty').then(module => ({ default: module.taskSearchHandler })))
appGroup.use({ path: '清除悬赏', schema: { usage: '/清除悬赏 <编号>', args: [{ name: 'id', rules: [{ required: true, type: 'number', min: 1 }] }] } }, () => import('./response/bounty').then(module => ({ default: module.clearInvalidBountyHandler })))
appGroup.use({ path: '放弃悬赏', schema: { usage: '/放弃悬赏 <编号>', args: [{ name: 'id', rules: [{ required: true, type: 'number', min: 1 }] }] } }, () => import('./response/bounty').then(module => ({ default: module.abandonBountyHandler })))
appGroup.use({ path: '放弃副职业任务', schema: { usage: '/放弃副职业任务 <任务编号>', args: [{ name: 'code', rules: [{ required: true, type: 'enum', enum: ['blacksmith_apprentice', 'alchemist_apprentice', 'deconstructor_apprentice', 'omniscient_apprentice'] }] }] } }, () => import('./response/bounty').then(module => ({ default: module.abandonSecondaryQuestHandler })))
appGroup.use('工会商店', () => import('./response/guild-shop').then(module => ({ default: module.guildShopHandler })))
appGroup.use('家园', () => import('./response/home').then(module => ({ default: module.homeHandler })))
appGroup.use('家园购买', () => import('./response/home').then(module => ({ default: module.homePurchaseHandler })))
appGroup.use('家园回家', () => import('./response/home').then(module => ({ default: module.homeEnterHandler })))
appGroup.use('家园出门', () => import('./response/home').then(module => ({ default: module.homeLeaveHandler })))
appGroup.use('家园升级', () => import('./response/home').then(module => ({ default: module.homeUpgradeHandler })))
appGroup.use({ path: '家园扩建', schema: { usage: '/家园扩建 <2|3>', args: [{ name: 'floor', rules: [{ required: true, type: 'enum', enum: ['2', '3'] }] }] } }, () => import('./response/home').then(module => ({ default: module.homeExpandHandler })))
appGroup.use({ path: '家园楼层', schema: { usage: '/家园楼层 <1|2|3>', args: [{ name: 'floor', rules: [{ required: true, type: 'enum', enum: ['1', '2', '3'] }] }] } }, () => import('./response/home').then(module => ({ default: module.homeFloorHandler })))
appGroup.use({ path: '家园家具', schema: { usage: '/家园家具 [页码] [关键词]', args: [{ name: 'page', rules: [{ type: 'number', min: 1 }] }, { name: 'keyword', rules: [{ type: 'rest' }] }] } }, () => import('./response/home').then(module => ({ default: module.homeFurnitureHandler })))
appGroup.use({ path: '家园制作清单', schema: { usage: '/家园制作清单 [页码] [关键词]', args: [{ name: 'page', rules: [{ type: 'number', min: 1 }] }, { name: 'keyword', rules: [{ type: 'rest' }] }] } }, () => import('./response/home').then(module => ({ default: module.homeFurnitureHandler })))
appGroup.use({ path: '家园家具搜索', schema: { usage: '/家园家具搜索 <关键词>', args: [{ name: 'keyword', rules: [{ required: true, type: 'rest' }] }] } }, () => import('./response/home').then(module => ({ default: module.homeFurnitureSearchHandler })))
appGroup.use({ path: '家园家具摆放', schema: { usage: '/家园家具摆放 [1|2|3]', args: [{ name: 'floor', rules: [{ type: 'number', min: 1, max: 3 }] }] } }, () => import('./response/home').then(module => ({ default: module.homeFurniturePlacementHandler })))
appGroup.use({ path: '家园制作', schema: { usage: '/家园制作 <家具代码> <楼层>', args: [{ name: 'code', rules: [{ required: true }] }, { name: 'floor', rules: [{ required: true, type: 'number', min: 1, max: 3 }] }, { name: 'slot' }] } }, () => import('./response/home').then(module => ({ default: module.homeCraftHandler })))
appGroup.use({ path: '家园拆除', schema: { usage: '/家园拆除 <家具编号>', args: [{ name: 'id', rules: [{ required: true, type: 'number', min: 1 }] }] } }, () => import('./response/home').then(module => ({ default: module.homeRemoveHandler })))
appGroup.use('百纳居', () => import('./response/home-shop').then(module => ({ default: module.homeShopHandler })))
appGroup.use({ path: '百纳居交易', schema: { usage: '/百纳居交易 <报价编号> [数量]', args: [{ name: 'id', rules: [{ required: true, type: 'number', min: 1 }] }, { name: 'quantity', rules: [{ type: 'number', min: 1, max: 999 }] }] } }, () => import('./response/home-shop').then(module => ({ default: module.homeShopTradeHandler })))
appGroup.use('餐厅', () => import('./response/guild-restaurant'))
appGroup.use('铁匠铺', () => import('./response/blacksmith'))
appGroup.use({ path: '铁匠铺购买', schema: { usage: '/铁匠铺购买 [全部|头肩|上装|腰部|下装|脚部]', args: [{ name: 'category', rules: [{ type: 'enum', enum: ['全部', '头肩', '上装', '腰部', '下装', '脚部'] }] }] } }, () => import('./response/blacksmith-shop').then(module => ({ default: module.blacksmithShopBuyListHandler })))
appGroup.use({ path: '铁匠铺购买页', schema: { usage: '/铁匠铺购买页 <全部|头肩|上装|腰部|下装|脚部> <页码> [关键词]', args: [{ name: 'category', rules: [{ required: true, type: 'enum', enum: ['全部', '头肩', '上装', '腰部', '下装', '脚部'] }] }, { name: 'page', rules: [{ required: true, type: 'number', min: 1 }] }, { name: 'keyword' }] } }, () => import('./response/blacksmith-shop').then(module => ({ default: module.blacksmithShopBuyListHandler })))
appGroup.use({ path: '铁匠铺购买搜索', schema: { usage: '/铁匠铺购买搜索 <全部|头肩|上装|腰部|下装|脚部> <装备关键词>', args: [{ name: 'category', rules: [{ required: true, type: 'enum', enum: ['全部', '头肩', '上装', '腰部', '下装', '脚部'] }] }, { name: 'keyword', rules: [{ required: true }] }] } }, () => import('./response/blacksmith-shop').then(module => ({ default: module.blacksmithShopBuySearchHandler })))
appGroup.use({ path: '购买铁匠铺装备', schema: { usage: '/购买铁匠铺装备 <装备编号> [数量]', args: [{ name: 'id', rules: [{ required: true, type: 'number', min: 1 }] }, { name: 'quantity', rules: [{ type: 'number', min: 1, max: 99 }] }] } }, () => import('./response/blacksmith-shop').then(module => ({ default: module.blacksmithShopPurchaseHandler })))
appGroup.use('铁匠铺出售', () => import('./response/blacksmith-shop').then(module => ({ default: module.blacksmithShopSellListHandler })))
appGroup.use({ path: '铁匠铺出售页', schema: { usage: '/铁匠铺出售页 <页码> [关键词]', args: [{ name: 'page', rules: [{ required: true, type: 'number', min: 1 }] }, { name: 'keyword' }] } }, () => import('./response/blacksmith-shop').then(module => ({ default: module.blacksmithShopSellListHandler })))
appGroup.use({ path: '铁匠铺出售搜索', schema: { usage: '/铁匠铺出售搜索 <装备关键词>', args: [{ name: 'keyword', rules: [{ required: true }] }] } }, () => import('./response/blacksmith-shop').then(module => ({ default: module.blacksmithShopSellSearchHandler })))
appGroup.use({ path: '出售铁匠铺装备', schema: { usage: '/出售铁匠铺装备 <装备实例编号>', args: [{ name: 'instanceId', rules: [{ required: true, type: 'number', min: 1 }] }] } }, () => import('./response/blacksmith-shop').then(module => ({ default: module.blacksmithShopSellHandler })))
appGroup.use({ path: '出售铁匠铺材料', schema: { usage: '/出售铁匠铺材料 <物品编号> [数量]', args: [{ name: 'itemId', rules: [{ required: true, type: 'number', min: 1 }] }, { name: 'quantity', rules: [{ type: 'number', min: 1, max: 999 }] }] } }, () => import('./response/blacksmith-shop').then(module => ({ default: module.blacksmithShopSellMaterialHandler })))
appGroup.use('铁匠铺闲聊', () => import('./response/blacksmith-shop').then(module => ({ default: module.blacksmithChatHandler })))
appGroup.use('学习小北的匠心', () => import('./response/blacksmith-shop').then(module => ({ default: module.learnXiaobeiCraftsmanshipHandler })))
appGroup.use('教堂', () => import('./response/church'))
appGroup.use('圣恩教堂', () => import('./response/church'))
appGroup.use('修女闲聊', () => import('./response/church').then(module => ({ default: module.churchChatHandler })))
appGroup.use('糖水屋', () => import('./response/alchemist').then(module => ({ default: module.alchemistShopHandler })))
appGroup.use('晴空糖水屋', () => import('./response/alchemist').then(module => ({ default: module.alchemistShopHandler })))
appGroup.use('晴儿闲聊', () => import('./response/alchemist').then(module => ({ default: module.alchemistChatHandler })))
appGroup.use('异工坊', () => import('./response/deconstructor').then(module => ({ default: module.oddWorkshopHandler })))
appGroup.use('唯薇安闲聊', () => import('./response/deconstructor').then(module => ({ default: module.oddWorkshopChatHandler })))
appGroup.use('异工坊购买', () => import('./response/deconstructor').then(module => ({ default: module.oddWorkshopTradeHandler('buy') })))
appGroup.use({ path: '购买异工坊商品', schema: { usage: '/购买异工坊商品 <破魔传送器|图纸>', args: [{ name: 'code', rules: [{ required: true, type: 'enum', enum: ['demon_breaker_teleporter', 'demon_breaker_teleporter_blueprint'] }] }] } }, () => import('./response/dungeon-quest').then(module => ({ default: module.oddWorkshopPurchaseHandler })))
appGroup.use('异工坊出售', () => import('./response/deconstructor').then(module => ({ default: module.oddWorkshopTradeHandler('sell') })))
appGroup.use({ path: '异工坊出售页', schema: { usage: '/异工坊出售页 <页码> [关键词]', args: [{ name: 'page', rules: [{ required: true, type: 'number', min: 1 }] }, { name: 'keyword' }] } }, () => import('./response/deconstructor').then(module => ({ default: module.oddWorkshopSellPageHandler })))
appGroup.use({ path: '异工坊出售搜索', schema: { usage: '/异工坊出售搜索 <关键词>', args: [{ name: 'keyword', rules: [{ required: true }] }] } }, () => import('./response/deconstructor').then(module => ({ default: module.oddWorkshopSellSearchHandler })))
appGroup.use({ path: '出售异工坊物品', schema: { usage: '/出售异工坊物品 <物品编号> [数量]', args: [{ name: 'id', rules: [{ required: true, type: 'number', min: 1 }] }, { name: 'quantity', rules: [{ type: 'number', min: 1, max: 999 }] }] } }, () => import('./response/deconstructor').then(module => ({ default: module.oddWorkshopSellItemHandler })))
appGroup.use('猎户小屋', () => import('./response/hunter-lodge').then(module => ({ default: module.hunterLodgeHandler })))
appGroup.use({ path: '猎户购买', schema: { usage: '/猎户购买 [页码] [关键词]', args: [{ name: 'page', rules: [{ type: 'number', min: 1 }] }, { name: 'keyword' }] } }, () => import('./response/hunter-lodge').then(module => ({ default: module.hunterBuyHandler })))
appGroup.use({ path: '猎户购买页', schema: { usage: '/猎户购买页 <页码> [关键词]', args: [{ name: 'page', rules: [{ required: true, type: 'number', min: 1 }] }, { name: 'keyword' }] } }, () => import('./response/hunter-lodge').then(module => ({ default: module.hunterBuyHandler })))
appGroup.use({ path: '猎户购买搜索', schema: { usage: '/猎户购买搜索 <关键词>', args: [{ name: 'keyword', rules: [{ required: true }] }] } }, () => import('./response/hunter-lodge').then(module => ({ default: module.hunterBuySearchHandler })))
appGroup.use({ path: '购买猎户物品', schema: { usage: '/购买猎户物品 <物品编号> [数量]', args: [{ name: 'id', rules: [{ required: true, type: 'number', min: 1 }] }, { name: 'quantity', rules: [{ type: 'number', min: 1, max: 999 }] }] } }, () => import('./response/hunter-lodge').then(module => ({ default: module.hunterPurchaseHandler })))
appGroup.use('猎户出售', () => import('./response/hunter-lodge').then(module => ({ default: module.hunterSellHandler })))
appGroup.use({ path: '猎户出售页', schema: { usage: '/猎户出售页 <页码> [关键词]', args: [{ name: 'page', rules: [{ required: true, type: 'number', min: 1 }] }, { name: 'keyword' }] } }, () => import('./response/hunter-lodge').then(module => ({ default: module.hunterSellHandler })))
appGroup.use({ path: '猎户出售搜索', schema: { usage: '/猎户出售搜索 <关键词>', args: [{ name: 'keyword', rules: [{ required: true }] }] } }, () => import('./response/hunter-lodge').then(module => ({ default: module.hunterSellSearchHandler })))
appGroup.use({ path: '出售猎户物品', schema: { usage: '/出售猎户物品 <物品编号> [数量]', args: [{ name: 'id', rules: [{ required: true, type: 'number', min: 1 }] }, { name: 'quantity', rules: [{ type: 'number', min: 1, max: 999 }] }] } }, () => import('./response/hunter-lodge').then(module => ({ default: module.hunterSellItemHandler })))
appGroup.use('猎户闲聊', () => import('./response/hunter-lodge').then(module => ({ default: module.hunterChatHandler })))
appGroup.use('百味书屋', () => import('./response/bookshop').then(module => ({ default: module.bookshopHandler })))
appGroup.use({ path: '书屋购买', schema: { usage: '/书屋购买 [页码] [关键词]', args: [{ name: 'page', rules: [{ type: 'number', min: 1 }] }, { name: 'keyword' }] } }, () => import('./response/bookshop').then(module => ({ default: module.bookshopBuyHandler })))
appGroup.use({ path: '书屋购买页', schema: { usage: '/书屋购买页 <页码> [关键词]', args: [{ name: 'page', rules: [{ required: true, type: 'number', min: 1 }] }, { name: 'keyword' }] } }, () => import('./response/bookshop').then(module => ({ default: module.bookshopBuyHandler })))
appGroup.use({ path: '书屋购买搜索', schema: { usage: '/书屋购买搜索 <关键词>', args: [{ name: 'keyword', rules: [{ required: true }] }] } }, () => import('./response/bookshop').then(module => ({ default: module.bookshopBuySearchHandler })))
appGroup.use({ path: '购买书屋物品', schema: { usage: '/购买书屋物品 <物品编号> [数量]', args: [{ name: 'id', rules: [{ required: true, type: 'number', min: 1 }] }, { name: 'quantity', rules: [{ type: 'number', min: 1, max: 999 }] }] } }, () => import('./response/bookshop').then(module => ({ default: module.bookshopPurchaseHandler })))
appGroup.use('书屋出售', () => import('./response/bookshop').then(module => ({ default: module.bookshopSellHandler })))
appGroup.use({ path: '书屋出售页', schema: { usage: '/书屋出售页 <页码> [关键词]', args: [{ name: 'page', rules: [{ required: true, type: 'number', min: 1 }] }, { name: 'keyword' }] } }, () => import('./response/bookshop').then(module => ({ default: module.bookshopSellHandler })))
appGroup.use({ path: '书屋出售搜索', schema: { usage: '/书屋出售搜索 <关键词>', args: [{ name: 'keyword', rules: [{ required: true }] }] } }, () => import('./response/bookshop').then(module => ({ default: module.bookshopSellSearchHandler })))
appGroup.use({ path: '出售书屋物品', schema: { usage: '/出售书屋物品 <物品编号> [数量]', args: [{ name: 'id', rules: [{ required: true, type: 'number', min: 1 }] }, { name: 'quantity', rules: [{ type: 'number', min: 1, max: 999 }] }] } }, () => import('./response/bookshop').then(module => ({ default: module.bookshopSellItemHandler })))
appGroup.use('书屋闲聊', () => import('./response/bookshop').then(module => ({ default: module.bookshopChatHandler })))
appGroup.use({ path: '研读技能书', schema: { usage: '/研读技能书 <物品编号>', args: [{ name: 'id', rules: [{ required: true, type: 'number', min: 1 }] }] } }, () => import('./response/bookshop').then(module => ({ default: module.readBookHandler })))
appGroup.use('关于全知者', () => import('./response/bookshop').then(module => ({ default: module.omniscientAboutHandler })))
appGroup.use('选择副职业 全知者', () => import('./response/bookshop').then(module => ({ default: module.omniscientProfessionSelectHandler })))
appGroup.use('接受全知者任务', () => import('./response/bookshop').then(module => ({ default: module.acceptOmniscientQuestHandler })))
appGroup.use('提交全知者任务', () => import('./response/bookshop').then(module => ({ default: module.claimOmniscientQuestHandler })))
appGroup.use('全知者明鉴', () => import('./response/bookshop').then(module => ({ default: module.omniscientInsightHandler })))
appGroup.use('全知者识踪', () => import('./response/bookshop').then(module => ({ default: module.omniscientTraceHandler })))
appGroup.use('全知者巧思', () => import('./response/bookshop').then(module => ({ default: module.omniscientIngenuityHandler })))
appGroup.use('打造装备', () => import('./response/blacksmith').then(module => ({ default: module.forgeHandler })))
appGroup.use('副职业打造装备', () => import('./response/blacksmith').then(module => ({ default: module.secondaryProfessionForgeHandler })))
appGroup.use({ path: '打造部位', schema: { usage: '/打造部位 <部位>', args: [{ name: 'category', rules: [{ required: true, type: 'enum', enum: ['武器', '头肩', '上装', '腰部', '下装', '脚部'] }] }] } }, () => import('./response/blacksmith').then(module => ({ default: module.forgeCategoryHandler })))
appGroup.use({ path: '打造类型', schema: { usage: '/打造类型 <类型>', args: [{ name: 'subtype', rules: [{ required: true, type: 'enum', enum: ['长剑', '法杖', '匕首', '拳刃', '布甲', '皮甲', '轻甲', '重甲', '板甲'] }] }] } }, () => import('./response/blacksmith').then(module => ({ default: module.forgeSubtypeHandler })))
appGroup.use({ path: '打造等级', schema: { usage: '/打造等级 <等级>', args: [{ name: 'level', rules: [{ required: true, type: 'number', min: 5, max: 50 }] }] } }, () => import('./response/blacksmith').then(module => ({ default: module.forgeLevelHandler })))
appGroup.use('打造材料', () => import('./response/blacksmith').then(module => ({ default: module.forgeMaterialListHandler })))
appGroup.use({ path: '打造材料页', schema: { usage: '/打造材料页 <页码> [关键词]', args: [{ name: 'page', rules: [{ required: true, type: 'number', min: 1 }] }, { name: 'keyword' }] } }, () => import('./response/blacksmith').then(module => ({ default: module.forgeMaterialPageHandler })))
appGroup.use({ path: '打造材料搜索', schema: { usage: '/打造材料搜索 <关键词>', args: [{ name: 'keyword', rules: [{ required: true }] }] } }, () => import('./response/blacksmith').then(module => ({ default: module.forgeMaterialSearchHandler })))
appGroup.use({ path: '放入打造材料', schema: { usage: '/放入打造材料 <材料编号> [数量]', args: [{ name: 'id', rules: [{ required: true, type: 'number', min: 1 }] }, { name: 'quantity', rules: [{ type: 'number', min: 1 }] }] } }, () => import('./response/blacksmith').then(module => ({ default: module.forgeMaterialHandler })))
appGroup.use({ path: '取出打造材料', schema: { usage: '/取出打造材料 <材料编号>', args: [{ name: 'id', rules: [{ required: true, type: 'number', min: 1 }] }] } }, () => import('./response/blacksmith').then(module => ({ default: module.forgeMaterialRemoveHandler })))
appGroup.use({ path: '修改打造材料', schema: { usage: '/修改打造材料 <材料编号> <数量>', args: [{ name: 'id', rules: [{ required: true, type: 'number', min: 1 }] }, { name: 'quantity', rules: [{ required: true, type: 'number', min: 0 }] }] } }, () => import('./response/blacksmith').then(module => ({ default: module.forgeMaterialSetHandler })))
appGroup.use({ path: '删除打造材料', schema: { usage: '/删除打造材料 <材料编号>', args: [{ name: 'id', rules: [{ required: true, type: 'number', min: 1 }] }] } }, () => import('./response/blacksmith').then(module => ({ default: module.forgeMaterialClearHandler })))
appGroup.use('开始打造', () => import('./response/blacksmith').then(module => ({ default: module.forgeStartHandler(false) })))
appGroup.use('确认打造', () => import('./response/blacksmith').then(module => ({ default: module.forgeStartHandler(true) })))
appGroup.use('关于锻造师', () => import('./response/blacksmith').then(module => ({ default: module.blacksmithAboutHandler })))
appGroup.use({ path: '选择副职业', schema: { usage: '/选择副职业 <副职业>', args: [{ name: 'name', rules: [{ required: true, type: 'enum', enum: ['锻造师'] }] }] } }, () => import('./response/blacksmith').then(module => ({ default: module.blacksmithProfessionSelectHandler })))
appGroup.use('接受锻造师任务', () => import('./response/blacksmith').then(module => ({ default: module.acceptBlacksmithQuestHandler })))
appGroup.use('提交锻造师任务', () => import('./response/blacksmith').then(module => ({ default: module.claimBlacksmithQuestHandler })))
appGroup.use('副职业', () => import('./response/blacksmith').then(module => ({ default: module.secondaryProfessionHandler })))
appGroup.use('分解', () => import('./response/deconstructor').then(module => ({ default: module.deconstructorFeatureHandler('分解') })))
appGroup.use({ path: '分解页', schema: { usage: '/分解页 <装备|道具|材料> <页码> [关键词]', args: [{ name: 'category', rules: [{ required: true, type: 'enum', enum: ['装备', '道具', '材料'] }] }, { name: 'page', rules: [{ required: true, type: 'number', min: 1 }] }, { name: 'keyword' }] } }, () => import('./response/deconstructor').then(module => ({ default: module.deconstructionPageHandler })))
appGroup.use({ path: '分解搜索', schema: { usage: '/分解搜索 <装备|道具|材料> <关键词>', args: [{ name: 'category', rules: [{ required: true, type: 'enum', enum: ['装备', '道具', '材料'] }] }, { name: 'keyword', rules: [{ required: true }] }] } }, () => import('./response/deconstructor').then(module => ({ default: module.deconstructionSearchHandler })))
appGroup.use({ path: '分解物品', schema: { usage: '/分解物品 <物品编号> [数量]', args: [{ name: 'id', rules: [{ required: true, type: 'number', min: 1 }] }, { name: 'quantity', rules: [{ type: 'number', min: 1, max: 9999 }] }] } }, () => import('./response/deconstructor').then(module => ({ default: module.deconstructItemHandler })))
appGroup.use('构造', () => import('./response/deconstructor').then(module => ({ default: module.deconstructorFeatureHandler('构造') })))
appGroup.use({ path: '构造制作', schema: { usage: '/构造制作 <配方>', args: [{ name: 'code', rules: [{ required: true, type: 'string' }] }] } }, () => import('./response/deconstructor').then(module => ({ default: module.constructItemHandler })))
appGroup.use({ path: '构造页', schema: { usage: '/构造页 <基材|构件|异械> <页码> [关键词]', args: [{ name: 'category', rules: [{ required: true, type: 'enum', enum: ['基材', '构件', '异械'] }] }, { name: 'page', rules: [{ required: true, type: 'number', min: 1 }] }, { name: 'keyword' }] } }, () => import('./response/deconstructor').then(module => ({ default: module.constructionPageHandler })))
appGroup.use({ path: '构造搜索', schema: { usage: '/构造搜索 <基材|构件|异械> <关键词>', args: [{ name: 'category', rules: [{ required: true, type: 'enum', enum: ['基材', '构件', '异械'] }] }, { name: 'keyword', rules: [{ required: true }] }] } }, () => import('./response/deconstructor').then(module => ({ default: module.constructionSearchHandler })))
appGroup.use('关于无形的禁锢', () => import('./response/adventure').then(module => ({ default: module.guildBarrierHandler })))
appGroup.use('晴儿 关于无形的禁锢', () => import('./response/alchemist').then(module => ({ default: module.alchemistBarrierHandler })))
appGroup.use('窥探天空粉尘', () => import('./response/main-quest').then(module => ({ default: module.contemplateSkyDustHandler })))
appGroup.use('关于炼金师', () => import('./response/alchemist').then(module => ({ default: module.alchemistAboutHandler })))
appGroup.use('关于解构师', () => import('./response/deconstructor').then(module => ({ default: module.deconstructorAboutHandler })))
appGroup.use('选择副职业 炼金师', () => import('./response/alchemist').then(module => ({ default: module.alchemistProfessionSelectHandler })))
appGroup.use('选择副职业 解构师', () => import('./response/deconstructor').then(module => ({ default: module.deconstructorProfessionSelectHandler })))
appGroup.use('接受炼金师任务', () => import('./response/alchemist').then(module => ({ default: module.acceptAlchemistQuestHandler })))
appGroup.use('接受解构师任务', () => import('./response/deconstructor').then(module => ({ default: module.acceptDeconstructorQuestHandler })))
appGroup.use('提交炼金师任务', () => import('./response/alchemist').then(module => ({ default: module.claimAlchemistQuestHandler })))
appGroup.use('提交解构师任务', () => import('./response/deconstructor').then(module => ({ default: module.claimDeconstructorQuestHandler })))
appGroup.use('提纯', () => import('./response/alchemist').then(module => ({ default: module.purificationHandler })))
appGroup.use({ path: '提纯材料页', schema: { usage: '/提纯材料页 <页码> [关键词]', args: [{ name: 'page', rules: [{ required: true, type: 'number', min: 1 }] }, { name: 'keyword' }] } }, () => import('./response/alchemist').then(module => ({ default: module.purificationPageHandler })))
appGroup.use({ path: '提纯材料搜索', schema: { usage: '/提纯材料搜索 <关键词>', args: [{ name: 'keyword', rules: [{ required: true }] }] } }, () => import('./response/alchemist').then(module => ({ default: module.purificationSearchHandler })))
appGroup.use({ path: '提纯放入', schema: { usage: '/提纯放入 <材料编号> [数量]', args: [{ name: 'id', rules: [{ required: true, type: 'number', min: 1 }] }, { name: 'quantity', rules: [{ type: 'number', min: 1, max: 9999 }] }] } }, () => import('./response/alchemist').then(module => ({ default: module.purificationPutHandler })))
appGroup.use('提纯清空', () => import('./response/alchemist').then(module => ({ default: module.purificationClearHandler })))
appGroup.use('提纯删除', () => import('./response/alchemist').then(module => ({ default: module.purificationClearHandler })))
appGroup.use('开始提纯', () => import('./response/alchemist').then(module => ({ default: module.purificationExecuteHandler })))
appGroup.use('炼金', () => import('./response/alchemist').then(module => ({ default: module.alchemyHandler })))
appGroup.use({ path: '炼金材料页', schema: { usage: '/炼金材料页 <页码> [关键词]', args: [{ name: 'page', rules: [{ required: true, type: 'number', min: 1 }] }, { name: 'keyword' }] } }, () => import('./response/alchemist').then(module => ({ default: module.alchemyMaterialPageHandler })))
appGroup.use({ path: '炼金材料搜索', schema: { usage: '/炼金材料搜索 <关键词>', args: [{ name: 'keyword', rules: [{ required: true }] }] } }, () => import('./response/alchemist').then(module => ({ default: module.alchemyMaterialSearchHandler })))
appGroup.use({ path: '炼金选材', schema: { usage: '/炼金选材 <主材|辅材|反应剂> <材料编号>', args: [{ name: 'role', rules: [{ required: true, type: 'enum', enum: ['主材', '辅材', '反应剂'] }] }, { name: 'item', rules: [{ required: true, type: 'number', min: 1 }] }] } }, () => import('./response/alchemist').then(module => ({ default: module.alchemySelectHandler })))
appGroup.use({ path: '炼金添加', schema: { usage: '/炼金添加 <主材|辅材|反应剂> <材料名称或编号>', args: [{ name: 'role', rules: [{ required: true, type: 'enum', enum: ['主材', '辅材', '反应剂'] }] }, { name: 'item', rules: [{ required: true }] }] } }, () => import('./response/alchemist').then(module => ({ default: module.alchemyAddHandler })))
appGroup.use({ path: '炼金移除', schema: { usage: '/炼金移除 <main|auxiliary|reagent>', args: [{ name: 'role', rules: [{ required: true, type: 'enum', enum: ['main', 'auxiliary', 'reagent'] }] }] } }, () => import('./response/alchemist').then(module => ({ default: module.alchemyRemoveHandler })))
appGroup.use('保存炼金配方', () => import('./response/alchemist').then(module => ({ default: module.saveAlchemyFormulaHandler })))
appGroup.use('炼金配方', () => import('./response/alchemist').then(module => ({ default: module.alchemyFormulaListHandler })))
appGroup.use({ path: '炼金配方页', schema: { usage: '/炼金配方页 <页码> [关键词]', args: [{ name: 'page', rules: [{ required: true, type: 'number', min: 1 }] }, { name: 'keyword' }] } }, () => import('./response/alchemist').then(module => ({ default: module.alchemyFormulaPageHandler })))
appGroup.use({ path: '炼金配方搜索', schema: { usage: '/炼金配方搜索 <关键词>', args: [{ name: 'keyword', rules: [{ required: true }] }] } }, () => import('./response/alchemist').then(module => ({ default: module.alchemyFormulaSearchHandler })))
appGroup.use({ path: '炼金配方改名', schema: { usage: '/炼金配方改名 <配方编号> <名称>', args: [{ name: 'id', rules: [{ required: true, type: 'number', min: 1 }] }, { name: 'name', rules: [{ required: true }] }] } }, () => import('./response/alchemist').then(module => ({ default: module.renameAlchemyFormulaHandler })))
appGroup.use({ path: '加入炼金配方', schema: { usage: '/加入炼金配方 <配方编号>', args: [{ name: 'id', rules: [{ required: true, type: 'number', min: 1 }] }] } }, () => import('./response/alchemist').then(module => ({ default: module.loadAlchemyFormulaHandler })))
appGroup.use({ path: '删除炼金配方', schema: { usage: '/删除炼金配方 <配方编号>', args: [{ name: 'id', rules: [{ required: true, type: 'number', min: 1 }] }] } }, () => import('./response/alchemist').then(module => ({ default: module.deleteAlchemyFormulaHandler })))
appGroup.use('开始炼金', () => import('./response/alchemist').then(module => ({ default: module.alchemyExecuteHandler })))
appGroup.use({ path: '炼金商店购买', schema: { usage: '/炼金商店购买 [全部|回复|特殊]', args: [{ name: 'category', rules: [{ type: 'enum', enum: ['全部', '回复', '特殊'] }] }] } }, () => import('./response/alchemist').then(module => ({ default: module.alchemistBuyListHandler })))
appGroup.use({ path: '炼金商店购买页', schema: { usage: '/炼金商店购买页 <全部|回复|特殊> <页码> [关键词]', args: [{ name: 'category', rules: [{ required: true, type: 'enum', enum: ['全部', '回复', '特殊'] }] }, { name: 'page', rules: [{ required: true, type: 'number', min: 1 }] }, { name: 'keyword' }] } }, () => import('./response/alchemist').then(module => ({ default: module.alchemistBuyListHandler })))
appGroup.use({ path: '炼金商店搜索', schema: { usage: '/炼金商店搜索 <全部|回复|特殊> <关键词>', args: [{ name: 'category', rules: [{ required: true, type: 'enum', enum: ['全部', '回复', '特殊'] }] }, { name: 'keyword', rules: [{ required: true }] }] } }, () => import('./response/alchemist').then(module => ({ default: module.alchemistBuySearchHandler })))
appGroup.use({ path: '购买炼金商品', schema: { usage: '/购买炼金商品 <商品编号> [数量]', args: [{ name: 'id', rules: [{ required: true, type: 'number', min: 1 }] }, { name: 'quantity', rules: [{ type: 'number', min: 1, max: 999 }] }] } }, () => import('./response/alchemist').then(module => ({ default: module.alchemistPurchaseHandler })))
appGroup.use('炼金商店出售', () => import('./response/alchemist').then(module => ({ default: module.alchemistTradeHandler })))
appGroup.use({ path: '炼金商店出售页', schema: { usage: '/炼金商店出售页 <页码> [关键词]', args: [{ name: 'page', rules: [{ required: true, type: 'number', min: 1 }] }, { name: 'keyword' }] } }, () => import('./response/alchemist').then(module => ({ default: module.alchemistSellPageHandler })))
appGroup.use({ path: '炼金商店出售搜索', schema: { usage: '/炼金商店出售搜索 <关键词>', args: [{ name: 'keyword', rules: [{ required: true }] }] } }, () => import('./response/alchemist').then(module => ({ default: module.alchemistSellSearchHandler })))
appGroup.use({ path: '出售炼金商品', schema: { usage: '/出售炼金商品 <物品编号> [数量]', args: [{ name: 'id', rules: [{ required: true, type: 'number', min: 1 }] }, { name: 'quantity', rules: [{ type: 'number', min: 1, max: 999 }] }] } }, () => import('./response/alchemist').then(module => ({ default: module.alchemistSellItemHandler })))
appGroup.use('精炼', () => import('./response/blacksmith').then(module => ({ default: module.refineListHandler })))
appGroup.use({ path: '精炼页', schema: { usage: '/精炼页 <页码> [关键词]', args: [{ name: 'page', rules: [{ required: true, type: 'number', min: 1 }] }, { name: 'keyword' }] } }, () => import('./response/blacksmith').then(module => ({ default: module.refinePageHandler })))
appGroup.use({ path: '精炼搜索', schema: { usage: '/精炼搜索 <装备关键词>', args: [{ name: 'keyword', rules: [{ required: true }] }] } }, () => import('./response/blacksmith').then(module => ({ default: module.refineSearchHandler })))
appGroup.use({ path: '精炼放入', schema: { usage: '/精炼放入 <武器实例编号>', args: [{ name: 'id', rules: [{ required: true, type: 'number', min: 1 }] }] } }, () => import('./response/blacksmith').then(module => ({ default: module.refinePutHandler })))
appGroup.use({ path: '精炼材料页', schema: { usage: '/精炼材料页 <武器实例编号> <页码> [关键词]', args: [{ name: 'id', rules: [{ required: true, type: 'number', min: 1 }] }, { name: 'page', rules: [{ required: true, type: 'number', min: 1 }] }, { name: 'keyword' }] } }, () => import('./response/blacksmith').then(module => ({ default: module.refineMaterialPageHandler })))
appGroup.use({ path: '精炼材料搜索', schema: { usage: '/精炼材料搜索 <武器实例编号> <关键词>', args: [{ name: 'id', rules: [{ required: true, type: 'number', min: 1 }] }, { name: 'keyword', rules: [{ required: true }] }] } }, () => import('./response/blacksmith').then(module => ({ default: module.refineMaterialSearchHandler })))
appGroup.use({ path: '精炼执行', schema: { usage: '/精炼执行 <武器实例编号> <材料编号>', args: [{ name: 'instanceId', rules: [{ required: true, type: 'number', min: 1 }] }, { name: 'materialId', rules: [{ required: true, type: 'number', min: 1 }] }] } }, () => import('./response/blacksmith').then(module => ({ default: module.refineExecuteHandler })))
appGroup.use('熔铸', () => import('./response/blacksmith').then(module => ({ default: module.fuseListHandler })))
appGroup.use({ path: '熔铸页', schema: { usage: '/熔铸页 <页码> [关键词]', args: [{ name: 'page', rules: [{ required: true, type: 'number', min: 1 }] }, { name: 'keyword' }] } }, () => import('./response/blacksmith').then(module => ({ default: module.fusePageHandler })))
appGroup.use({ path: '熔铸搜索', schema: { usage: '/熔铸搜索 <装备关键词>', args: [{ name: 'keyword', rules: [{ required: true }] }] } }, () => import('./response/blacksmith').then(module => ({ default: module.fuseSearchHandler })))
appGroup.use({ path: '熔铸放入', schema: { usage: '/熔铸放入 <武器实例编号>', args: [{ name: 'id', rules: [{ required: true, type: 'number', min: 1 }] }] } }, () => import('./response/blacksmith').then(module => ({ default: module.fusePutHandler })))
appGroup.use({ path: '熔铸材料页', schema: { usage: '/熔铸材料页 <武器实例编号> <页码> [关键词]', args: [{ name: 'id', rules: [{ required: true, type: 'number', min: 1 }] }, { name: 'page', rules: [{ required: true, type: 'number', min: 1 }] }, { name: 'keyword' }] } }, () => import('./response/blacksmith').then(module => ({ default: module.fuseMaterialPageHandler })))
appGroup.use({ path: '熔铸材料搜索', schema: { usage: '/熔铸材料搜索 <武器实例编号> <关键词>', args: [{ name: 'id', rules: [{ required: true, type: 'number', min: 1 }] }, { name: 'keyword', rules: [{ required: true }] }] } }, () => import('./response/blacksmith').then(module => ({ default: module.fuseMaterialSearchHandler })))
appGroup.use({ path: '熔铸执行', schema: { usage: '/熔铸执行 <武器实例编号> <材料编号>', args: [{ name: 'instanceId', rules: [{ required: true, type: 'number', min: 1 }] }, { name: 'materialId', rules: [{ required: true, type: 'number', min: 1 }] }] } }, () => import('./response/blacksmith').then(module => ({ default: module.fuseExecuteHandler })))
appGroup.use('餐厅菜单', () => import('./response/guild-restaurant').then(module => ({ default: module.restaurantMenuHandler })))
appGroup.use({ path: '餐厅菜单页', schema: { usage: '/餐厅菜单页 <页码> [关键词]', args: [{ name: 'page', rules: [{ required: true, type: 'number', min: 1 }] }, { name: 'keyword' }] } }, () => import('./response/guild-restaurant').then(module => ({ default: module.restaurantMenuHandler })))
appGroup.use({ path: '餐厅搜索', schema: { usage: '/餐厅搜索 <菜品关键词>', args: [{ name: 'keyword', rules: [{ required: true }] }] } }, () => import('./response/guild-restaurant').then(module => ({ default: module.restaurantSearchHandler })))
appGroup.use({ path: '享用美食', schema: { usage: '/享用美食 <菜品编号>', args: [{ name: 'id', rules: [{ required: true, type: 'number', min: 1 }] }] } }, () => import('./response/guild-restaurant').then(module => ({ default: module.enjoyMealHandler })))
appGroup.use('商店购买', () => import('./response/guild-shop').then(module => ({ default: module.shopBuyListHandler })))
appGroup.use({ path: '商店购买页', schema: { usage: '/商店购买页 <页码> [关键词]', args: [{ name: 'page', rules: [{ required: true, type: 'number', min: 1 }] }, { name: 'keyword' }] } }, () => import('./response/guild-shop').then(module => ({ default: module.shopBuyListHandler })))
appGroup.use({ path: '商店搜索', schema: { usage: '/商店搜索 <物品名关键词>', args: [{ name: 'keyword', rules: [{ required: true }] }] } }, () => import('./response/guild-shop').then(module => ({ default: module.shopSearchHandler })))
appGroup.use({ path: '购买商品', schema: { usage: '/购买商品 <商品编号> [数量]', args: [{ name: 'id', rules: [{ required: true, type: 'number', min: 1 }] }, { name: 'quantity', rules: [{ type: 'number', min: 1 }] }] } }, () => import('./response/guild-shop').then(module => ({ default: module.shopPurchaseHandler })))
appGroup.use('商店出售', () => import('./response/guild-shop').then(module => ({ default: module.shopSellListHandler })))
appGroup.use({ path: '商店出售页', schema: { usage: '/商店出售页 <页码> [关键词]', args: [{ name: 'page', rules: [{ required: true, type: 'number', min: 1 }] }, { name: 'keyword' }] } }, () => import('./response/guild-shop').then(module => ({ default: module.shopSellListHandler })))
appGroup.use({ path: '商店出售搜索', schema: { usage: '/商店出售搜索 <物品名关键词>', args: [{ name: 'keyword', rules: [{ required: true }] }] } }, () => import('./response/guild-shop').then(module => ({ default: module.shopSellSearchHandler })))
appGroup.use({ path: '出售商品', schema: { usage: '/出售商品 <物品编号> [数量]', args: [{ name: 'id', rules: [{ required: true, type: 'number', min: 1 }] }, { name: 'quantity', rules: [{ type: 'number', min: 1 }] }] } }, () => import('./response/guild-shop').then(module => ({ default: module.shopSellHandler })))
appGroup.use('商店闲聊', () => import('./response/guild-shop').then(module => ({ default: module.shopChatHandler })))
appGroup.use({ path: '接取悬赏', schema: { usage: '/接取悬赏 <编号>', args: [{ name: 'id', rules: [{ required: true, type: 'number', min: 1 }] }] } }, () => import('./response/bounty').then(module => ({ default: module.acceptBountyHandler })))
appGroup.use({ path: '领取悬赏', schema: { usage: '/领取悬赏 <编号>', args: [{ name: 'id', rules: [{ required: true, type: 'number', min: 1 }] }] } }, () => import('./response/bounty').then(module => ({ default: module.claimBountyHandler })))
appGroup.use('职业选择', () => import('./response/adventure').then(module => ({ default: module.professionHandler('select') })))
appGroup.use({ path: '职业查看', schema: { usage: '/职业查看 <职业>', args: [{ name: 'name', rules: [{ required: true, type: 'enum', enum: ['战士', '法师', '盗贼', '牧师'] }] }] } }, () => import('./response/adventure').then(module => ({ default: module.professionHandler('detail') })))
appGroup.use({ path: '选择职业', schema: { usage: '/选择职业 <职业>', args: [{ name: 'name', rules: [{ required: true, type: 'enum', enum: ['战士', '法师', '盗贼', '牧师'] }] }] } }, () => import('./response/adventure').then(module => ({ default: module.professionHandler('choose') })))
appGroup.use('前台闲聊', () => import('./response/adventure').then(module => ({ default: module.guildChatHandler })))
appGroup.use('卡片', () => import('./response/adventure').then(module => ({ default: module.adventurerCardHandler })))
appGroup.use({ path: '梨子喵预览', schema: { usage: '/梨子喵预览 [图片URL]', args: [{ name: 'url', rules: [{ type: 'rest' }] }] } }, () => import('./response/adventure').then(module => ({ default: module.pearGuidePreviewHandler })))
appGroup.use('梨子喵', () => import('./response/adventure').then(module => ({ default: module.pearGuideHandler })))
appGroup.use('梨子喵闲聊', () => import('./response/adventure').then(module => ({ default: module.pearGuideChatHandler })))
appGroup.use('梨子喵离开', () => import('./response/adventure').then(module => ({ default: module.pearGuideLeaveHandler })))
appGroup.use({ path: 'NPC离开', schema: { usage: '/NPC离开 <编号>', args: [{ name: 'code', rules: [{ required: true }] }] } }, () => import('./response/adventure').then(module => ({ default: module.npcLeaveHandler })))
appGroup.use({ path: 'NPC对话', schema: { usage: '/NPC对话 <编号>', args: [{ name: 'code', rules: [{ required: true }] }] } }, () => import('./response/adventure').then(module => ({ default: module.npcEncounterHandler('talk') })))
appGroup.use({ path: 'NPC忽略', schema: { usage: '/NPC忽略 <编号>', args: [{ name: 'code', rules: [{ required: true }] }] } }, () => import('./response/adventure').then(module => ({ default: module.npcEncounterHandler('ignore') })))
appGroup.use('攻击', () => import('./response/combat').then(module => ({ default: module.attack })))
appGroup.use('鉴识', () => import('./response/combat-appraisal'))
appGroup.use({ path: '技能', schema: { usage: '/技能 <1-4>', args: [{ name: 'slot', rules: [{ required: true, type: 'number', min: 1, max: 4 }] }] } }, () => import('./response/combat').then(module => ({ default: module.skill })))
appGroup.use({ path: '道具', schema: { usage: '/道具 <1-4>', args: [{ name: 'slot', rules: [{ required: true, type: 'number', min: 1, max: 4 }] }] } }, () => import('./response/combat').then(module => ({ default: module.item })))
appGroup.use('逃跑', () => import('./response/combat').then(module => ({ default: module.escape })))
appGroup.use('组队 创建', () => import('./response/party-create'))
appGroup.use({ path: '组队 加入', schema: { usage: '/组队 加入 <队长QQ用户ID>', args: [{ name: 'leader', rules: [{ required: true }] }] } }, () => import('./response/party-join'))

export default defineChildren({
  // 注册内容
  register() {
    return {
      responseRouter: router.define,
      expose: expose,
      koaRouter: r
    };
  },
  // 当准备好时
  onReady() {
    logger.info('本地测试启动');
    void getPool()
      // 重启时保留所有现有小怪坐标，只补足缺失数量；整点任务才执行完整数量校正与 Boss 刷新。
      .then(async pool => { await refreshDungeons(pool); await spawnMonsters({ refreshBosses: false, trimExcess: false }); logger.info('游戏数据库、初始地图与怪物群已就绪'); })
      .catch(error => logger.error({ err: error }, '游戏数据库初始化失败'));
    // 延时前往的最终状态以数据库为准；即使开发热重载或短暂重连让消息计时器丢失，也会自动补结算坐标。
    setInterval(() => {
      if (settlingDueTravels) return;
      settlingDueTravels = true;
      void settleDueTravels()
        .catch(error => logger.warn({ err: error }, '到期移动补偿结算失败'))
        .finally(() => { settlingDueTravels = false; });
    }, 1000);
    setCron('0 * * * *', () => void getPool().then(async pool => { await refreshShopStocks(pool); await refreshBounties(pool); await refreshDungeons(pool, { refreshMonsters: true }); await spawnMonsters(); }).catch(error => logger.error({ err: error }, '整点刷新失败')));
  }
});
