plugins {
    id 'com.android.application'
}

android {
    namespace 'com.fantasyfinal.pet'
    compileSdk 34

    defaultConfig {
        applicationId "com.fantasyfinal.pet"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "0.1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
